### ISSUE TITLE
getting error when run ionic serve command

### ISSUE THREAD

**Issue by Abdul-majid-ashrafi** [driftyco/ionic-cli#1001]
RangeError: Maximum call stack size exceeded
    at String.match (native)
    at Object.exports.fromSource (c:\Users\Mani\Desktop\New folder (2)\applixation\node_modules\convert-source-map\index.js:122:19)
    at DestroyableTransform.sourceMapInit [as _transform](c:UsersManiDesktopNew folder %282%29applixationnode_modulesgulp-sourcemapsindex.js:36:27)
    at DestroyableTransform.Transform._read (c:\Users\Mani\Desktop\New folder (2)\applixation\node_modules\through2\node_modules\readable-stream\lib_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (c:\Users\Mani\Desktop\New folder (2)\applixation\node_modules\through2\node_modules\readable-stream\lib_stream_transform.js:147:83)
    at doWrite (c:\Users\Mani\Desktop\New folder (2)\applixation\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:313:64)
    at writeOrBuffer (c:\Users\Mani\Desktop\New folder (2)\applixation\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (c:\Users\Mani\Desktop\New folder (2)\applixation\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:241:11)
    at write (c:\Users\Mani\Desktop\New folder (2)\applixation\node_modules\vinyl-buffer\node_modules\readable-stream\lib_stream_readable.js:623:24)
    at flow (c:\Users\Mani\Desktop\New folder (2)\applixation\node_modules\vinyl-buffer\node_modules\readable-stream\lib_stream_readable.js:632:7)

**Comment by mashhadi** [comment]
i have experiencing the same issue right now.

**Comment by coderabsolute** [comment]
me too getting the similar error, here is the exception am experiencing:



Caught exception:
 RangeError: Maximum call stack size exceeded
    at String.match (native)
    at Object.exports.fromSource (C:\xxxx\\MyIonic2ProjectTs\node_modules\convert-source-map\index.js:122:19)
    at DestroyableTransform.sourceMapInit [as _transform] (C:\xxxx\\MyIonic2ProjectTs\node_modules\gulp-sourcemaps\index.js:36:27)
    at DestroyableTransform.Transform._read (C:\xxxx\\MyIonic2ProjectTs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (C:\xxxx\\MyIonic2ProjectTs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (C:\xxxx\\MyIonic2ProjectTs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:313:64)
    at writeOrBuffer (C:\xxxx\\MyIonic2ProjectTs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (C:\xxxx\\MyIonic2ProjectTs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:241:11)
    at write (C:\xxxx\\MyIonic2ProjectTs\node_modules\vinyl-buffer\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (C:\xxxx\\MyIonic2ProjectTs\node_modules\vinyl-buffer\node_modules\readable-stream\lib\_stream_readable.js:632:7)

```

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by astro44** [comment]
had the same issue... ran ionic info:
Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v6.2.0

**Comment by 1415003719** [comment]
@jthoms1 can you help us,i also getting the issue

**Comment by jodybrewster** [comment]
same here...
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v7.2.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jthoms1** [comment]
@jodybrewster Could you provide the output of the error? This thread is pretty old so likely your error is different.
