### ISSUE TITLE
Error when running "ionic serve" on tutorial for v2

### ISSUE THREAD

**Issue by stevenbuchko** [driftyco/ionic-cli#1002]
I'm going through the documentation for v2 and I get the following error when I run "ionic serve" on the tutorial project:

```
Running 'serve:before' gulp task before serve
[22:37:35] Starting 'clean'...
[22:37:35] Finished 'clean' after 6.66 ms
[22:37:35] Starting 'watch'...
[22:37:35] Starting 'sass'...
[22:37:35] Starting 'html'...
[22:37:35] Starting 'fonts'...
[22:37:35] Starting 'scripts'...
[22:37:35] Finished 'scripts' after 32 ms
[22:37:35] Finished 'html' after 38 ms
[22:37:35] Finished 'fonts' after 43 ms
Caught exception:
 ReferenceError: Promise is not defined
    at LazyResult.async (/home/stevenbuchko/IonicProjects/MyIonic2Project/node_modules/ionic-gulp-sass-build/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/home/stevenbuchko/IonicProjects/MyIonic2Project/node_modules/ionic-gulp-sass-build/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:79:21)
    at DestroyableTransform._transform (/home/stevenbuchko/IonicProjects/MyIonic2Project/node_modules/ionic-gulp-sass-build/node_modules/gulp-autoprefixer/index.js:24:6)
    at DestroyableTransform.Transform._read (/home/stevenbuchko/IonicProjects/MyIonic2Project/node_modules/ionic-gulp-sass-build/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/home/stevenbuchko/IonicProjects/MyIonic2Project/node_modules/ionic-gulp-sass-build/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/home/stevenbuchko/IonicProjects/MyIonic2Project/node_modules/ionic-gulp-sass-build/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/home/stevenbuchko/IonicProjects/MyIonic2Project/node_modules/ionic-gulp-sass-build/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/home/stevenbuchko/IonicProjects/MyIonic2Project/node_modules/ionic-gulp-sass-build/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at DestroyableTransform.ondata (/home/stevenbuchko/IonicProjects/MyIonic2Project/node_modules/ionic-gulp-sass-build/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:531:20)
    at DestroyableTransform.emit (events.js:95:17)
```

**Comment by dcumbo** [comment]
I'm having the same issue.

**Comment by jgw96** [comment]
@stevenbuchko Hello! Thanks for opening an issue with us! What version of node.js are you running?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
