### ISSUE TITLE
Exception when creating IonicV2 tutorial project with TypeScript

### ISSUE THREAD

**Issue by Sako73** [driftyco/ionic-cli#1006]
ionic start MyIonic2Project tutorial --ts
Creating Ionic app in folder C:\test1\MyIonic2Project based on tutorial project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-tutorial/archive/master.zip
Caught exception:
 TypeError: Cannot read property 'bold' of undefined
    at Request._callback (C:\Users\S\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\utils.js:114:37)
    at Request.self.callback (C:\Users\S\AppData\Roaming\npm\node_modules\ionic\node_modules\request\request.js:373:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\S\AppData\Roaming\npm\node_modules\ionic\node_modules\request\request.js:1318:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\S\AppData\Roaming\npm\node_modules\ionic\node_modules\request\request.js:1266:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by Sako73** [comment]
I misunderstood the documentation.  When it said to use the "--ts" parameter, I thought it meant to replace the "--v2" parameter.  When I used both, it worked fine.

Thanks.
