### ISSUE TITLE
ionic run android TypError after BUILD SUCCESSFUL

### ISSUE THREAD

**Issue by jQrgen** [driftyco/ionic-cli#1009]
**BUILD SUCCESSFUL**

Total time: 34.953 secs
Built the following apk(s): 
	/Users/Stian/flareprog/flare/platforms/android/build/outputs/apk/android-debug.apk
Using apk: /Users/Stian/flareprog/flare/platforms/android/build/outputs/apk/android-debug.apk
Caught exception:
 TypeError: invalid data
    at WriteStream.Socket.write (net.js:623:11)
    at WriteStream.stream.write (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/ansi/lib/newlines.js:36:21)
    at Socket.<anonymous> (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/lib/ionic/cordova.js:284:22)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:529:20) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Caught exception:
 TypeError: invalid data
    at WriteStream.Socket.write (net.js:623:11)
    at WriteStream.stream.write (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/npm/node_modules/ansi/lib/newlines.js:36:21)
    at Socket.<anonymous> (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/lib/ionic/cordova.js:284:22)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:529:20) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Stians-iMac:flare Stian$ ionic info
Your system information:**

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.2.1-nightly-1867
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.5 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jQrgen** [comment]
No :)
