### ISSUE TITLE
ionic2 upload error

### ISSUE THREAD

**Issue by aqqadk** [driftyco/ionic-cli#1016]
#### Short description of the problem:
Attempting to run "ionic upload" and getting error.

#### What behavior are you expecting?
Expecting to login and upload.

**Steps to reproduce:**
1. Get a c9.io vm running
2. install ionic2
3. attempt to upload

```
Error logging in

TypeError: log.info.log is not a function
    at /home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/ionic/lib/ionic/login.js:35:14
    at _fulfilled (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)


log.info.log is not a function (CLI v2.0.0-beta.25)

Your system information:

Cordova CLI: Not installed
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Distributor ID:     Ubuntu Description:     Ubuntu 14.04.3 LTS 
Node Version: v4.4.3
```

**Comment by jthoms1** [comment]
Thanks for reporting.  This issue was resolved with commit: 345993aa1e65d5 and will be released in the next beta this week.
