### ISSUE TITLE
 Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by bit4bit** [driftyco/ionic-cli#1029]
Hi,

i just try [ionic v2 installing](http://ionicframework.com/docs/v2/getting-started/installation/), when run **ionic platform add android** or **ionic plugin add cordova-plugin-inappbrowser**

throws 
~~~bash
 TypeError: Cannot read property 'slice' of undefined
    at Object.run (/usr/local/lib/node_modules/ionic/lib/ionic/platform.js:35:32)
    at Promise.apply (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:1078:26)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:1304:14
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:449:3 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
~~~

**ionic version: 2.0.0-beta.26**
**cordova: 6.2.0**

thanks

**Comment by leoncheek** [comment]
I got the same problem.😂
When i run ionic platform add ios,
the TypeError: Cannot read property 'slice' of undefined showed.

**Comment by webgear88** [comment]
Me too,

Caught exception:
 TypeError: Cannot read property 'slice' of undefined
    at Object.run (/usr/local/lib/node_modules/ionic/lib/ionic/run.js:44:32)
    at Promise.apply (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:1078:26)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:1304:14
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

ionic version: 2.0.0-beta.26
cordova: 6.2.0

**Comment by zoranSpare** [comment]
I think this is a Beta26 issue as it only started after I updated to beta26. On my other machine which hasn't been updated it's working fine.

**Comment by onkelfredrik** [comment]
same problem here!

**Comment by Geaz** [comment]
Same here! This seems to be a major problem. Even the build command has this error.
Seems like the 'rawCliArguments' is not passed to the method 'run' calls and the scripts try to to a 'slice' on 'undefined'.

**Comment by madhassan** [comment]
hello everyone!
did someone find the solution for this? i am also getting the same error.

**Comment by DidelotK** [comment]
As said @onkelfredrik if you downgrade your version of ionic it's works ( it works for me in any case), so try this:
npm i -g ionic@2.0.0-beta.25

**Comment by jthoms1** [comment]
I am working on a fix for this and should have it out in a few hours. Thanks for reporting.

**Comment by sfabriece** [comment]
@jthoms1 can you update here when the fix is out. Also where can we find the changelog for ionic-cli?

**Comment by jthoms1** [comment]
I will post an update here.  The beta work is currently done in the v2 branch.  https://github.com/driftyco/ionic-cli/blob/v2/CHANGELOG.md

**Comment by jthoms1** [comment]
Commit 5549b828c87b2ea5cf29ccb1c562d519bb6ee1b5 fixes this issue.

beta.27 is now on NPM.  You can update by installing from beta tag.  `npm i -g ionic@beta`

Thanks for your patience!

**Comment by sfabriece** [comment]
Thanks @jthoms1

**Comment by bit4bit** [comment]
Thanks @jthoms1
