### ISSUE TITLE
exception during platform add in ionic 2.0.0-Beta.26

### ISSUE THREAD

**Issue by CharlesJu1** [driftyco/ionic-cli#1035]
I am getting an exception when adding a platform to my ionic 2 project. 

C:\Users\cju\Documents\Projects\Bus-App>ionic --verbose platform add browser
Task: title=add, name=add, summary=Add an Ion, bower component, or addon to the project, [name]=The name of the ion, bow
er component, or addon you wish to install, isProjectTask=true, run=function run(ionic, argv) {

  if (!bower.checkForBower()) {
    appLibUtils.fail(bower.installMessage, 'add');
    return;
  }

  var componentName = argv._[1];
  var ioSet = false;

  try {
    ioSet = true;
    installBowerComponent(componentName);
  } catch (error) {
    var errorMessage = error.message ? error.message : error;
    appLibUtils.fail(errorMessage, 'service');
  }

  // Inject the component into our index.html, if necessary, and save the app_id
  ioLib.injectIoComponent(ioSet, componentName);
  ioLib.warnMissingData();
}
Looking up Ionic root, cwd: C:\Users\cju\Documents\Projects\Bus-App
Ionic root directory:  C:\Users\cju\Documents\Projects\Bus-App
Gulpfile found

[[The following line is a debug I added. It shows result.output in CheckForBower is undefined]]
C:\Users\cju\AppData\Roaming\npm\node_modules\ionic\lib\utils\bower.js result.output: undefined

Caught exception:
 TypeError: Cannot read property 'indexOf' of undefined
    at Object.checkForBower (C:\Users\cju\AppData\Roaming\npm\node_modules\ionic\lib\utils\bower.js:54:20)
    at Object.run (C:\Users\cju\AppData\Roaming\npm\node_modules\ionic\lib\ionic\add.js:48:14)
    at Promise.apply (C:\Users\cju\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:1078:26)
    at Promise.promise.promiseDispatch (C:\Users\cju\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:741:41)
    at C:\Users\cju\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:1304:14
    at flush (C:\Users\cju\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:108:17)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by jthoms1** [comment]
Fixed by 53bcbbb.  Could you please try the latest ionic beta? https://github.com/driftyco/ionic-cli/blob/v2/CHANGELOG.md

Thanks

**Comment by CharlesJu1** [comment]
Confirmed it is fixed. Beta.30 works fine.
