### ISSUE TITLE
Error occurred while adding plugin

### ISSUE THREAD

**Issue by tleite** [driftyco/ionic-cli#1036]
I'm on Windows 7 using Powershell and Ionic 2 beta.29

I get "Error occurred while adding plugin" when starting a new app.

The entire log is below:

----------------------

PS C:\Projects> ionic start cutePuppyPics --v2
Creating Ionic app in folder C:\Projects\cutePuppyPics based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...

Adding initial native plugins
Initializing cordova project without CLI
Error occurred while adding plugin:  Error: Cannot find module 'detective'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\tleite2\AppData\Roaming\nvm\v4.4.0\node_modules\ionic\node_modules\ionic-app-lib\nod
e_modules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\module-deps\index.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
Error with start Error: Cannot find module 'detective'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\tleite2\AppData\Roaming\nvm\v4.4.0\node_modules\ionic\node_modules\ionic-app-lib\nod
e_modules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\module-deps\index.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
Error Initializing app: Error: Cannot find module 'detective'
 Error: Cannot find module 'detective'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\tleite2\AppData\Roaming\nvm\v4.4.0\node_modules\ionic\node_modules\ionic-app-lib\nod
e_modules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\module-deps\index.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
Caught exception:
 Error: Cannot find module 'detective'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\tleite2\AppData\Roaming\nvm\v4.4.0\node_modules\ionic\node_modules\ionic-app-lib\nod
e_modules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\module-deps\index.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Error occurred while adding plugin:  Error: Cannot find module 'detective'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\tleite2\AppData\Roaming\nvm\v4.4.0\node_modules\ionic\node_modules\ionic-app-lib\nod
e_modules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\module-deps\index.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
Error occurred while adding plugin:  Error: Cannot find module 'detective'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\tleite2\AppData\Roaming\nvm\v4.4.0\node_modules\ionic\node_modules\ionic-app-lib\nod
e_modules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\module-deps\index.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
Error occurred while adding plugin:  Error: Cannot find module 'detective'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\tleite2\AppData\Roaming\nvm\v4.4.0\node_modules\ionic\node_modules\ionic-app-lib\nod
e_modules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\module-deps\index.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
Error occurred while adding plugin:  Error: Cannot find module 'detective'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\tleite2\AppData\Roaming\nvm\v4.4.0\node_modules\ionic\node_modules\ionic-app-lib\nod
e_modules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\module-deps\index.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
Error occurred while adding plugin:  Error: Cannot find module 'detective'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\tleite2\AppData\Roaming\nvm\v4.4.0\node_modules\ionic\node_modules\ionic-app-lib\nod
e_modules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\module-deps\index.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by raja95shah** [comment]
Looks like your `npm` isnt installed properly. Could you check if its properly installed with latest upgrade or at least version `3.9.0`

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by cmoro-deusto** [comment]
I had the exact same problem and resolved it by updating `cordova`:
```
npm install -g cordova
```

 and rerunning `ionic start`

**Comment by jae-rebel** [comment]
I am experiencing the same issue as above. I tried all the options mentioned in this forum but the error still persists. 

npm version: 3.10.10
