### ISSUE TITLE
[Bug][Crit] TypeError: Can't call method on  undefined  ??

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic-cli#1038]
I recently faced this issue when trying to compile android and send the apk to Google Play, need urgent help:

```sh
[16:18:53] Finished 'build' after 19 s
[16:18:53] Starting 'build:before'...
[16:18:53] Finished 'build:before' after 3.78 μs

Running command: /mnt/LinHDD/Carlos/Programming/taoappionic2/hooks/after_prepare/010_add_platform_class.js /mnt/LinHDD/Carlos/Programming/taoappionic2


add to body class: platform-android

ANDROID_HOME=/mnt/LinHDD/Android/Sdk

JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

null

org.xwalk:xwalk_core_library_beta:18+


Caught exception:
 TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (/mnt/LinHDD/Carlos/Programming/taoappionic2/node_modules/core-js/modules/_defined.js:3:28)
    at createHTML (/mnt/LinHDD/Carlos/Programming/taoappionic2/node_modules/core-js/modules/_string-html.js:7:19)
    at bold (/mnt/LinHDD/Carlos/Programming/taoappionic2/node_modules/core-js/modules/es6.string.bold.js:5:12)
    at cb (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:206:7)
    at done (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:167:19)
    at /home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:40:16
    at /home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:193:9
    at [object Object].Console.log (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/transports/console.js:127:3)
    at emit (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:186:17)
    at /home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:157:13
    at _each (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:156:9)
    at [object Object].Logger.log (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:214:9)
    at [object Object].target.(anonymous function) [as error] (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/common.js:54:18)
    at Socket.<anonymous> (/home/carlos/.npm-global/lib/node_modules/ionic/lib/utils/cordova.js:83:11)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:534:20) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues


Caught exception:
 TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (/mnt/LinHDD/Carlos/Programming/taoappionic2/node_modules/core-js/modules/_defined.js:3:28)
    at createHTML (/mnt/LinHDD/Carlos/Programming/taoappionic2/node_modules/core-js/modules/_string-html.js:7:19)
    at bold (/mnt/LinHDD/Carlos/Programming/taoappionic2/node_modules/core-js/modules/es6.string.bold.js:5:12)
    at cb (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:206:7)
    at done (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:167:19)
    at /home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:40:16
    at /home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:193:9
    at [object Object].Console.log (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/transports/console.js:127:3)
    at emit (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:186:17)
    at /home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:157:13
    at _each (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:156:9)
    at [object Object].Logger.log (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:214:9)
    at [object Object].target.(anonymous function) [as error] (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/common.js:54:18)
    at Socket.<anonymous> (/home/carlos/.npm-global/lib/node_modules/ionic/lib/utils/cordova.js:83:11)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:534:20) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues


BUILD FAILED

Total time: 3.101 secs


Caught exception:
 TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (/mnt/LinHDD/Carlos/Programming/taoappionic2/node_modules/core-js/modules/_defined.js:3:28)
    at createHTML (/mnt/LinHDD/Carlos/Programming/taoappionic2/node_modules/core-js/modules/_string-html.js:7:19)
    at bold (/mnt/LinHDD/Carlos/Programming/taoappionic2/node_modules/core-js/modules/es6.string.bold.js:5:12)
    at cb (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:206:7)
    at done (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:167:19)
    at /home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:40:16
    at /home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:193:9
    at [object Object].Console.log (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/transports/console.js:127:3)
    at emit (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:186:17)
    at /home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:157:13
    at _each (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:156:9)
    at [object Object].Logger.log (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:214:9)
    at [object Object].target.(anonymous function) [as error] (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/common.js:54:18)
    at Socket.<anonymous> (/home/carlos/.npm-global/lib/node_modules/ionic/lib/utils/cordova.js:83:11)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:534:20) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues


Caught exception:
 TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (/mnt/LinHDD/Carlos/Programming/taoappionic2/node_modules/core-js/modules/_defined.js:3:28)
    at createHTML (/mnt/LinHDD/Carlos/Programming/taoappionic2/node_modules/core-js/modules/_string-html.js:7:19)
    at bold (/mnt/LinHDD/Carlos/Programming/taoappionic2/node_modules/core-js/modules/es6.string.bold.js:5:12)
    at cb (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:206:7)
    at done (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:167:19)
    at /home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:40:16
    at /home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:193:9
    at [object Object].Console.log (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/transports/console.js:127:3)
    at emit (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:186:17)
    at /home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:157:13
    at _each (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:156:9)
    at [object Object].Logger.log (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:214:9)
    at [object Object].target.(anonymous function) [as error] (/home/carlos/.npm-global/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/common.js:54:18)
    at Socket.<anonymous> (/home/carlos/.npm-global/lib/node_modules/ionic/lib/utils/cordova.js:83:11)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:534:20) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Caught exception:
 undefined 
```

**Comment by Luchillo** [comment]
**Update**: After copying the config.xml, deleting some values that were not there, and using `ionic state reset` the project compiles again, but still that caught exception still shows up, even if it's just a warning it's freaking me out.

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by Luchillo** [comment]
It still shows those errors when compiling Android, tough the app works fine.

**Comment by jgw96** [comment]
Hmm, how are you installing the android sdk? By installing Android studio?

**Comment by jgw96** [comment]
Also, what version of the cli are you running?

**Comment by Luchillo** [comment]
I'm not sure if i'll be able to replicate again, i have to re-install OS since the mac i was working on just broke.

**Comment by jgw96** [comment]
@Luchillo ahh ok. I will close this issue for now, but if you run into it again feel free to comment and i will happily reopen. Thanks for using Ionic!

**Comment by almost92** [comment]
I am getting the same when running  ionic build android, how can I solve it ?

I have jdk 1.7, npm version 3.10.5 and I got the android sdk using the package manager of android studio.

**Comment by davidwdan** [comment]
@almost92 From what I can tell, cordova.js is trying to log an error with`.bold()`, which throws an exception.  If you want to see the error that's being logged, remove `.bold()` from `/lib/node_modules/ionic/lib/utils/cordova.js:83:11`

This is a hack, but it'll allow you to see what the underlying issue it.

**Comment by Luchillo** [comment]
@jgw96 Where should we report this `.bold()` method so it get's fixed, here in ionic or in cordova?

**Comment by jmart2015** [comment]
Thank you @davidwdan, that did the trick. 
In my version, the line is 213, and  'log.info(('Setup Live Reload').green**.bold**); ' should be 'log.info(('Setup Live Reload').green); '

cordova 6.3.1
ionic 2.0.0

Thanks again!

**Comment by Luchillo** [comment]
@jgw96 There's still the same error happening with that `.bold()` method, literally where should we report this so it can be fixed?

**Comment by nobol** [comment]
Had the same error in another file (globally installed): 

`/usr/local/lib/node_modules/ionic/lib/ionic/add.js` line 51 

I simply changed `log.info(deprecationMsg.bold);` to `log.info(deprecationMsg.bold);`

This seems to be related to the already described problems.

**Comment by Luchillo** [comment]
@nobol Dude, i literally don't see a difference between your before/after comparison.

**Comment by sdemurjian** [comment]
getting the same error here

**Comment by Luchillo** [comment]
Check https://github.com/driftyco/ionic-cli/issues/1038#issuecomment-234997779 to remove the error that hides your real error.

**Comment by OBout** [comment]
I fixed it by simply doing "ionic resources", then all of a sudden it gave "build succeed"

**Comment by Luchillo** [comment]
Well i had this issue by a `resources` error, and some other times were different errors, the issue is that the `.bold` issue hides the real issue you're having, thus harder to spot the issue that triggered the `.bold` one.

**Comment by Freundschaft** [comment]
I just experienced the error, #1038 (comment) was helping, but I'm still wondering why the ionic CLI crashes and isn't able to produce the real underlying error message (which in my case was a missing sdk level for android) Doesnt this need further inspection?

**Comment by jayaj12** [comment]
I also experienced this error. removing bold helped

**Comment by budda** [comment]
Also suffering from this problem when doing an ```$ ionic run ios```

```
Caught exception:
 TypeError: Can't call method on  undefined
    at module.exports (/Users/mike/Code/sandwich-van/SandwichVan/node_modules/core-js/modules/_defined.js:3:28)
    at createHTML (/Users/mike/Code/sandwich-van/SandwichVan/node_modules/core-js/modules/_string-html.js:7:19)
    at bold (/Users/mike/Code/sandwich-van/SandwichVan/node_modules/core-js/modules/es6.string.bold.js:5:12)
    at cb (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:206:7)
    at done (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:167:19)
    at /usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:40:16
    at /usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:193:9
    at exports.Console.Console.log (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/transports/console.js:127:3)
    at emit (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:186:17)
    at /usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:157:13
    at _each (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:156:9)
    at exports.Logger.Logger.log (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:214:9)
    at exports.Logger.target.(anonymous function) [as error] (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/common.js:54:18)
    at Socket.<anonymous> (/usr/local/lib/node_modules/ionic/lib/utils/cordova.js:83:11)
    at emitOne (events.js:101:20)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues


Caught exception:
 TypeError: Can't call method on  undefined
    at module.exports (/Users/mike/Code/sandwich-van/SandwichVan/node_modules/core-js/modules/_defined.js:3:28)
    at createHTML (/Users/mike/Code/sandwich-van/SandwichVan/node_modules/core-js/modules/_string-html.js:7:19)
    at bold (/Users/mike/Code/sandwich-van/SandwichVan/node_modules/core-js/modules/es6.string.bold.js:5:12)
    at cb (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:206:7)
    at done (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:167:19)
    at /usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:40:16
    at /usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:193:9
    at exports.Console.Console.log (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/transports/console.js:127:3)
    at emit (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:186:17)
    at /usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:157:13
    at _each (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:156:9)
    at exports.Logger.Logger.log (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:214:9)
    at exports.Logger.target.(anonymous function) [as error] (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/common.js:54:18)
    at Socket.<anonymous> (/usr/local/lib/node_modules/ionic/lib/utils/cordova.js:83:11)
    at emitOne (events.js:101:20)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues


Caught exception:
 TypeError: Can't call method on  undefined
    at module.exports (/Users/mike/Code/sandwich-van/SandwichVan/node_modules/core-js/modules/_defined.js:3:28)
    at createHTML (/Users/mike/Code/sandwich-van/SandwichVan/node_modules/core-js/modules/_string-html.js:7:19)
    at bold (/Users/mike/Code/sandwich-van/SandwichVan/node_modules/core-js/modules/es6.string.bold.js:5:12)
    at cb (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:206:7)
    at done (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:167:19)
    at /usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:40:16
    at /usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:193:9
    at exports.Console.Console.log (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/transports/console.js:127:3)
    at emit (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:186:17)
    at /usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:157:13
    at _each (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:156:9)
    at exports.Logger.Logger.log (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:214:9)
    at exports.Logger.target.(anonymous function) [as error] (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/common.js:54:18)
    at Socket.<anonymous> (/usr/local/lib/node_modules/ionic/lib/utils/cordova.js:83:11)
    at emitOne (events.js:101:20)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

No clues on how to trace back to the source of the probem.
Removed all hooks from project in case it was one of them - no change.

**Comment by AmberWilkie** [comment]
Thank you @davidwdan !! This livereload problem was destroying my life. Removing the `.bold` made everything work.

**Comment by Luchillo** [comment]
What? is this issue still bothering people in latest version? the Ionic staff should have fixed it long ago, is not that big of a change for god's sake.
