### ISSUE TITLE
ionic@2.0.0-beta.29 throws on `ionic add ionic-platform-web-client`

### ISSUE THREAD

**Issue by dasilvacontin** [driftyco/ionic-cli#1042]
Works using `ionic@1.7.15`.

```
➜  deploy-tutorial ionic add ionic-platform-web-client
(node:99143) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Caught exception:
 TypeError: Cannot read property 'indexOf' of undefined
    at Object.checkForBower (/Users/dasilvacontin/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/lib/utils/bower.js:52:20)
    at Object.run (/Users/dasilvacontin/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/lib/ionic/add.js:48:14)
    at Promise.apply (/Users/dasilvacontin/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/q/q.js:1078:26)
    at Promise.promise.promiseDispatch (/Users/dasilvacontin/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/q/q.js:741:41)
    at /Users/dasilvacontin/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/q/q.js:1304:14
    at flush (/Users/dasilvacontin/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:159:18)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

➜  deploy-tutorial node -v
v6.0.0
➜  deploy-tutorial npm -v
3.8.6
➜  deploy-tutorial ionic -v
2.0.0-beta.29
```

**Comment by jthoms1** [comment]
This is a duplicate for #1037. This is resolved in release ionic@2.0.0-beta.30. Thanks!
