### ISSUE TITLE
blank screen when ionic-plugin-deploy is installed in "ionic<2-initialised" deploy-tutorial

### ISSUE THREAD

**Issue by dasilvacontin** [driftyco/ionic-cli#1044]
Thing to note is, when `deploy-tutorial` is initialised using `ionic@2.0.0-beta` (though later downgraded due to plugin install bug), it no longer gets the following warning (which I do get when tutorial is initialised using `ionic@1.7.15`:

`Using this version of Cordova with older version of cordova-ios is being deprecated. Consider upgrading to cordova-ios@4.0.0 or newer.`

Could be the cause of the blank screen, but not sure.

<img width="200" alt="screenshot 2016-06-06 20 21 09" src="https://cloud.githubusercontent.com/assets/1260830/15833367/d1ebffda-2c26-11e6-9b02-0b408910cab6.png">
```bash
➜  deploy-tutorial ionic -v
1.7.15
➜  temp ionic start deploy-tutorial tabs
 ✗ (node:38531) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Creating Ionic app in folder /Users/dasilvacontin/temp/deploy-tutorial based on tabs project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Updated the hooks directory to have execute permissions
Update Config.xml
Initializing cordova project

ionic io init
Adding in iOS application by default
 ✗ (node:38531) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
➜  temp cd deploy-tutorial
ionic io init
➜  deploy-tutorial ionic io init
Initializing app with ionic.io....
Saved app_id, writing to ionic.io.bundle.min.js...
Saved api_key, writing to ionic.io.bundle.min.js...
➜  deploy-tutorial ionic add ionic-platform-web-client
 ✗ (node:43094) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Bower component installed - ionic-platform-web-client
Adding component to index.html
Injecting ionic.service.core into app.js
Saved dev_push, writing to ionic.io.bundle.min.js...
➜  deploy-tutorial ionic plugin add ionic-plugin-deploy
 ✗ (node:43335) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Updated the hooks directory to have execute permissions
Fetching plugin "ionic-plugin-deploy" via npm
Installing "ionic-plugin-deploy" for ios
 Using this version of Cordova with older version of cordova-ios is being deprecated. Consider upgrading to cordova-ios@4.0.0 or newer.
Saving plugin to package.json file
➜  deploy-tutorial ionic emulate ios
"blank screen, unusable"
```
vs
<img width="200" alt="screenshot 2016-06-06 20 35 00" src="https://cloud.githubusercontent.com/assets/1260830/15833371/d853b1ce-2c26-11e6-89c7-c656e3f42969.png">
```bash
➜  temp npm i -g ionic@beta
"lots of stuff"
└─┬ ionic@2.0.0-beta.29
"lots of stuff"
➜  temp ionic start deploy-tutorial tabs
Creating Ionic app in folder /Users/dasilvacontin/temp/deploy-tutorial based on tabs project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...

Adding initial native plugins
[=============================]  100%  0.0s

Adding in iOS application by default

add to body class: platform-ios
Downloading: https://github.com/driftyco/ionic-default-resources/archive/master.zip
[=============================]  100%  0.0s
Saving your Ionic app state of platforms and plugins
Saved platform
Saved plugins
Saved package.json

♬ ♫ ♬ ♫  Your Ionic app is ready to go! ♬ ♫ ♬ ♫

Make sure to cd into your new app directory:
  cd deploy-tutorial

To run your app in the browser (great for initial development):
  ionic serve

To run on iOS:
  ionic run ios

To run on Android:
  ionic run android

To test your app on a device easily, try Ionic View:
  http://view.ionic.io

New! Add push notifications, live app updates, and more with Ionic Platform!
  https://apps.ionic.io/signup

➜  temp cd deploy-tutorial
ionic io init
➜  deploy-tutorial ionic io init
(node:51902) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Initializing app with ionic.io....
Saved app_id, writing to ionic.io.bundle.min.js...
Saved api_key, writing to ionic.io.bundle.min.js...
➜  deploy-tutorial ionic add ionic-platform-web-client
(node:52912) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Caught exception:
 TypeError: Cannot read property 'indexOf' of undefined
    at Object.checkForBower (/Users/dasilvacontin/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/lib/utils/bower.js:52:20)
    at Object.run (/Users/dasilvacontin/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/lib/ionic/add.js:48:14)
    at Promise.apply (/Users/dasilvacontin/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/q/q.js:1078:26)
    at Promise.promise.promiseDispatch (/Users/dasilvacontin/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/q/q.js:741:41)
    at /Users/dasilvacontin/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/q/q.js:1304:14
    at flush (/Users/dasilvacontin/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:159:18)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
➜  deploy-tutorial npm i -g ionic
"lots of stuff"
└─┬ ionic@1.7.15
"lots of stuff"
➜  deploy-tutorial ionic add ionic-platform-web-client
 ✗ (node:61132) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Bower component installed - ionic-platform-web-client
Injecting ionic.service.core into app.js
Adding component to index.html
Saved dev_push, writing to ionic.io.bundle.min.js...
➜  deploy-tutorial ionic plugin add ionic-plugin-deploy
 ✗ (node:61914) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Updated the hooks directory to have execute permissions
Fetching plugin "ionic-plugin-deploy" via npm
Installing "ionic-plugin-deploy" for ios
cp: no such file or directory: /Users/dasilvacontin/temp/deploy-tutorial/resources/ios/icon/icon-40@3x.png

cp: no such file or directory: /Users/dasilvacontin/temp/deploy-tutorial/resources/ios/icon/icon-83.5@2x.png

Saving plugin to package.json file
➜  deploy-tutorial ionic plugin add ionic-plugin-deploy
"app is actually running, looks fine"
```

**Comment by jthoms1** [comment]
Fixed with 53bcbbb. This issue has been fixed in the latest release of ionic beta. https://github.com/driftyco/ionic-cli/blob/v2/CHANGELOG.md

Thanks!

**Comment by dasilvacontin** [comment]
@jthoms1 So the `deploy-tutorial` won't work unless I'm using v2 beta of the cli?

**Comment by dasilvacontin** [comment]
I would expect the tutorial to work using `ionic@1.x.x`, but it's not the case. I'm not pointing out the same problem as in https://github.com/driftyco/ionic-cli/issues/1042.

**Comment by jthoms1** [comment]
I misunderstood. The issue that I see within your output at the bottom references beta.29 and 'Cannot read property 'indexOf' of undefined'. This particular issue is resolved in beta.30.

**Comment by dasilvacontin** [comment]
Please, take a second look. What this issue is pointing out is that the tutorial is not working when using `ionic@1.x.x`.

**Comment by dasilvacontin** [comment]
The log when using `ionic@2.x.x` (which does not get a blank screen) is there for pointing out that the following warning **does not appear**, whereas it does appear when setting it up using `ionic@1.x.x`:

> Using this version of Cordova with older version of cordova-ios is being deprecated. Consider upgrading to cordova-ios@4.0.0 or newer.

**Comment by dasilvacontin** [comment]
ping @jthoms1
