### ISSUE TITLE
adding iOS weirdness

### ISSUE THREAD

**Issue by mwk24** [driftyco/ionic-cli#1050]
Marks-MacBook-Air:lantern-ionic markk$ ionic platform add ios
(node:19648) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

You have been opted out of telemetry. To change this, run: cordova telemetry on.

Error: Platform ios already added.

Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Marks-MacBook-Air:lantern-ionic markk$ ionic emulate ios
(node:19668) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

Running 'emulate:before' gulp task before emulate
[11:06:40] Starting 'clean'...
[11:06:40] Finished 'clean' after 63 ms
[11:06:40] Starting 'build'...
[11:06:40] Starting 'sass'...
[11:06:40] Starting 'html'...
[11:06:40] Starting 'fonts'...
[11:06:40] Starting 'scripts'...
[11:06:40] Finished 'scripts' after 72 ms
[11:06:40] Finished 'html' after 87 ms
[11:06:40] Finished 'fonts' after 100 ms
[11:06:42] Finished 'sass' after 1.66 s
[11:06:55] Finished 'build' after 14 s
[11:06:55] Starting 'emulate:before'...
[11:06:55] Finished 'emulate:before' after 12 μs

• You're trying to build for iosbut don't have the platform installed yet.
∆ Installing ios for you.
Installing cordova-plugin-device
Installing cordova-plugin-console
Installing cordova-plugin-whitelist
Installing cordova-plugin-splashscreen
Installing cordova-plugin-statusbar
Installing ionic-plugin-keyboard
Caught exception:
 Error: Command failed: cordova platform add ios
Error: Platform ios already added.

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:485:12) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by pyavcom** [comment]
Have pretty same problem. Did lots manipulations with ionic/cordova packages and all time same problem. Have remove platforms before each emulation start. All packages latest versions.
