### ISSUE TITLE
error while serving ionic 2 project

### ISSUE THREAD

**Issue by ameni26** [driftyco/ionic-cli#1079]
I have the ionic version 2.0.0-beta.30
when I serve my project I get this error

`Caught exception:
Error: watch node_modules/angular2/src/animate/css_animation_options.js ENOSPC

Caught exception:
node_modules/angular2/src/platform/dom/util.js ENOSPC
at exports._errnoException (util.js:860:11)
at FSWatcher.start (fs.js:1313:19)
at Object.fs.watch (fs.js:1341:11)
at createFsWatchInstance (/home/ameni/ionic/covoiturage/node_modules/chokidar/lib/nodefs-handler.js:37:15)
at setFsWatchListener (/home/ameni/ionic/covoiturage/node_modules/chokidar/lib/nodefs-handler.js:80:15)

`
and many other errors like that. Can I anyone help me to solve this problem

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
