### ISSUE TITLE
ionic start newApp -ts --v2 => TypeError: options.template.indexOf is not a function

### ISSUE THREAD

**Issue by petermetz** [driftyco/ionic-cli#1086]
OS X El Capitan 10.11.5 (15F34)

$ node --version
`v5.7.0`

$ ionic --version
`2.0.0-beta.30`

$ ionic start newApp -ts --v2
```
Creating Ionic app in folder /Users/peter.somogyvari/projects/newApp based on  project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Error with start TypeError: options.template.indexOf is not a function
    at Object.Start.fetchSeed (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:245:25)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:106:18
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
Error Initializing app: TypeError: options.template.indexOf is not a function
 TypeError: options.template.indexOf is not a function
    at Object.Start.fetchSeed (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:245:25)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:106:18
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
Caught exception:
 TypeError: options.template.indexOf is not a function
    at Object.Start.fetchSeed (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:245:25)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:106:18
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues


```

**Comment by dimpu** [comment]
Don't use -ts flag now by default it's typescript if you want  to use javascript use --no-ts  flag. It's working fine if you don't use -ts flag.
 http://ionicframework.com/docs/v2/getting-started/tutorial/

I'm using ionic 2.0.0-beta.30
node 4.4.5
npm 3.9.5

**Comment by petermetz** [comment]
Thanks very much @dimpu , that fixed it!

**Comment by esoyke** [comment]
I ran into the same error. It was caused by using a single dash for the ts option. Use --ts not -ts and it should be fine.
