### ISSUE TITLE
Error while deploying app on Genymotion Nexus 5 API 23 Emulator 

### ISSUE THREAD

**Issue by dgpuranik** [driftyco/ionic-cli#1097]
My Ionic 2 app works fine in web browser with --lab. But when I try to deploy it on running Genymotion emulator device, it gives me following error and stack trace:

```
`Exception in thread "main" 
java.lang.RuntimeException: java.net.SocketException: Operation timed out
```

	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
	at org.gradle.wrapper.Install.createDist(Install.java:47)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)

```
Caused by: java.net.SocketException: Operation timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3336)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3329)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:63)
	at org.gradle.wrapper.Download.download(Download.java:45)
	at org.gradle.wrapper.Install$1.call(Install.java:60)
	at org.gradle.wrapper.Install$1.call(Install.java:47)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	... 3 more

Error: Error code 1 for command: /Users/darshan/dev/learning/ionic/gonehybrid/ionic2-tutorial-github/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/darshan/dev/learning/ionic/gonehybrid/ionic2-tutorial-github/platforms/android/build.gradle,-PcdvBuildArch=x86,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true


Caught exception:
 undefined 
```
`

Cordova 6.2.0
Ionic 2 Beta
Angular 2 RC1
npm 3.9.3
node 6.2.0

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Could you post the output of ionic info here please? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
