### ISSUE TITLE
iOS Simulator not working

### ISSUE THREAD

**Issue by msaccone** [driftyco/ionic-cli#1102]
I´ve created an empty -blank template- project and the iOS simulator didn't work.

The first time, it hanged up on the splash screen with the loading icon mark

Then, I tried to run it with ´sudo´, and after that I´m receiving the following error,

_**Error: EACCES: permission denied, rmdir '/Users/magenta/Documents/ionic/mPlusV1/www/build/css'

    at Error (native)
/usr/local/lib/node_modules/cordova/node_modules/insight/node_modules/configstore/index.js:53
				throw err;
				^

Error: EACCES: permission denied, open '/Users/magenta/.config/configstore/insight-cordova.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.create.all.get (/usr/local/lib/node_modules/cordova/node_modules/insight/node_modules/configstore/index.js:34:26)
    at Object.Configstore (/usr/local/lib/node_modules/cordova/node_modules/insight/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/local/lib/node_modules/cordova/node_modules/insight/lib/index.js:38:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova/src/telemetry.js:37:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

    at Module.load (module.js:343:32)

Caught exception:
 undefined_**

**Comment by msaccone** [comment]
After applying a chmod 777 -R on the parent folder, removing and adding the iOS platform again, it started to work properly.
