### ISSUE TITLE
Cannot find module 'ionic-app-lib'

### ISSUE THREAD

**Issue by songokudbz** [driftyco/ionic-cli#1104]
Hello everybody,

I've installed ionic@beta, everything was ok. When I try to write ionic in the bash I get the following error:

Caught exception:
 Error: Cannot find module 'ionic-app-lib'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Users\AdrianAMadaras\AppData\Roaming\npm\node_modules\ionic\lib\cli.js:4:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

My System: Windows 7 x64

Pls help!!!

**Comment by songokudbz** [comment]
I've managed to fix this problem by completely uninstalling NODE js and reinstalling everything. Didn't know what caused the problem.
