### ISSUE TITLE
Error on "ionic push --production-mode=y"

### ISSUE THREAD

**Issue by philbenoit** [driftyco/ionic-cli#1124]
Caught exception:
 TypeError: Cannot read property 'inputValues' of undefined
    at getCmdArgValue (/usr/local/lib/node_modules/ionic/lib/ionic/push.js:431:11)
    at getCmdLineOptions (/usr/local/lib/node_modules/ionic/lib/ionic/push.js:447:3)
    at Object.run (/usr/local/lib/node_modules/ionic/lib/ionic/push.js:39:3)
    at Promise.apply (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:1078:26)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:1304:14
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
    at Function.Module.runMain (module.js:477:11)

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Could you post the output of ionic info here please? Thanks for using Ionic!

**Comment by philbenoit** [comment]
I have since updated a number of the components. I am closing as I provided insufficient information.
