### ISSUE TITLE
ionic upload crashes with project created with ionic-m

### ISSUE THREAD

**Issue by dkarchmer** [driftyco/ionic-cli#1164]
I created a project with https://github.com/mwaylabs/generator-m-ionic
Because it does not create an ionic.config.json file, I created one manually.
I then run
```
ionic upload
```

and got the following crash

```
Uploading app....
Saved app_id, writing to ionic.io.bundle.min.js...

Caught exception:
 TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (/Users/david/ArchSys/iotile-mobile-ionic/node_modules/core-js/modules/_defined.js:3:28)
    at createHTML (/Users/david/ArchSys/iotile-mobile-ionic/node_modules/core-js/modules/_string-html.js:7:19)
    at bold (/Users/david/ArchSys/iotile-mobile-ionic/node_modules/core-js/modules/es6.string.bold.js:5:12)
    at cb (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:206:7)
    at done (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:167:19)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:40:16
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:193:9
    at Console.log (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/transports/console.js:127:3)
    at emit (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:186:17)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:157:13
    at _each (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:156:9)
    at Logger.log (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:214:9)
    at target.(anonymous function) [as info] (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/common.js:54:18)
    at Request._callback (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:150:11) 
```

Clearly this is an issue due for me not using the ionic cli to create the project, but it would be nice not to crash and instead give me a nice error msg.

**Comment by dkarchmer** [comment]
Issue also reported on the generator-m-ionic project: https://github.com/mwaylabs/generator-m-ionic/issues/409

**Comment by jgw96** [comment]
Hello! Since this does not seem to be an issue with our cli, but instead something related to their setup I will be closing this issue. Our cli is actually handling this exception correctly. Thanks for using Ionic!

**Comment by dkarchmer** [comment]
You should still not crash.

**Comment by gruppjo** [comment]
@jgw96 thanks for redirecting this to us :)

**Comment by jgw96** [comment]
@gruppjo No problem!
