### ISSUE TITLE
bug: ionic serve -l,  not working

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-cli#1165]
_From @shubhamsinghrajput on July 11, 2016 6:33_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>shell.js: internal error
Error: EBUSY: resource busy or locked, open 'C:\Users\MORGEN~1\AppData\Local\Temp\shelljs_f346f45a91a42db0d0bc'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at execSync (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\shelljs\src\exec.js:67:57)
    at Object._exec (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\shelljs\src\exec.js:179:12)
    at Object.exec (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\shelljs\src\common.js:168:23)
    at Object.gatherGulpInfo (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\info.js:201:24)
    at Object.t (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\lib\utils\stats.js:148:15)
    at Object.run (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\lib\cli.js:123:16)
    at Object.<anonymous> (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\bin\ionic:13:10)</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#7262_

**Comment by shubhamsinghrajput** [comment]
same result...
with ionic info

ionic info
shell.js: internal error
Error: EBUSY: resource busy or locked, open 'C:\Users\MORGEN~1\AppData\Local\Temp\shelljs_d59ae64b5a076f1f0e51'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at execSync (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\shelljs\src\exec.js:67:57)
    at Object._exec (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\shelljs\src\exec.js:179:12)
    at Object.exec (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\shelljs\src\common.js:168:23)
    at Object.gatherGulpInfo (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\info.js:201:24)
    at Object.t (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\lib\utils\stats.js:148:15)
    at Object.run (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\lib\cli.js:123:16)
    at Object.<anonymous> (C:\Users\MorgenTEC\AppData\Roaming\npm\node_modules\ionic\bin\ionic:13:10)

**Comment by shubhamsinghrajput** [comment]
Hello, @jgw96 after repeated the same "ionic info" command i got the info, 
I am new in ionic, if i have made any mistake, please guide me. 
I will be grateful for any help you can provide.

ionic info
Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
OS:
Node Version: v6.3.0

**Comment by shubhamsinghrajput** [comment]
Hello, @brandyscarney  @jgw96 ,  I have just solved this issue.

1) cleaned all the data inside AppData\Local\Temp\  
2) cleaned the registry, 
It is working properly.

Thank you, appreciate your concern.

**Comment by myurAgarwal** [comment]
I am sorry, but it is not working for me.. i have cleared all the temp files as well clean the registries using CCleaner...
but still i am facing the same issue...
