### ISSUE TITLE
use gulp#4

### ISSUE THREAD

**Issue by rolandjitsu** [driftyco/ionic-cli#1183]
I was just trying to use gulp 4 instead of 3 in the gulpfile the `ionic start` command generates, but it looks like your CLI is dependent on version 3 and it cannot find some tasks.

Note that using v4 you get the advantage of dropping some deps, such as `run-sequence`, since v4 already provides a way to run things in series or parallel.

I get:

``` bash
TypeError: Cannot read property 'serve:before' of undefined
    at Object.runWithGulp (/Users/rolandjitsu/Projects/infarm/operator/node_modules/ionic/lib/cli.js:217:17)
    at Object.run (/Users/rolandjitsu/Projects/infarm/operator/node_modules/ionic/lib/cli.js:190:16)
    at Object.<anonymous> (/Users/rolandjitsu/Projects/infarm/operator/node_modules/ionic/bin/ionic:13:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
```

I could submit a pr if this would be an option, should be a straight forward migration.

**Comment by loki1** [comment]
+1

**Comment by armenbadalyan** [comment]
+1

**Comment by martinmine** [comment]
+1

**Comment by brunodeprez** [comment]
+1

**Comment by rolandjitsu** [comment]
I'm closing this as Ionic no longer uses Gulp, there is [ionic-app-scripts](https://github.com/driftyco/ionic-app-scripts).
