### ISSUE TITLE
After updating to Ionic 2, this is the error I receive.

### ISSUE THREAD

**Issue by tybed7** [driftyco/ionic-cli#1208]
Caught exception:
 Error: Cannot find module 'tough-cookie'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\ionic\node_modules\request\lib\cookies.js:3:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

I am using node v.4.4.5 and npm 2.15.5

**Comment by Sabiehahmed** [comment]
Im getting the same problem here '

`Caught exception:
 Error: Cannot find module 'tough-cookie'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/request/lib/cookies.js:3:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues`

**Comment by kumaro** [comment]
I am experiencing this too. any fix ?

**Comment by jtushar53** [comment]
currently reverted to beta 32, @kumaro, you can install it by ```npm install -g ionic@2.0.0-beta.32```

**Comment by rpayanm** [comment]
Same error :(

**Comment by pedroigp** [comment]
same problem here

**Comment by disono** [comment]
Same problem here

npm install -g ionic@beta

Caught exception:
 Error: Cannot find module 'tough-cookie'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\{USERNAME}\AppData\Roaming\npm\node_modules\ionic\node_modules\request\lib\cookies.js:3:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by zhchsf** [comment]
same error

**Comment by jthoms1** [comment]
Found the issue. There is a problem with npm where you need to always publish packages with bundledDependencies from npm2 with the node_modules structure of npm2 (nested). When I released ionic@2.0.0-beta.33 I was using npm3 with the flat structure. So release beta.33 would only work with npm3 installs, which is what I used for testing.

I am sorry for the pain this might have caused. It is resolved in beta.35. I have tested and we should be ok now. Please let me know if you are still having issues. Thank you!

Fix: ```npm install -g ionic@2.0.0-beta.35```
