### ISSUE TITLE
Caught exception:  Error: Cannot find module 'tough-cookie'

### ISSUE THREAD

**Issue by dilipwk** [driftyco/ionic-cli#1212]
C:\Users\Dilip>ionic start cutePuppyPics --v2
Caught exception:
 Error: Cannot find module 'tough-cookie'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Dilip\AppData\Roaming\npm\node_modules\ionic
\node_modules\request\lib\cookies.js:3:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by ubaidazad** [comment]
ionic serve

Caught exception:
 Error: Cannot find module 'tough-cookie'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\ubaid\AppData\Roaming\npm\node_modules\ionic\node_modules\request\lib\cookies.js:3:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by eltonmkw** [comment]
![screenshot 30](https://cloud.githubusercontent.com/assets/3103419/17172466/d7d94168-5427-11e6-8903-7471e35b749f.png)

**Comment by gdessard** [comment]
Same probleme with ionic@2.0.0-beta.33
I try 
npm install tough-cookie -g
It's resolve this error but after it's an other module:
Error: Cannot find module 'json-stringify-safe'

I stop here, after an another module etc...

**Comment by eltonmkw** [comment]
For every error of missing module
(Eg: `Error: Cannot find module 'json-stringify-safe'` )

Try `npm install json-stringify-safe -g`
Note that the command correspond to the missing module name.

After done all missing module, try the following command:
`ionic start myApp`
`cd myApp`

![screenshot 31](https://cloud.githubusercontent.com/assets/3103419/17174693/e31c7b18-5435-11e6-9c79-66263ba21201.png)

**Comment by j0nny** [comment]
same error ("cannot find module 'though-cookie') on my OS X 10.11.6
Install worked without errors (sudo nam install -g ionic@beta), but executing ionic (independent of parameters) throws the error.
Followed gdessard's advice and gone back to version 32, which works as usual.
Noticed that the installation takes a lot longer (installing all necessary packages..)

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by eltonmkw** [comment]
@jthoms1 Here you go :smile: 
![screenshot 32](https://cloud.githubusercontent.com/assets/3103419/17180357/bfc1162e-544e-11e6-8033-b08691c630cc.png)

**Comment by ryanjsalva** [comment]
Same problem here. 

`Caught exception:
 Error: Cannot find module 'tough-cookie'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/ryanjsalva/.nvm/versions/node/v4.4.4/lib/node_modules/ionic/node_modules/request/lib/cookies.js:3:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17) `

**Comment by purushottamjha** [comment]
Same problem, I had to npm install tons of modules one after the other.

**Comment by jthoms1** [comment]
Found the issue.  There is a problem with npm where you need to always publish packages with *bundledDependencies* from npm2 with the node_modules structure of npm2 (nested).  When I released ionic@2.0.0-beta.33 I was using npm3 with the flat structure.  So release beta.33 would only work with npm3 installs, which is what I used for testing.

I am sorry for the pain this might have caused.  It is resolved in beta.35.  I have tested and we should be ok now.  Please let me know if you are still having issues. Thank you!

Fix:  ```npm install -g ionic@2.0.0-beta.35```

**Comment by gdessard** [comment]
It' OK for me
