### ISSUE TITLE
Error: ENOENT: no such file or directory,

### ISSUE THREAD

**Issue by benBarking** [driftyco/ionic-cli#1223]
Get this error trying to build for v2 ionic:

No idea what I am doing wrong - help appreciated

Running 'run:before' gulp task before run
[21:30:43] Starting 'clean'...
[21:30:43] Finished 'clean' after 38 ms
[21:30:43] Starting 'build'...
[21:30:43] Starting 'sass'...
[21:30:43] Starting 'html'...
[21:30:43] Starting 'fonts'...
[21:30:43] Starting 'scripts'...
[21:30:43] Finished 'sass' after 22 ms
[21:30:43] Finished 'html' after 13 ms
[21:30:43] Finished 'scripts' after 40 ms
[21:30:43] Finished 'fonts' after 46 ms
Caught exception:
 Error: ENOENT: no such file or directory, lstat '/Users/BenMedland/Barkv2/app'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at Object.realpathSync (fs.js:1518:21)
    at /Users/BenMedland/Barkv2/node_modules/tsify/index.js:58:38
    at Array.map (native)
    at DestroyableTransform.flush [as _flush] (/Users/BenMedland/Barkv2/node_modules/tsify/index.js:58:6)
    at DestroyableTransform.<anonymous> (/Users/BenMedland/Barkv2/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at DestroyableTransform.emit (events.js:179:7)

**Comment by anrip** [comment]
me too!

**Comment by Mobius77x** [comment]
Getting similar.

c:\Users\Mark\My Documents\App Development\PPP>ionic serve

Running 'serve:before' gulp task before serve
[13:03:18] Starting 'clean'...
[13:03:19] Finished 'clean' after 168 ms
[13:03:19] Starting 'watch'...
[13:03:19] Starting 'sass'...
[13:03:19] Starting 'html'...
[13:03:19] Starting 'fonts'...
[13:03:19] Starting 'scripts'...
[13:03:19] Finished 'html' after 271 ms
[13:03:19] Finished 'scripts' after 295 ms
[13:03:19] Finished 'fonts' after 366 ms
[13:03:22] Finished 'sass' after 3.43 s
Caught exception:
 Error: ENOENT: no such file or directory, lstat 'C:\Users\Mark\Documents\App Development\PPP\typing
s\index.d.ts'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at Object.realpathSync (fs.js:1518:21)
    at C:\Users\Mark\Documents\App Development\PPP\node_modules\tsify\index.js:58:38
    at Array.map (native)
    at DestroyableTransform.flush [as _flush] (C:\Users\Mark\Documents\App Development\PPP\node_modu
les\tsify\index.js:58:6)
    at DestroyableTransform.<anonymous> (C:\Users\Mark\Documents\App Development\PPP\node_modules\th
rough2\node_modules\readable-stream\lib\_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at DestroyableTransform.emit (events.js:179:7)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues


The file \typings\index.d.ts'  does not exist, and I see that it doesn't exist in the Conference App, which similarly to me has

typings/browser/ambient
typings/main/ambient
typings/browser.d.ts
typings/main.d.ts

Why is something looking for index.d.ts?

**Comment by mousDZ** [comment]
me too

**Comment by PrithiviRajG** [comment]
me too...

**Comment by wightspace** [comment]
same

**Comment by st1s** [comment]
same

**Comment by Ingosmar89219** [comment]
me too. somebody can help us?

**Comment by anrip** [comment]
update your all node modules!

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.
