### ISSUE TITLE
ionic build ios error: "TypeError: Can't call method on  undefined"

### ISSUE THREAD

**Issue by jQrgen** [driftyco/ionic-cli#1269]
<h2>Env:</h2>
<code>
<pre>
Stians-iMac:flare Stian$ ionic info

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.8.5 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3.1 Build version 7D1014 
</code>
</pre>
<h2>Logs: </h2>
<code>
<pre>
Stians-iMac:flare Stian$ ionic build ios
Running command: /Users/Stian/flareprog/flare/hooks/after_prepare/010_add_platform_class.js /Users/Stian/flareprog/flare

add to body class: platform-ios

Building project  : /Users/Stian/flareprog/flare/platforms/ios/Flare dev.xcodeproj

	Configuration : Debug

	Platform      : emulator

Build settings from command line:

    ARCHS = i386
    CONFIGURATION_BUILD_DIR = /Users/Stian/flareprog/flare/platforms/ios/build/emulator
    SDKROOT = iphonesimulator9.3
    SHARED_PRECOMPS_DIR = /Users/Stian/flareprog/flare/platforms/ios/build/sharedpch
    VALID_ARCHS = i386

Build settings from configuration file '/Users/Stian/flareprog/flare/platforms/ios/cordova/build-debug.xcconfig':
    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
    CODE_SIGN_IDENTITY = iPhone Developer
    ENABLE_BITCODE = NO
    GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1
    HEADER_SEARCH_PATHS = "$(TARGET_BUILD_DIR)/usr/local/lib/include" "$(OBJROOT)/UninstalledProducts/include" "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" "$(BUILT_PRODUCTS_DIR)"
    IPHONEOS_DEPLOYMENT_TARGET = 8.0
    OTHER_LDFLAGS = -ObjC
    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h
    TARGETED_DEVICE_FAMILY = 1,2

Caught exception:
 TypeError: Can't call method on  undefined
  at TypeError (native)
  at module.exports (/Users/Stian/flareprog/flare/node_modules/core-js/modules/_defined.js:3:28)
  at createHTML (/Users/Stian/flareprog/flare/node_modules/core-js/modules/_string-html.js:7:19)
  at bold (/Users/Stian/flareprog/flare/node_modules/core-js/modules/es6.string.bold.js:5:12)
  at cb (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:206:7)
  at done (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:167:19)
  at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:40:16
  at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:193:9
  at [object Object].Console.log (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/transports/console.js:127:3)
  at emit (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:186:17)
  at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:157:13
  at _each (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:57:9)
  at Object.async.each (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:156:9)
  at [object Object].Logger.log (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:214:9)
  at [object Object].target.(anonymous function) [as error] (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/common.js:54:18)
  at Socket.<anonymous> (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/lib/utils/cordova.js:83:11)
  at emitOne (events.js:95:20)
  at Socket.emit (events.js:182:7)
  at readableAddChunk (_stream_readable.js:153:18)
  at Socket.Readable.push (_stream_readable.js:111:10)
  at Pipe.onread (net.js:529:20)
 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Caught exception:
 TypeError: Can't call method on  undefined
  at TypeError (native)
  at module.exports (/Users/Stian/flareprog/flare/node_modules/core-js/modules/_defined.js:3:28)
  at createHTML (/Users/Stian/flareprog/flare/node_modules/core-js/modules/_string-html.js:7:19)
  at bold (/Users/Stian/flareprog/flare/node_modules/core-js/modules/es6.string.bold.js:5:12)
  at cb (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:206:7)
  at done (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:167:19)
  at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:40:16
  at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:193:9
  at [object Object].Console.log (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/transports/console.js:127:3)
  at emit (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:186:17)
  at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:157:13
  at _each (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:57:9)
  at Object.async.each (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:156:9)
  at [object Object].Logger.log (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:214:9)
  at [object Object].target.(anonymous function) [as error] (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/common.js:54:18)
  at Socket.<anonymous> (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/lib/utils/cordova.js:83:11)
  at emitOne (events.js:95:20)
  at Socket.emit (events.js:182:7)
  at readableAddChunk (_stream_readable.js:153:18)
  at Socket.Readable.push (_stream_readable.js:111:10)
  at Pipe.onread (net.js:529:20)
 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Caught exception:
 TypeError: Can't call method on  undefined
  at TypeError (native)
  at module.exports (/Users/Stian/flareprog/flare/node_modules/core-js/modules/_defined.js:3:28)
  at createHTML (/Users/Stian/flareprog/flare/node_modules/core-js/modules/_string-html.js:7:19)
  at bold (/Users/Stian/flareprog/flare/node_modules/core-js/modules/es6.string.bold.js:5:12)
  at cb (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:206:7)
  at done (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:167:19)
  at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:40:16
  at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:193:9
  at [object Object].Console.log (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/transports/console.js:127:3)
  at emit (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:186:17)
  at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:157:13
  at _each (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:57:9)
  at Object.async.each (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:156:9)
  at [object Object].Logger.log (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:214:9)
  at [object Object].target.(anonymous function) [as error] (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/common.js:54:18)
  at Socket.<anonymous> (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/lib/utils/cordova.js:83:11)
  at emitOne (events.js:95:20)
  at Socket.emit (events.js:182:7)
  at readableAddChunk (_stream_readable.js:153:18)
  at Socket.Readable.push (_stream_readable.js:111:10)
  at Pipe.onread (net.js:529:20)
 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Caught exception:
 TypeError: Can't call method on  undefined
  at TypeError (native)
  at module.exports (/Users/Stian/flareprog/flare/node_modules/core-js/modules/_defined.js:3:28)
  at createHTML (/Users/Stian/flareprog/flare/node_modules/core-js/modules/_string-html.js:7:19)
  at bold (/Users/Stian/flareprog/flare/node_modules/core-js/modules/es6.string.bold.js:5:12)
  at cb (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:206:7)
  at done (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:167:19)
  at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:40:16
  at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:193:9
  at [object Object].Console.log (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/transports/console.js:127:3)
  at emit (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:186:17)
  at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:157:13
  at _each (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:57:9)
  at Object.async.each (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:156:9)
  at [object Object].Logger.log (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:214:9)
  at [object Object].target.(anonymous function) [as error] (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/common.js:54:18)
  at Socket.<anonymous> (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/lib/utils/cordova.js:83:11)
  at emitOne (events.js:95:20)
  at Socket.emit (events.js:182:7)
  at readableAddChunk (_stream_readable.js:153:18)
  at Socket.Readable.push (_stream_readable.js:111:10)
  at Pipe.onread (net.js:529:20)
 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Caught exception:
 TypeError: Can't call method on  undefined
  at TypeError (native)
  at module.exports (/Users/Stian/flareprog/flare/node_modules/core-js/modules/_defined.js:3:28)
  at createHTML (/Users/Stian/flareprog/flare/node_modules/core-js/modules/_string-html.js:7:19)
  at bold (/Users/Stian/flareprog/flare/node_modules/core-js/modules/es6.string.bold.js:5:12)
  at cb (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:206:7)
  at done (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:167:19)
  at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:40:16
  at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:193:9
  at [object Object].Console.log (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/transports/console.js:127:3)
  at emit (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:186:17)
  at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:157:13
  at _each (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:57:9)
  at Object.async.each (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:156:9)
  at [object Object].Logger.log (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:214:9)
  at [object Object].target.(anonymous function) [as error] (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/common.js:54:18)
  at Socket.<anonymous> (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/lib/utils/cordova.js:83:11)
  at emitOne (events.js:95:20)
  at Socket.emit (events.js:182:7)
  at readableAddChunk (_stream_readable.js:153:18)
  at Socket.Readable.push (_stream_readable.js:111:10)
  at Pipe.onread (net.js:529:20)
 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Caught exception:
 TypeError: Can't call method on  undefined
  at TypeError (native)
  at module.exports (/Users/Stian/flareprog/flare/node_modules/core-js/modules/_defined.js:3:28)
  at createHTML (/Users/Stian/flareprog/flare/node_modules/core-js/modules/_string-html.js:7:19)
  at bold (/Users/Stian/flareprog/flare/node_modules/core-js/modules/es6.string.bold.js:5:12)
  at cb (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:206:7)
  at done (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:167:19)
  at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:40:16
  at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:193:9
  at [object Object].Console.log (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/transports/console.js:127:3)
  at emit (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:186:17)
  at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:157:13
  at _each (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:57:9)
  at Object.async.each (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/async/lib/async.js:156:9)
  at [object Object].Logger.log (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:214:9)
  at [object Object].target.(anonymous function) [as error] (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/winston/lib/winston/common.js:54:18)
  at Socket.<anonymous> (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/lib/utils/cordova.js:83:11)
  at emitOne (events.js:95:20)
  at Socket.emit (events.js:182:7)
  at readableAddChunk (_stream_readable.js:153:18)
  at Socket.Readable.push (_stream_readable.js:111:10)
  at Pipe.onread (net.js:529:20)
 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

<code>
<pre>

**Comment by jQrgen** [comment]
Solution found: Had to update ios platform to 4.2.0:
<code>
ionic platform update ios@4.2.0 --save
</code>
