### ISSUE TITLE
Ionic serve failed with exception

### ISSUE THREAD

**Issue by ikhsan017** [driftyco/ionic-cli#1271]
Hi All,

so I was trying the ionic starter project tutorial, using ionic-cli 1.7.16 is ok, but after update to ionic-cli 2.0.0, I got this error when running ```ionic serve```, there are a lot of exception, but it looks similar, so I only put the last one

```
Caught exception:
 Error: watch /home/ikhsan/www_data/htdocs/ionic/MyIonic2Project/node_modules/@angular/compiler/src/view_compiler/compile_binding.js ENOSPC
    at exports._errnoException (util.js:893:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/home/ikhsan/www_data/htdocs/ionic/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/ikhsan/www_data/htdocs/ionic/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/ikhsan/www_data/htdocs/ionic/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/ikhsan/www_data/htdocs/ionic/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/ikhsan/www_data/htdocs/ionic/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:82:15) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

9.1 MB bytes written (17.29 seconds)
[15:07:45] Finished 'watch' after 35 s
[15:07:45] Starting 'serve:before'...
[15:07:45] Finished 'serve:before' after 8.61 μs

Live Reload failed to start, error: Error: watch /home/ikhsan/www_data/htdocs/ionic/MyIonic2Project/www/build ENOSPC
Ionic serve failed - error: Error: watch /home/ikhsan/www_data/htdocs/ionic/MyIonic2Project/www/build ENOSPC
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

ionic $
```

regards :)

**Comment by ikhsan017** [comment]
running npm install, I got this message

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN myionic2project@ No repository field.
npm WARN myionic2project@ No license field.
```

my os is ubuntu 16.04 x64 btw

**Comment by ikhsan017** [comment]
its strange, after restart the ```ionic serve``` running flawlesly
