### ISSUE TITLE
Ionic serve error with config.xml

### ISSUE THREAD

**Issue by krystalcode** [driftyco/ionic-cli#130]
Getting the following when doing an "ionic serve". Not getting errors with "phonegap serve".

Error updating /App/config.xml: TypeError: Cannot read property '0' of undefined (CLI v1.2.8)
Error parsing /App/config.xml: TypeError: Cannot read property '0' of undefined (CLI v1.2.8)

path.js:360
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Object.IonicTask.loadSettings (/usr/local/lib/node_modules/ionic/lib/ionic/serve.js:62:26)
    at Object.IonicTask.run (/usr/local/lib/node_modules/ionic/lib/ionic/serve.js:29:8)
    at Object.Ionic.run (/usr/local/lib/node_modules/ionic/lib/ionic.js:455:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/bin/ionic:10:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by jbavari** [comment]
@krystalcode - would you mind grabbing latest and seeing if this issue still shows up?
