### ISSUE TITLE
ionic start newFolder --v2 gets stuck at Installing npm packages...

### ISSUE THREAD

**Issue by Nkarimbi** [driftyco/ionic-cli#1306]
I will like to start learning ionic2, but after installing ionic globally and starting a new project on CLI
**_ionic start newFolder --v2_** 
the process gets stuck at: _**Installing npm packages...**_ and says this, 

Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

after which ionic info in the newFolder directory throws:

shell.js: internal error
Error: EBUSY: resource busy or locked, open 'C:\Users\folder\AppData\Local\Temp\shelljs_de31c3e49cfe07cbe126'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at execSync (C:\Users\folder\AppData\Roaming\npm\node_modules\ionic\node_modules\shelljs\src\exec.js:67:57)
    at Object._exec (C:\Users\folder\AppData\Roaming\npm\node_modules\ionic\node_modules\shelljs\src\exec.js:179:12)
    at Object.exec (C:\Users\folder\AppData\Roaming\npm\node_modules\ionic\node_modules\shelljs\src\common.js:168:23)
    at Object.gatherGulpInfo (C:\Users\folder\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\info.js:201:24)
    at Object.t (C:\Users\folder\AppData\Roaming\npm\node_modules\ionic\lib\utils\stats.js:148:15)
    at Object.run (C:\Users\folder\AppData\Roaming\npm\node_modules\ionic\lib\cli.js:135:16)
    at Object.<anonymous> (C:\Users\folder\AppData\Roaming\npm\node_modules\ionic\bin\ionic:13:10)

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
