### ISSUE TITLE
ionic serve failed on Mac OS X

### ISSUE THREAD

**Issue by piusng** [driftyco/ionic-cli#1314]
ionic serve 

There was an error serving your Ionic application: Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
Caught exception:
 Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26) 

It was working just last night.

**Comment by piusng** [comment]
ionic serve --address 127.0.0.1 

solved the issue.
