### ISSUE TITLE
Caught exception:  Error: Cannot find module 'ionic-app-lib'

### ISSUE THREAD

**Issue by DouDzZz** [driftyco/ionic-cli#1346]
Hello everybody,
I'm using Ionic 2 for a while, and everything is perfect...
But, since I did an npm update npm -g because npm was not able to install angularfire2.
Since when, whatever I do with Ionic (even create a knew project or ask for version), I have this error:
" **ionic -v
Caught exception:
 Error: Cannot find module 'ionic-app-lib'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/lib/cli.js:4:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues** "

I ever tried to uninstall and reinstall node as explain here: 
https://github.com/driftyco/ionic-cli/issues/1104

By the way, I have these errors when I do:
" **npm WARN enoent ENOENT: no such file or directory, open '/Users/Me/.Trash/Project/node_modules/browserify/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/Me/.Trash/Project/node_modules/buffer/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/Me/.Trash/Project/node_modules/concat-stream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/Me/.Trash/Project/node_modules/fined/package.json'
npm WARN tsify@0.14.8 requires a peer of browserify@>= 6.x but none was installed.
npm WARN projetshindyme@ No repository field.
npm WARN projetshindyme@ No license field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.3
npm ERR! path /Users/Me/.Trash/Project/node_modules/firebase/node_modules/jsonwebtoken/node_modules/jws/node_modules/base64url/node_modules/meow/node_modules/indent-string
npm ERR! code ENOTEMPTY
npm ERR! errno -66
npm ERR! syscall rename

npm ERR! ENOTEMPTY: directory not empty, rename '/Users/Me/.Trash/Project/node_modules/firebase/node_modules/jsonwebtoken/node_modules/jws/node_modules/base64url/node_modules/meow/node_modules/indent-string' -> '/Users/Me/.Trash/Project/node_modules/firebase/node_modules/jsonwebtoken/node_modules/jws/node_modules/base64url/node_modules/meow/node_modules/.indent-string.DELETE'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/DoudzzzElCapitan/.Trash/ProjetShindyMe/npm-debug.log** "

I even uninstall and reinstall Ionic.

Please someone help me...

**Comment by DouDzZz** [comment]
After uninstalling node & ionic almost ten times, it works fine again, except for angularfire2
