### ISSUE TITLE
ionic package throws TypeError

### ISSUE THREAD

**Issue by Agies** [driftyco/ionic-cli#1349]
**When I try to run** 
`ionic package build ios --profile app --release`

**Ionic throws** 
Caught exception:
 TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (C:\Users\agies\Documents\GitHub\chatbck-mobile\node_modules\karma\node_modules\core-js\modules\_defined.js:3:28)
    at createHTML (C:\Users\agies\Documents\GitHub\chatbck-mobile\node_modules\karma\node_modules\core-js\modules\_string-html.js:7:19)
    at bold (C:\Users\agies\Documents\GitHub\chatbck-mobile\node_modules\karma\node_modules\core-js\modules\es6.string.bold.js:5:12)
    at cb (C:\Users\agies\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\logger.js:206:7)
    at done (C:\Users\agies\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:167:19)
    at C:\Users\agies\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:40:16
    at emit (C:\Users\agies\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\logger.js:196:7)
    at C:\Users\agies\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:157:13
    at _each (C:\Users\agies\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:57:9)
    at Object.async.each (C:\Users\agies\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\node_modules\async\lib\async.js:156:9)
    at Logger.log (C:\Users\agies\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\logger.js:214:9)
    at target.(anonymous function) [as info] (C:\Users\agies\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\winston\lib\winston\common.js:54:18)
    at Request._callback (C:\Users\agies\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\upload.js:150:11)
    at Request.self.callback (C:\Users\agies\AppData\Roaming\npm\node_modules\ionic\node_modules\request\request.js:373:22)
    at emitTwo (events.js:106:13)

**System Info**

Cordova CLI: 6.3.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.2.4
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
OS:
Node Version: v6.2.0

**Comment by Gazaret** [comment]
This error cause by colors.js module.
colors.js extend String.prototype bold property, but ES6 add own property String.prototype.bold

I think need use last version colors.js in safe mode (in this mode colors.js doesn't extend String.prototype)

`var colors = require('colors/safe');`

**Comment by xuantain** [comment]
I have the same error.
After many times I run `ionic run android` normally then now it occurrs this error.
I did not update `ionic` or `cordova` or anything else, but why?

### Ionic throws 
```
Caught exception:
 TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (/home/xuantain/projects/pv-mobile-app/src/node_modules/core-js/modules/_defined.js:3:28)
    at createHTML (/home/xuantain/projects/pv-mobile-app/src/node_modules/core-js/modules/_string-html.js:7:19)
    at bold (/home/xuantain/projects/pv-mobile-app/src/node_modules/core-js/modules/es6.string.bold.js:5:12)
    at cb (/home/xuantain/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:206:7)
    at done (/home/xuantain/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/async/lib/async.js:167:19)
    at /home/xuantain/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/async/lib/async.js:40:16
    at /home/xuantain/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:193:9
    at Console.log (/home/xuantain/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/winston/lib/winston/transports/console.js:127:3)
    at emit (/home/xuantain/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:186:17)
    at /home/xuantain/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/async/lib/async.js:157:13
    at _each (/home/xuantain/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/home/xuantain/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/async/lib/async.js:156:9)
    at Logger.log (/home/xuantain/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:214:9)
    at target.(anonymous function) [as error] (/home/xuantain/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/node_modules/winston/lib/winston/common.js:54:18)
    at Socket.<anonymous> (/home/xuantain/.nvm/versions/node/v5.0.0/lib/node_modules/ionic/lib/utils/cordova.js:83:11) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```
### This is my System info
```
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
Node Version: v5.0.0
```

**Comment by jthoms1** [comment]
commit #1605 closes this issue.
