### ISSUE TITLE
Error running Ionic start

### ISSUE THREAD

**Issue by SivaDorai** [driftyco/ionic-cli#1351]
Can someone help on this pls. (On Windows PC - Installed Ionic and cordova after node installation, prior to running this)
Node ver 6.4 and npm ver is 3.10.6

$ ionic start ionicapp1
Caught exception:
 Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\SD00472887\AppData\Roaming\npm\node_modules\ionic\node_modules\glob\glob.js:42:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by SivaDorai** [comment]
The issue was due to some local cache. I deleted all the contents of the folder under appdata/roaming/npm. Then re-installed each of them separately, it worked.
