### ISSUE TITLE
 Error: watch /node_modules/@angular/compiler/src/view_compiler/*.js ENOSPC

### ISSUE THREAD

**Issue by cristianKumul** [driftyco/ionic-cli#1405]
When I try to run the app with : 

`ionic serve`

The exception appears:

```
Caught exception:
 Error: watch /home/cristian/Documentos/Proyectos/Ionic2/apiApp/node_modules/@angular/compiler/src/view_compiler/lifecycle_binder.js ENOSPC
    at exports._errnoException (util.js:870:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at createFsWatchInstance (/home/cristian/Documentos/Proyectos/Ionic2/apiApp/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/cristian/Documentos/Proyectos/Ionic2/apiApp/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/cristian/Documentos/Proyectos/Ionic2/apiApp/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/cristian/Documentos/Proyectos/Ionic2/apiApp/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/cristian/Documentos/Proyectos/Ionic2/apiApp/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:82:15) 
```

**Comment by cristianKumul** [comment]
echo fs.inotify.max_user_watches=582222 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
