### ISSUE TITLE
ionic CLI upgrade error: enoent ENOENT: no such file or directory, rename 

### ISSUE THREAD

**Issue by mixersoft** [driftyco/ionic-cli#1414]
I got a message that said my ionic CLI was out of date and did `npm install -g ionic`. 

I got the following error:

```
53840 warn In ionic@2.0.0 replacing bundled version of semver with semver@4.2.0
53841 warn In ionic@2.0.0 replacing bundled version of ionic-app-lib with ionic-app-lib@2.0.0
53842 verbose stack Error: ENOENT: no such file or directory, rename '/Users/m/.nvm/versions/node/v5.12.0/lib/node_modules/.staging/ansi-93ed635c' -> '/Users/m/.nvm/versions/node/v5.12.0/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
53842 verbose stack     at destStatted (/Users/m/.nvm/versions/node/v5.12.0/lib/node_modules/npm/lib/install/action/finalize.js:25:7)
53842 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
53842 verbose stack
53842 verbose stack Error: ENOENT: no such file or directory, rename '/Users/m/.nvm/versions/node/v5.12.0/lib/node_modules/.staging/ansi-93ed635c' -> '/Users/m/.nvm/versions/node/v5.12.0/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
53842 verbose stack     at Error (native)
53843 verbose cwd /dev.snaphappi.com/_ng2/mappi0
53844 error Darwin 15.6.0
53845 error argv "/Users/m/.nvm/versions/node/v5.12.0/bin/node" "/Users/m/.nvm/versions/node/v5.12.0/bin/npm" "install" "-g" "ionic"
53846 error node v5.12.0
53847 error npm  v3.8.6
53848 error path /Users/m/.nvm/versions/node/v5.12.0/lib/node_modules/.staging/ansi-93ed635c
53849 error code ENOENT
53850 error errno -2
53851 error syscall rename
53852 error enoent ENOENT: no such file or directory, rename '/Users/m/.nvm/versions/node/v5.12.0/lib/node_modules/.staging/ansi-93ed635c' -> '/Users/m/.nvm/versions/node/v5.12.0/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
53853 error enoent ENOENT: no such file or directory, rename '/Users/m/.nvm/versions/node/v5.12.0/lib/node_modules/.staging/ansi-93ed635c' -> '/Users/m/.nvm/versions/node/v5.12.0/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
53853 error enoent This is most likely not a problem with npm itself
53853 error enoent and is related to npm not being able to find a file.
53854 verbose exit [ -2, true ]

```

any ideas?

[npm-debug.log.zip](https://github.com/driftyco/ionic-cli/files/495296/npm-debug.log.zip)

**Comment by mixersoft** [comment]
nevermind. I just did an `npm -g remove ionic` and then I was able to install correctly

**Comment by JackZhang1988** [comment]
i have tried `npm -g remove ionic`, and run `npm install --save-dev --save-exact ionic@latest`, but i got same problem, do you know what happen?

**Comment by dwieeb** [comment]
@JackZhang1988 Why are you removing it globally and then installing it locally?
