### ISSUE TITLE
Error with start undefined

### ISSUE THREAD

**Issue by TShelton41** [driftyco/ionic-cli#1424]
updated Ionic and version shows 2.1.0
Then I tried to create a project using `ionic start MyApp blank --v2`
Then it created the folder and started downloading the master.zip
Then it errored out saying this. 

Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

I am using Node version 6.7.0 and npm version 3.10.6

Anyone else having issues.

**Comment by meeximum** [comment]
have the same issue

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.3.1

**Comment by Simpler1** [comment]
Same here...
Node version: 6.6.0
npm version: 3.10.3

**Comment by glashtin** [comment]
Same here, at first it was an error with GIT but I installed the latest version of Windows Git (https://git-for-windows.github.io/).  That fixed the git error and and now getting the same error as everyone else

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.6.0

**Comment by glashtin** [comment]
So I tried installing each package in the package.json one at at time.

npm install ionic-angular
npm install ionicons
ect

I was able to install every package except @ionic/app-scripts

seems to be missing alot of npm-cache packages

npm ERR! not a package C:\Users\User_2\AppData\Roaming\npm-cache\aproba\1.0.4\package.tgz
npm ERR! not a package C:\Users\User_2\AppData\Roaming\npm-cache\console-control-strings\1.1.0\package.tgz
ect

**Comment by edy-ap** [comment]
Same problem here... xD

**Comment by edy-ap** [comment]
ionic 2 RC Released. Yeeahhh!!!!

**Comment by nuote** [comment]
how to solution？

**Comment by nuote** [comment]
Same problem，懵逼

**Comment by edy-ap** [comment]
The problem is that liberated the Ionic RC 2 will soon be solved.

**Comment by edy-ap** [comment]
http://blog.ionic.io/announcing-the-ionic-2-release-candidate/

**Comment by nuote** [comment]
Yeeahhh！thanks

**Comment by edy-ap** [comment]
yes, i am exited

**Comment by nuote** [comment]
I'm using ionic1 now,

**Comment by edy-ap** [comment]
Deberias probar Ionic2, es mejor

**Comment by edy-ap** [comment]
You should try Ionic 2 is better

**Comment by nuote** [comment]
Ionic1 and ionic2 can be generic?

**Comment by edy-ap** [comment]
Cross platform?

**Comment by nuote** [comment]
ios and android

**Comment by edy-ap** [comment]
yes

**Comment by edy-ap** [comment]
is very powerful

**Comment by sbipvkelxj** [comment]
已经解决了
My methods ：
http://user.qzone.qq.com/19643604/blog/1475133805

**Comment by mtycholaz** [comment]
Same issue here

**Comment by huichogil** [comment]
same probem how can i fix this

**Comment by Simpler1** [comment]
**Make sure git is installed.**

You can get more information if you run with the `--verbose` flag:
`ionic start my_proj --v2 --verbose`

**Comment by nuote** [comment]
Make sure git is installed.@Simpler1  is right   I fix it in  this way !

**Comment by nuote** [comment]
install git tools  and  run  npm install   then  ionic serve

**Comment by mtycholaz** [comment]
I have git installed, but I still get the error. When I run verbose, it looks like it has troubles compiling gulp-sass module.

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by mtycholaz** [comment]
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.7.0

And here's a very small snippet of a very large verbose output.

 ```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstddef(725): error C3861: '__builtin_addressof': identifier not found (compiling source file ..\..\src\libsass\src\sass_functions.cpp) [C:\source\repos\test\node_modules\node-sass\build\src\libsass.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstddef(725): error C3861: '__builtin_addressof': identifier not found (compiling source file ..\..\src\libsass\src\sass_util.cpp) [C:\source\repos\test\node_modules\node-sass\build\src\libsass.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstddef(725): error C3861: '__builtin_addressof': identifier not found (compiling source file ..\..\src\libsass\src\sass_values.cpp) [C:\source\repos\test\node_modules\node-sass\build\src\libsass.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstddef(725): error C3861: '__builtin_addressof': identifier not found (compiling source file ..\..\src\libsass\src\source_map.cpp) [C:\source\repos\test\node_modules\node-sass\build\src\libsass.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstddef(725): error C3861: '__builtin_addressof': identifier not found (compiling source file ..\..\src\libsass\src\to_c.cpp) [C:\source\repos\test\node_modules\node-sass\build\src\libsass.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstddef(725): error C3861: '__builtin_addressof': identifier not found (compiling source file ..\..\src\libsass\src\units.cpp) [C:\source\repos\test\node_modules\node-sass\build\src\libsass.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstddef(725): error C3861: '__builtin_addressof': identifier not found (compiling source file ..\..\src\libsass\src\utf8_string.cpp) [C:\source\repos\test\node_modules\node-sass\build\src\libsass.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstddef(725): error C3861: '__builtin_addressof': identifier not found (compiling source file ..\..\src\libsass\src\to_value.cpp) [C:\source\repos\test\node_modules\node-sass\build\src\libsass.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstddef(725): error C3861: '__builtin_addressof': identifier not found (compiling source file ..\..\src\libsass\src\util.cpp) [C:\source\repos\test\node_modules\node-sass\build\src\libsass.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstddef(725): error C3861: '__builtin_addressof': identifier not found (compiling source file ..\..\src\libsass\src\values.cpp) [C:\source\repos\test\node_modules\node-sass\build\src\libsass.vcxproj]

    8 Warning(s)
    39 Error(s)

Time Elapsed 00:00:16.06

gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\source\repos\test\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14936
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\source\\repos\\test\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\source\repos\test\node_modules\node-sass
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

Build failed

ionic-app-base@ C:\source\repos\test
+-- @ionic/storage@1.1.0
| +-- @angular/core@2.0.1
| +-- @types/localforage@0.0.30
| +-- localforage@1.4.2
| | `-- lie@3.0.2
| |   +-- es3ify@0.1.4
| |   | +-- esprima-fb@3001.1.0-dev-harmony-fb
| |   | +-- jstransform@3.0.0
| |   | | +-- base62@0.1.1
| |   | | `-- source-map@0.1.31
| |   | `-- through@2.3.8
| |   +-- immediate@3.0.6
| |   +-- inline-process-browser@1.0.0
| |   | +-- falafel@1.2.0
| |   | | +-- acorn@1.2.2
| |   | | +-- foreach@2.0.5
| |   | | +-- isarray@0.0.1
| |   | | `-- object-keys@1.0.11
| |   | `-- through2@0.6.5
| |   |   +-- readable-stream@1.0.34
| |   |   | +-- core-util-is@1.0.2
| |   |   | +-- inherits@2.0.3
| |   |   | `-- string_decoder@0.10.31
| |   |   `-- xtend@4.0.1
| |   `-- unreachable-branch-transform@0.3.0
| |     +-- esmangle-evaluator@1.0.1
| |     `-- recast@0.10.43
| |       +-- ast-types@0.8.15
| |       +-- esprima-fb@15001.1001.0-dev-harmony-fb
| |       +-- private@0.1.6
| |       `-- source-map@0.5.6
| +-- localforage-cordovasqlitedriver@1.4.6  (git://github.com/driftyco/localforage-cordovasqlitedriver.git#9803562a61c2172a69f3475f97e98922c0b49ac0)
| `-- rxjs@5.0.0-beta.12
|   `-- symbol-observable@1.0.2
+-- d@0.1.1  extraneous
+-- ionic-angular@2.0.0-rc.0
| +-- @angular/common@2.0.1
| +-- @angular/compiler@2.0.1
| +-- @angular/compiler-cli@0.6.3
| | +-- @angular/tsc-wrapped@0.3.0
| | | `-- tsickle@0.1.7
| | |   +-- mkdirp@0.5.1
| | |   | `-- minimist@0.0.8
| | |   +-- source-map@0.4.4
| | |   | `-- amdefine@1.0.0
| | |   `-- source-map-support@0.3.3
| | |     `-- source-map@0.1.32
| | +-- minimist@1.2.0
| | +-- parse5@1.3.2
| | `-- reflect-metadata@0.1.8
| +-- @angular/forms@2.0.1
| +-- @angular/http@2.0.1
| +-- @angular/platform-browser@2.0.1
| +-- @angular/platform-browser-dynamic@2.0.1
| +-- @angular/platform-server@2.0.1
| `-- zone.js@0.6.25
+-- ionic-native@2.0.3
+-- ionicons@3.0.0
`-- typescript@2.0.3


npm
WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Windows_NT 10.0.14936
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.9.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.9.3 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
```

**Comment by mtycholaz** [comment]
Managed to solve this problem. Credit goes to this [SO question](http://stackoverflow.com/questions/38114116/builtin-address-of-identifier-not-found-when-running-opencv-in-visual-studi/38230171)

Short version: Repair Visual Studio 2015 from Programs and Features

**Comment by TShelton41** [comment]
I solved my issue by going into my global node_modules and deleting all instances of ionic and cordova. Then I cleaned the npm cache and reinstalled both of these and it worked for me. 

Hope that helps someone.

**Comment by TShelton41** [comment]
Here is another fix. 
Run this: `npm uninstall -g ionicnpm cache clean`
Then reinstall: `npm install -g ionic cordova`

Then I found out you have to update git. So I'm on a Mac and I updated to 2.10

That all worked for me on my laptop. The answer above was my desktop.

**Comment by rajassbj** [comment]
open .npmrc
registry=http://registry.npmjs.org/
http-proxy=http://xyz:80/
https-proxy=https://xyz:80/

set https to https-proxy

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
