### ISSUE TITLE
ionic serve fails on RC starter app

### ISSUE THREAD

**Issue by thomaswb** [driftyco/ionic-cli#1447]
I updated the CLI as per instructions, updated npm to the latest available 2.15.9 (no, not 3.x as it says in the RC instructions), installed a starter app:

`ionic start --v2 Ionic2RC tabs`

But it doesn't serve, can't find many modules. See below. Same result for blank starter.

Your system information:

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v4.6.0
Xcode version: Xcode 8.0 Build version 8A218a 

```
$ ionic serve

Running 'serve:before' npm script before serve
> ionic2rc@ watch /Users/thomas/Development/Ionic2RC
> ionic-app-scripts watch
[11:18:22]  ionic-app-scripts 0.0.23
[11:18:22]  watch started ...
[11:18:22]  build dev started ...
[11:18:22]  clean started ...
[11:18:22]  clean finished in 8 ms
[11:18:22]  copy started ...
[11:18:22]  typescript compiler started ...
[11:18:22]  lint started ...
[11:18:22]  

[11:18:22]  copy finished in 47 ms
[11:18:25]  src/app/app.component.ts(1,27): error TS2307: Cannot find module '@angular/core'.
[11:18:25]  src/app/app.module.ts(1,26): error TS2307: Cannot find module '@angular/core'.
[11:18:25]  src/app/main.dev.ts(1,40): error TS2307: Cannot find module '@angular/platform-browser-dynamic'.
[11:18:25]  src/pages/about/about.ts(1,27): error TS2307: Cannot find module '@angular/core'.
[11:18:25]  src/pages/contact/contact.ts(1,27): error TS2307: Cannot find module '@angular/core'.
[11:18:25]  src/pages/home/home.ts(1,27): error TS2307: Cannot find module '@angular/core'.
[11:18:25]  src/pages/tabs/tabs.ts(1,27): error TS2307: Cannot find module '@angular/core'.
[11:18:25]  typescript compiler ready in 2.85 s
[11:18:25]  bundle dev started ...
[11:18:25]  Error: Could not resolve '@angular/platform-browser-dynamic' from /Users/thomas/Development/Ionic2RC/.tmp/app/main.dev.js
    at Error (native)
    at /Users/thomas/Development/Ionic2RC/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:78:21
    at /Users/thomas/Development/Ionic2RC/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/browser-resolve/index.js:265:24
    at /Users/thomas/Development/Ionic2RC/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:46:14
    at process (/Users/thomas/Development/Ionic2RC/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/thomas/Development/Ionic2RC/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/thomas/Development/Ionic2RC/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/thomas/Development/Ionic2RC/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/thomas/Development/Ionic2RC/node_modules/@ionic/app-scripts/node_modules/rollup-plugin-node-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

[11:18:25]  sass started ...
[11:18:25]  sass failed:  Cannot generate Sass files without first bundling JavaScript files in order to know all used modules. Please build JS files first.

[11:18:25]  build dev failed:  Build failed

[11:18:25]  

[11:18:25]  watch ready in 3.08 s
Running live reload server: http://localhost:35729
Watching: www/**/*, !www/lib/**/*
√ Running dev server:  http://localhost:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

ionic $ 
```

**Comment by amity203** [comment]
Go to https://git-for-windows.github.io/ and install git
than open git cmd
run below command: 
git config --global url."https://".insteadOf git://

This resolved issues for me

**Comment by thomaswb** [comment]
That didn't make any difference for me on a Mac, nor the reverse. It always uses https:// to fetch anyway.

```
 ionic start --v2 Ionic2RC tabs
Creating Ionic app in folder /Users/thomas/Development/Ionic2RC based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...

Adding initial native plugins
[=============================]  100%  0.0s

Adding in iOS application by default

Saving your Ionic app state of platforms and plugins
Saved platform
Saved plugins
Saved package.json
```

**Comment by thomaswb** [comment]
Doh! I revisited the release notes. It said to install the latest NodeJS. I had installed NodeJS v4.6.0 LTS "Recommended for most users". But I see there is v6.7.0 Current. So I installed that, uninstalled ionic, installed ionic again, installed a demo project... now it works.
Sorry for the noise.
