### ISSUE TITLE
npm update ionic fails

### ISSUE THREAD

**Issue by matheo** [driftyco/ionic-cli#1462]
Any ideas why I get this "cordova error" while I'm trying to update my Ionic CLI?
```
# npm -g update ionic
npm WARN deprecated lodash@2.1.0: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
/usr/local/lib
└── (empty)

npm WARN In ionic@2.1.0-beta.3 replacing bundled version of semver with semver@4.2.0
npm WARN In ionic@2.1.0-beta.3 replacing bundled version of ionic-app-lib with ionic-app-lib@2.1.0-beta.1
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "update" "ionic"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8
npm ERR! path /usr/local/lib/node_modules/.staging/ansi-392b32ed
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     ./npm-debug.log
npm ERR! code 1
```

.
The relevant npm-debug log is:
```
...
54024 silly lifecycle xmlbuilder@4.0.0~preinstall: no script for preinstall, continuing
54025 silly lifecycle xmldom@0.1.22~preinstall: no script for preinstall, continuing
54026 silly lifecycle plist@1.2.0~preinstall: no script for preinstall, continuing
54027 silly lifecycle cordova-common@1.1.1~preinstall: no script for preinstall, continuing
54028 silly doReverseSerial remove 0
54029 silly doSerial move 0
54030 silly doSerial finalize 275
54031 silly finalize /usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi
54032 verbose unlock done using /root/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
54033 silly rollbackFailedOptional Starting
54034 silly rollbackFailedOptional Finishing
54035 silly runTopLevelLifecycles Finishing
54036 silly install printInstalled
54037 warn In ionic@2.1.0-beta.3 replacing bundled version of semver with semver@4.2.0
54038 verbose If you need help, you may report this error at:
54038 verbose     <https://github.com/npm/npm/issues>
54039 warn In ionic@2.1.0-beta.3 replacing bundled version of ionic-app-lib with ionic-app-lib@2.1.0-beta.1
54040 verbose If you need help, you may report this error at:
54040 verbose     <https://github.com/npm/npm/issues>
54041 verbose stack Error: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
54041 verbose stack     at destStatted (/usr/local/lib/node_modules/npm/lib/install/action/finalize.js:25:7)
54041 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
54041 verbose stack
54041 verbose stack Error: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
54041 verbose stack     at Error (native)
54042 verbose cwd /media/zikula/git/gitlab/ionic
54043 error Linux 4.4.0-38-generic
54044 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "update" "ionic"
54045 error node v6.6.0
54046 error npm  v3.10.8
54047 error path /usr/local/lib/node_modules/.staging/ansi-392b32ed
54048 error code ENOENT
54049 error errno -2
54050 error syscall rename
54051 error enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
54052 error enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
54052 error enoent This is most likely not a problem with npm itself
54052 error enoent and is related to npm not being able to find a file.
54053 verbose exit [ -2, true ]
```

.
Thanks in advance!

**Comment by lesliejobse** [comment]
I guess you should uninstall and install again

**Comment by jdat82** [comment]
When updating global npm dependencies, I think it is better to use the install keyword:

```bash
npm i -g ionic
```

You can use tools like `npm-check-updates` or `updtr` to help you monitor your dependencies.

**Comment by jthoms1** [comment]
Could you take a look at the upgrade guide for Ionic RC0.  This could provide some steps that you might have missed during the update process. https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade-to-rc0

**Comment by matheo** [comment]
@jdat82 I did that with the same result :(

@jthoms1 Indeed, I had the `beta` before and I needed to execute:
```
npm uninstall -g ionic
```
Thanks!
