### ISSUE TITLE
Can't start new project

### ISSUE THREAD

**Issue by peterbarone315** [driftyco/ionic-cli#1497]
This is the error I'm getting.  Any advice ?

Caught exception:
 Error: Cannot find module 'lodash/assign'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xmlbuilder/lib/index.js:5:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xmlbuilder/lib/index.js:14:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**Comment by anjelo1989** [comment]
instal Git
& 
update npm type on cmd ====>>> npm install npm@latest -g

**Comment by peterbarone315** [comment]
New error ?

Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/.staging/@ionic'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/.staging/@ionic']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rmdir',
npm ERR!   path: '/usr/local/lib/node_modules/.staging/@ionic' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

Can you guide me

I’m sorry i’m a bit of a noob. 

Thanks for your help, this all started when I updated to Sierra on my Mac

**Comment by peterbarone315** [comment]
Solved this issue by updating node.js to 4.6 all seems to be good.
