### ISSUE TITLE
 ngc: can't resolve module 

### ISSUE THREAD

**Issue by AndreG-SA** [driftyco/ionic-cli#1502]
Hi There

Hope you guys can help
[npm-debug.txt](https://github.com/driftyco/ionic-cli/files/519060/npm-debug.txt)

[10:35:58]  ngc: can't resolve module F:/ionic/Mobi/node_modules/@angular/platform-browser/src/facade/collection.d.ts from F:/ionic/Mobi/node_modules/@angular/platform-browser/src/facade/collection.d.ts

[10:35:58]  ngc: Error: can't find symbol Map exported from module F:/ionic/Mobi/node_modules/@angular/platform-browser/src/facade/collection.d.ts
    at ReflectorHost.findDeclaration (F:\ionic\Mobi\node_modules\@angular\compiler-cli\src\reflector_host.js:173:23)
    at _loop_1 (F:\ionic\Mobi\node_modules\@angular\compiler-cli\src\codegen.js:52:51)
    at CodeGenerator.readFileMetadata (F:\ionic\Mobi\node_modules\@angular\compiler-cli\src\codegen.js:66:13)
    at F:\ionic\Mobi\node_modules\@angular\compiler-cli\src\codegen.js:100:74
    at Array.map (native)
    at CodeGenerator.codegen (F:\ionic\Mobi\node_modules\@angular\compiler-cli\src\codegen.js:100:35)
    at codegen (F:\ionic\Mobi\node_modules\@angular\compiler-cli\src\main.js:7:81)
    at Object.main (F:\ionic\Mobi\node_modules\@angular\tsc-wrapped\src\main.js:30:16)
    at Object.<anonymous> (F:\ionic\Mobi\node_modules\@angular\compiler-cli\src\main.js:14:9)
    at Module._compile (module.js:397:26)

**Comment by AndreG-SA** [comment]
I uninstalled everything and installed again , now it is working 100%
