### ISSUE TITLE
ionic run ios problem

### ISSUE THREAD

**Issue by phil-homecu** [driftyco/ionic-cli#1548]
this may be related to #1197, not sure.  

I have not been able to build for ios yet.  I started with the `ionic start --v2` command, and have changed the project significantly since.  

I started with the error of no `.xcodeproj` file found.  along the way I have removed and added the ios platform several times.  

```
$ ionic platform remove ios
$ ionic run  ios

Running 'run:before' npm script before run
> ionic-hello-world@ build /Users/philm/Documents/ionic/t4nt
> ionic-app-scripts build
[13:47:35]  ionic-app-scripts 0.0.30
[13:47:35]  build prod started ...
[13:47:35]  clean started ...
[13:47:35]  clean finished in 22 ms
[13:47:35]  copy started ...
[13:47:35]  ngc started ...
[13:47:35]  lint started ...
[13:47:35]  copy finished in 186 ms
[13:47:36]  lint finished in 962 ms
[13:47:48]  ngc finished in 12.51 s
[13:47:48]  bundle prod started ...
[13:47:54]  bundle prod finished in 6.53 s
[13:47:54]  sass started ...
[13:47:55]  sass finished in 989 ms
[13:47:55]  minify started ...
[13:47:55]  cleancss started ...
[13:47:55]  uglifyjs started ...
[13:48:03]  uglifyjs finished in 8.27 s
[13:48:03]  cleancss finished in 8.27 s
[13:48:03]  minify finished in 8.27 s
[13:48:03]  build prod finished in 28.33 s
• You're trying to build for ios but don't have the platform installed yet.
∆ Installing ios for you.
 Error: Command failed: cordova platform add ios
Error: Entry not found in project file for sub-project: CordovaLib/CordovaLib.xcodeproj

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

```
Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.6.0
Xcode version: Xcode 8.0 Build version 8A218a
```

**Comment by phil-homecu** [comment]
solved.  <name/>  tag in config.xml needs to be setup.
