### ISSUE TITLE
NPM doesn't start

### ISSUE THREAD

**Issue by vamshikrishnametta** [driftyco/ionic-cli#1554]
Caught exception:
 Error: Cannot find module 'archiver'
    at Function.Module._resolveFilename (module.
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\212576692\Ap
onic\node_modules\ionic-app-lib\lib\utils.js:4:1
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by vamshikrishnametta** [comment]
Hi

I had reinstalled nodejs then installed ionic and problem got fixed thanks
for response
