### ISSUE TITLE
Error with ionic sass watch / install

### ISSUE THREAD

**Issue by sirdowan** [driftyco/ionic-cli#1567]
#### Short description of the problem:
it started yesterday, after pulling a project from a git, none of my previous projects could watch for sass changes. Had to open new terminal and add gulp watch separately, but even this way returned error after 4-5 saves, and now for every single one. 

**Steps to reproduce:**
ionis setup sass or gulp sass

```
insert any relevant code between the above and below backticks
Ionic project ready to use Sass!
 * Customize the app using scss/ionic.app.scss
 * Run ionic serve to start a local dev server and watch/compile Sass to CSS

[14:47:46] Using gulpfile C:\git\MyHolidayApp\gulpfile.js
[14:47:46] Starting 'sass'...
C:\git\MyHolidayApp\node_modules\gulp-util\lib\PluginError.js:53
  if (!this.message) throw new Error('Missing error message');
                     ^

Error: Missing error message
    at new PluginError (C:\git\MyHolidayApp\node_modules\gulp-util\lib\PluginError.js:53:28)
    at DestroyableTransform.logError (C:\git\MyHolidayApp\node_modules\gulp-sass\index.js:179:17)
    at emitOne (events.js:82:20)
    at DestroyableTransform.emit (events.js:169:7)
    at onwriteError (C:\git\MyHolidayApp\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:322:10)
    at onwrite (C:\git\MyHolidayApp\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:339:11)
    at WritableState.onwrite (C:\git\MyHolidayApp\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:123:5)
    at afterTransform (C:\git\MyHolidayApp\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:81:3)
    at TransformState.afterTransform (C:\git\MyHolidayApp\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:58:12)
    at errorM (C:\git\MyHolidayApp\node_modules\gulp-sass\index.js:134:14)

Caught exception:
 TypeError: Cannot read property 'bold' of undefined
    at ChildProcess.<anonymous> (C:\Users\Hem\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\setup.js:144:49)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

**Post the output of `ionic info` below please**
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
OS:
Node Version: v4.4.1

**Comment by sirdowan** [comment]
So I've downgraded to Ionic 1.7.14 and now sass watch works
