### ISSUE TITLE
Error running npm install -g ionic

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#1568]
_From @andrewlaskey on October 20, 2016 4:17_

I am unable to install ionic. Running `npm install -g ionic` generates this error:

```
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic@latest"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8

npm ERR! Invalid name: "@ionic/app-generators"
```

Also I'm on macOS Seirra 10.12.

I didn't have the latest version of node or npm so I updated both of those, but it didn't resolve the issue. Any ideas? Something I'm missing?

Thanks!

_Copied from original issue: driftyco/ionic#8813_

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Unfortunately I cannot reproduce this issue. Can you be sure that you are on a solid network connection? Also, since this issue is a cli related issue and not the framework I am going to move this issue to the cli repo.

**Comment by andrewlaskey** [comment]
Thanks. Tried it on two different networks so I'm guessing its something with my machine. This is from npm-debug.log if it is helpful. 

```
14500 silly fetchNamedPackageData @ionic/app-generators
14501 silly mapToRegistry name @ionic/app-generators
14502 silly mapToRegistry scope (from package name) @ionic
14503 verbose mapToRegistry no registry URL found in name for scope @ionic
14504 silly mapToRegistry using default registry
14505 silly mapToRegistry registry https://registry.npmjs.org/
14506 silly mapToRegistry data Result {
14506 silly mapToRegistry   raw: '@ionic/app-generators',
14506 silly mapToRegistry   scope: '@ionic',
14506 silly mapToRegistry   escapedName: '@ionic%2fapp-generators',
14506 silly mapToRegistry   name: '@ionic/app-generators',
14506 silly mapToRegistry   rawSpec: '',
14506 silly mapToRegistry   spec: 'latest',
14506 silly mapToRegistry   type: 'tag' }
14507 silly mapToRegistry uri https://registry.npmjs.org/@ionic%2fapp-generators
14508 verbose request uri https://registry.npmjs.org/@ionic%2fapp-generators
14509 verbose request no auth needed
14510 info attempt registry request try #1 at 9:03:38 AM
14511 verbose etag "68Z4R7K164BI4CKA2BYM2VHYG"
14512 http request GET https://registry.npmjs.org/@ionic%2fapp-generators
14513 http 304 https://registry.npmjs.org/@ionic%2fapp-generators
14514 verbose headers { date: 'Thu, 20 Oct 2016 16:03:39 GMT',
14514 verbose headers   via: '1.1 varnish',
14514 verbose headers   'cache-control': 'max-age=0',
14514 verbose headers   etag: '"68Z4R7K164BI4CKA2BYM2VHYG"',
14514 verbose headers   age: '0',
14514 verbose headers   connection: 'keep-alive',
14514 verbose headers   'x-served-by': 'cache-sjc3125-SJC',
14514 verbose headers   'x-cache': 'MISS',
14514 verbose headers   'x-cache-hits': '0',
14514 verbose headers   'x-timer': 'S1476979419.337040,VS0,VE684',
14514 verbose headers   vary: 'Accept-Encoding' }
14515 silly get cb [ 304,
14515 silly get   { date: 'Thu, 20 Oct 2016 16:03:39 GMT',
14515 silly get     via: '1.1 varnish',
14515 silly get     'cache-control': 'max-age=0',
14515 silly get     etag: '"68Z4R7K164BI4CKA2BYM2VHYG"',
14515 silly get     age: '0',
14515 silly get     connection: 'keep-alive',
14515 silly get     'x-served-by': 'cache-sjc3125-SJC',
14515 silly get     'x-cache': 'MISS',
14515 silly get     'x-cache-hits': '0',
14515 silly get     'x-timer': 'S1476979419.337040,VS0,VE684',
14515 silly get     vary: 'Accept-Encoding' } ]
14516 verbose etag https://registry.npmjs.org/@ionic%2fapp-generators from cache
14517 verbose get saving @ionic/app-generators to /Users/andrewlaskey/.npm/registry.npmjs.org/_40ionic_252fapp-generators/.cache.json
14518 verbose correctMkdir /Users/andrewlaskey/.npm correctMkdir not in flight; initializing
14519 silly resolveWithNewModule @ionic/app-generators@0.0.3 checking installable status
14520 silly cache add args [ '@ionic/app-generators@0.0.3', null ]
14521 verbose cache add spec @ionic/app-generators@0.0.3
14522 silly cache add parsed spec Result {
14522 silly cache add   raw: '@ionic/app-generators@0.0.3',
14522 silly cache add   scope: '@ionic',
14522 silly cache add   escapedName: '@ionic%2fapp-generators',
14522 silly cache add   name: '@ionic/app-generators',
14522 silly cache add   rawSpec: '0.0.3',
14522 silly cache add   spec: '0.0.3',
14522 silly cache add   type: 'version' }
14523 silly addNamed @ionic/app-generators@0.0.3
14524 verbose addNamed "0.0.3" is a plain semver version for @ionic/app-generators
14525 silly mapToRegistry name @ionic/app-generators
14526 silly mapToRegistry scope (from package name) @ionic
14527 verbose mapToRegistry no registry URL found in name for scope @ionic
14528 silly mapToRegistry using default registry
14529 silly mapToRegistry registry https://registry.npmjs.org/
14530 silly mapToRegistry data Result {
14530 silly mapToRegistry   raw: '@ionic/app-generators',
14530 silly mapToRegistry   scope: '@ionic',
14530 silly mapToRegistry   escapedName: '@ionic%2fapp-generators',
14530 silly mapToRegistry   name: '@ionic/app-generators',
14530 silly mapToRegistry   rawSpec: '',
14530 silly mapToRegistry   spec: 'latest',
14530 silly mapToRegistry   type: 'tag' }
14531 silly mapToRegistry uri https://registry.npmjs.org/@ionic%2fapp-generators
14532 verbose addNameVersion registry:https://registry.npmjs.org/@ionic%2fapp-generators not in flight; fetching
14533 verbose get https://registry.npmjs.org/@ionic%2fapp-generators not expired, no request
14534 silly rollbackFailedOptional Starting
14535 silly rollbackFailedOptional Finishing
14536 silly runTopLevelLifecycles Finishing
14537 silly install printInstalled
14538 verbose stack Error: Invalid name: "@ionic/app-generators"
14538 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:297:15)
14538 verbose stack     at Object.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:201:5)
14538 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:38
14538 verbose stack     at Array.forEach (native)
14538 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:28:15)
14538 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:349:5)
14538 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
14538 verbose stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:295:20)
14538 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
14538 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
```

Maybe uninstall and reinstall node/npm?

**Comment by andrewlaskey** [comment]
Was able to fix the issue by installing node with nvm and then installing ionic.
