### ISSUE TITLE
Building ios from ionic package

### ISSUE THREAD

**Issue by bgosalci** [driftyco/ionic-cli#1575]
For over a week I'm getting the following error message when building ionic package build ios.

Caught exception:
 SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request._callback (C:\Users\burgos\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\package.js:116:27)
    at Request.self.callback (C:\Users\burgos\AppData\Roaming\npm\node_modules\ionic\node_modules\request\request.js:373:22)
    at emitTwo (events.js:88:13)
    at Request.emit (events.js:173:7)
    at Request.<anonymous> (C:\Users\burgos\AppData\Roaming\npm\node_modules\ionic\node_modules\request\request.js:1318:14)
    at emitOne (events.js:83:20)
    at Request.emit (events.js:170:7)
    at IncomingMessage.<anonymous> (C:\Users\burgos\AppData\Roaming\npm\node_modules\ionic\node_modules\request\request.js:1266:12)
    at emitNone (events.js:73:20)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by bgosalci** [comment]
I was using ionic keyboard plugging 1.7.1. once I've changed it to 2.2.1
the issue resolved.

**Comment by jthoms1** [comment]
Awesome, Thanks!

**Comment by Kaelink** [comment]
Hi,

Thanks for the info! Does one know if there is any issues with some pluggins? I'm encountering exactly the same error, trying to build for iOS, but my keyboard plugin is already 2.2.1

Here are the ouput of ionic info:

> Cordova CLI: 6.3.1 
> Ionic Framework Version: 2.0.0-rc.5
> Ionic CLI Version: 2.2.1
> Ionic App Lib Version: 2.2.0
> Ionic App Scripts Version: 1.0.0
> ios-deploy version: Not installed
> ios-sim version: Not installed
> OS: Linux 4.4
> Node Version: v4.2.6
> Xcode version: Not installed

I also tried on Windows 10, but I get the same error message.

And here are the plugins I am using:

> cordova-plugin-compat 1.1.0 "Compat"
> cordova-plugin-console 1.0.5 "Console"
> cordova-plugin-device 1.1.4 "Device"
> cordova-plugin-facebook4 1.7.4 "Facebook Connect"
> cordova-plugin-geolocation 2.4.1 "Geolocation"
> cordova-plugin-inappbrowser 1.6.1 "InAppBrowser"
> cordova-plugin-splashscreen 4.0.1 "Splashscreen"
> cordova-plugin-statusbar 2.2.1 "StatusBar"
> cordova-plugin-whitelist 1.3.1 "Whitelist"
> cordova-sqlite-storage 2.0.1 "Cordova sqlite storage plugin"
> ionic-plugin-keyboard 2.2.1 "Keyboard"
> phonegap-plugin-barcodescanner 6.0.5 "BarcodeScanner"

Thank you very much for your kind help

**Comment by devsaurin** [comment]
Facing same issue:

Caught exception:
 SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request._callback (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/package.js:117:27)
    at Request.self.callback (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/request/request.js:373:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/request/request.js:1318:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/request/request.js:1266:12)
    at emitNone (events.js:72:20)


This is what: ionic package info {build id} says.

The error is not helpful at all.

**Comment by devsaurin** [comment]
@Kaelink did you manage to resolve it?

**Comment by Kaelink** [comment]
@devsaurin Yes, but it was an issue on Ionic's side, so I have done nothing except wait for their patch. https://forum.ionicframework.com/t/ionic-package-build-ios-fails-with-error-in-ionic-keyboard/81397/24

**Comment by devsaurin** [comment]
@Kaelink I recently logged in to my app account on ionic to check what log says:

I found this: 

Check dependencies
Provisioning profile "HKindia" doesn't include the aps-environment entitlement.
Code signing is required for product type 'Application' in SDK 'iOS 10.2'

** ARCHIVE FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/package/workspace/apps-591816b9-8/cordova/platforms/ios/cordova/build-release.xcconfig,-workspace,HKIndia.xcworkspace,-scheme,HKIndia,-configuration,Release,-destination,generic/platform=iOS,-archivePath,HKIndia.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/package/workspace/apps-591816b9-8/cordova/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/package/workspace/apps-591816b9-8/cordova/platforms/ios/build/sharedpch

Do you know what is the issue?
