### ISSUE TITLE
ionic start myapp  gives 'getaddrinfo EAI_AGAIN github.com'

### ISSUE THREAD

**Issue by abverma** [driftyco/ionic-cli#1576]
#### Short description of the problem:
I just install ionic and cordova from command line. Trying to create new app I get this error.

#### What behavior are you expecting?
Ionic app directory should be created

**Steps to reproduce:**
1. ionic start myapp tabs

**Post the output of `ionic info` below please**
abhishek@abhishek-Lenovo-G50-30:~/Code/ionic$ ionic start myApp tabs
Creating Ionic app in folder /home/abhishek/Code/ionic/myApp based on tabs project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Error with start Error: getaddrinfo EAI_AGAIN github.com:443
    at Object.exports._errnoException (util.js:1026:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
Error Initializing app: Error: getaddrinfo EAI_AGAIN github.com:443
 Error: getaddrinfo EAI_AGAIN github.com:443
    at Object.exports._errnoException (util.js:1026:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
Caught exception:
 Error: getaddrinfo EAI_AGAIN github.com:443
    at Object.exports._errnoException (util.js:1026:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by abverma** [comment]
It just worked some time later.

**Comment by teekaytech** [comment]
I'm experiencing the same error on my linux mint, can anybody please help?
