### ISSUE TITLE
Create the APP Error

### ISSUE THREAD

**Issue by wjbd** [driftyco/ionic-cli#1583]
**Steps to reproduce:**
1.ionic start myAPP
`Creating Ionic app in folder /Users/*****/Desktop/PhoneGap/myAPP based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
Error with start Error: connect ETIMEDOUT 192.30.253.113:443
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
Error Initializing app: Error: connect ETIMEDOUT 192.30.253.113:443
 Error: connect ETIMEDOUT 192.30.253.113:443
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
Caught exception:
 Error: connect ETIMEDOUT 192.30.253.113:443
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues`

How can I solve this problem？

**Comment by jthoms1** [comment]
Could you please try to access this file directly from within your browser?  Just want to test that you can download files from github. https://github.com/driftyco/ionic2-app-base/archive/master.zip

Thanks!

**Comment by rodrigo-m-martins** [comment]
Hi Josh.
I have access !
I finish sucessfully the download of two files required on project installation.

**Comment by wjbd** [comment]
May be I am a Chinese，so i use my proxy can download

**Comment by wjbd** [comment]
like PROXY=http://127.0.0.1:9743 ionic start myAPP
