### ISSUE TITLE
ionic serve:  Error: Cannot find module 'winston'

### ISSUE THREAD

**Issue by karlpatrickespiritu** [driftyco/ionic-cli#1591]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

#### Short description of the problem:
````cli
$ ionic serve
Caught exception:
 Error: Cannot find module 'winston'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\cmadmin\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\logging.js:2:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
````

#### What behavior are you expecting?

**Steps to reproduce:**
1. removed my node_modules
2. ran npm install
3. ionic serve

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by karlpatrickespiritu** [comment]
oops. probably was a cache problem. npm cache clear fixed it.
