### ISSUE TITLE
Error while creating first ionic2 app

### ISSUE THREAD

**Issue by mrtinkz** [driftyco/ionic-cli#1632]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

#### Short description of the problem:
module error while creating first ionic2 application

#### What behavior are you expecting?

**Steps to reproduce:**
1. npm install -g ionic cordova
2.ionic start cutePuppyPics --v2
3.

```
insert any relevant code between the above and below backticks
```
Caught exception:
 Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\vpalakurthi\AppData\Roaming\npm\node_modules\ionic\node_modules\glob\glob.js:42:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Post the output of `ionic info` below please**
Caught exception:
 Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\vpalakurthi\AppData\Roaming\npm\node_modules\ionic\node_modules\glob\glob.js:42:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by mrtinkz** [comment]
Never mind, I reinstalled it and it worked.
