### ISSUE TITLE
Error when running ionic upload command

### ISSUE THREAD

**Issue by hafizbilal112** [driftyco/ionic-cli#1637]
Uploading app....
An error occurred uploading the build: TypeError: Cannot read property 'map' of undefined

TypeError: Cannot read property 'map' of undefined
    at Object.getDirectUploadKey (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:262:18)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:40:21
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Cannot read property 'map' of undefined (CLI v2.1.4)

**My system information:**
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X Sierra
Node Version: v6.9.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by kamok** [comment]
Did you figure this out? This was working for me before.

**Comment by hafizbilal112** [comment]
Yeh, I just check it again and it's working fine.
