### ISSUE TITLE
Run IONIC 1 - Project with IONIC-CLI 2

### ISSUE THREAD

**Issue by f0ntana** [driftyco/ionic-cli#1649]
How can i run IONIC 1 - Project with IONIC-CLI 2..., when i do:

`ionic serve`

i get this error:
```
WARN: ionic.project has been renamed to ionic.config.json, please rename it.

TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Object.runr (/usr/local/lib/node_modules/ionic/lib/cli.js:191:19)
    at /usr/local/lib/node_modules/ionic/lib/cli.js:54:9
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)


Cannot read property 'hasOwnProperty' of undefined (CLI v2.1.7)

Your system information:

Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62 
````

i do but don't resolve
`npm install`

Thanks

**Comment by xujingbao** [comment]
2.1.7 unstable. reinstalling ionic 2.0.0:

>  npm uninstall -g ionic
>  npm install -g ionic@2.0.0

----

➜  ionic-quickstarter git:(master) ✗ ionic info

Your system information:

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.11
OS: Mac OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8T29o

**Comment by f0ntana** [comment]
i do this and work, but with i works with ionic 2 can i use thins like generate?

using the 2.0 version ?

Thanks

**Comment by xujingbao** [comment]
No Problems！😄

**Comment by f0ntana** [comment]
Thanks, work's fine.
