### ISSUE TITLE
Cannot use `ionic` command

### ISSUE THREAD

**Issue by tae8838** [driftyco/ionic-cli#1659]
When I type `ionic` into the command line, I get this error:

```
Caught exception:
 Error: Cannot find module 'extend'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/request/index.js:17:29)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

How could I fix this? I'm using Mac 10.11.5 and I installed ionic using `sudo npm install -g ionic`

**Comment by tae8838** [comment]
Solved this by installing extend using npm. My NODE_PATH was empty as well, not sure if that caused this to happen.
