### ISSUE TITLE
ionic upload cli error

### ISSUE THREAD

**Issue by reverdin** [driftyco/ionic-cli#1670]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

#### Short description of the problem:
When I run ionic upload in the terminal, I get an error message.

#### What behavior are you expecting?
It should upload to ionic

**Steps to reproduce:**
1. Got to the app folder
2. Run the ionic upload
3. Displaying [Uploading app....
4. Error message:
```
Caught exception:
 Error: EINVAL: invalid argument, close
    at Error (native) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Caught exception:
 Error: process exited before Archiver could finish emitting data
    at .<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/archiver/lib/modules/core/index.js:42:13)
    at process.g (events.js:291:16)
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7) 
```
5. A www.zip file is in the project folder

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.39
ios-deploy version: 1.9.0 
ios-sim version: 5.0.9 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
With another app, it works.

**Comment by reverdin** [comment]
My project folder was on a SMB share. Moved it to a local folder and it worked again.
