### ISSUE TITLE
ionic resources giving Error: ENOENT: no such file or directory, uv_cwd

### ISSUE THREAD

**Issue by sawan1990** [driftyco/ionic-cli#1707]
For the first time on machine I run 
 ionic resources

got following error

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.posix.resolve (path.js:424:50)
    at Function.Module._resolveLookupPaths (module.js:249:17)
    at Function.Module._resolveFilename (module.js:327:31)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/sawan/.nvm/v4.2.0/lib/node_modules/ionic/bin/ionic:11:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by sawan1990** [comment]
Got it solved.

I guess was not in root directory
