### ISSUE TITLE
Error: Cannot find module 'generate-function'

### ISSUE THREAD

**Issue by Monika-Yadav** [driftyco/ionic-cli#1730]
Error: Cannot find module 'generate-function'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\index.js:2:14)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by Monika-Yadav** [comment]
this error is occurring again and again. I have tried everything bt no use. Please help me to resolve the error. Thank you.

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory as well as the command you are running? Thanks, this should help in troubleshooting.

**Comment by DrMYadav** [comment]
Sir, this is my output from "ionic info"

Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

Your system information:

 You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.4.0

Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.1.0
Xcode version: Not installed


******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`
