### ISSUE TITLE
ionic start fails to work

### ISSUE THREAD

**Issue by Codepoet77** [driftyco/ionic-cli#174]
The ionic start command fails for me with the following error on Ubuntu 14.04. 

andrew@FinancialIndepence:~/WebstormProjects/stadiumStore/mobile$ ionic start myApp tabs
Creating Ionic app in folder /home/andrew/WebstormProjects/stadiumStore/mobile/myApp based on tabs project

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s

Downloading: https://github.com/driftyco/ionic-starter-tabs/archive/master.zip
[=============================]  100%  0.0s

Update config.xml
Initializing cordova project
Fetching plugin "org.apache.cordova.device" via plugin registry
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
SyntaxError: Unexpected token I
Internal routing error

Sorry, we cannot connect to the intended server.

We have just been notified of this problem. We will correct it as soon as possible.

Feel free to contact us if you have any questions: support@iriscouch.com

    at Object.parse (native)
    at RegClient.<anonymous> (/home/andrew/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:274:23)
    at /home/andrew/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:251:7
    at Gunzip.onEnd (zlib.js:167:5)
    at Gunzip.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
Unable to add plugins. Perhaps your version of Cordova is too old. Try updating (npm install -g cordova), removing this project folder, and trying again. (CLI v1.3.0)

**Comment by Codepoet77** [comment]
This issue is now resolved. I was able to get past it and am resolving other issues in my dev environment setup as they crop up.
