### ISSUE TITLE
run android -l && run ios -l

### ISSUE THREAD

**Issue by cj** [driftyco/ionic-cli#1749]
I'm running into an issue trying to run two live builds at the same time.  this error is 

```
[19:44:30]  ionic-app-scripts 0.0.45
[19:44:30]  watch started ...
[19:44:30]  build dev started ...
[19:44:30]  clean started ...
[19:44:30]  clean finished in 4 ms
[19:44:30]  copy started ...
[19:44:30]  transpile started ...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:53703
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at net.js:1403:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/cj/.nvm/versions/node/v6.9.1/bin/node" "/Users/cj/.nvm/versions/node/v6.9.1/bin/npm" "run" "ionic:serve" "--" "--port" "8001" "--address" "192.168.1.115" "--liveReloadPort" "8000" "--iscordovaserve" "--nobrowser"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:serve: `ionic-app-scripts serve "--port" "8001" "--address" "192.168.1.115" "--liveReloadPort" "8000" "--iscordovaserve" "--nobrowser"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve "--port" "8001" "--address" "192.168.1.115" "--liveReloadPort" "8000" "--iscordovaserve" "--nobrowser"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve "--port" "8001" "--address" "192.168.1.115" "--liveReloadPort" "8000" "--iscordovaserve" "--nobrowser"
```

There used to be an option to change the `53703` port.  http://stackoverflow.com/questions/40623780/cant-run-multiple-projects-with-ionic-serve.  That doesn't seem to work now.  Is there an alternative way?

**Comment by cj** [comment]
```
± ionic info

Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by DhruvGupta5** [comment]
@cj i use " ionic serve -c -s --dev-logger-port 53704 --livereload-port 35730 --port 8200" it works perfectly you can search for the exact explanation,

**Comment by cj** [comment]
@DhruvGupta5 thank command with run gives the following error `Error: Unknown platforms: 53704`

Full log:

```
cj at mac in ~/Sync/apps/acd/m on mat!
± ionic run -c -s --dev-logger-port 53704 --livereload-port 35730 --port 8200

> ionic-hello-world@ ionic:build /Users/cj/Sync/apps/acd/m
> ionic-app-scripts build

[21:53:02]  ionic-app-scripts 0.0.45
[21:53:02]  build prod started ...
[21:53:02]  clean started ...
[21:53:02]  clean finished in 4 ms
[21:53:02]  copy started ...
[21:53:02]  ngc started ...
[21:53:02]  copy finished in 35 ms
[21:53:06]  ngc finished in 3.10 s
[21:53:06]  webpack started ...
[21:53:06]  webpack finished in 78 ms
[21:53:06]  uglifyjs started ...
[21:53:06]  sass started ...
[21:53:06]  sass finished in 74 ms
[21:53:06]  cleancss started ...
[21:53:06]  uglifyjs finished in 165 ms
[21:53:06]  cleancss finished in 187 ms
[21:53:06]  build prod finished in 3.46 s
Error: Unknown platforms: 53704
```

**Comment by DhruvGupta5** [comment]
update your app scripts file npm install @ionic/app-scripts@nightly it works fine for me

**Comment by cj** [comment]
@DhruvGupta5 still doesn't work with **run** and not serve.

```
○  ionic run ios -c -s --dev-logger-port 53704 --livereload-port 35730 --port 8200

> ionic-hello-world@ ionic:build /Users/cj/Sync/apps/acd/mobile-new
> ionic-app-scripts build

[16:08:20]  ionic-app-scripts 0.0.46-201612070604
[16:08:20]  build prod started ...
[16:08:20]  clean started ...
[16:08:20]  clean finished in 5 ms
[16:08:20]  copy started ...
[16:08:20]  ngc started ...
[16:08:26]  ngc finished in 6.02 s
[16:08:26]  webpack started ...
[16:08:27]  copy finished in 6.17 s
[16:08:34]  webpack finished in 7.16 s
[16:08:34]  uglifyjs started ...
[16:08:34]  sass started ...
[16:08:35]  sass finished in 1.14 s
[16:08:35]  cleancss started ...
[16:08:36]  cleancss finished in 896 ms
[16:08:42]  uglifyjs finished in 8.04 s
[16:08:42]  build prod finished in 21.23 s
Error: Unknown platforms: 53704
```

**Comment by jthoms1** [comment]
Please update to the latest version of the cli. Release 2.1.15 resolved this issue. Thank you!

`npm install -g ionic@latest`
