### ISSUE TITLE
Caught exception ENOSPC 

### ISSUE THREAD

**Issue by sagoyanfisic** [driftyco/ionic-cli#1803]
Running live reload server: http://192.168.1.193:35729
Watching: www/**/*, !www/lib/**/*, !www/**/*.map
√ Running dev server:  http://192.168.1.193:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

ionic $ Caught exception:
 Error: watch www/manifest.json ENOSPC
    at exports._errnoException (util.js:896:11)
    at FSWatcher.start (fs.js:1423:19)
    at Object.fs.watch (fs.js:1450:11)
    at createFsWatchInstance (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:117:15) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Caught exception:
 Error: watch www/service-worker.js ENOSPC
    at exports._errnoException (util.js:896:11)
    at FSWatcher.start (fs.js:1423:19)
    at Object.fs.watch (fs.js:1450:11)
    at createFsWatchInstance (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:117:15) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Caught exception:
 Error: watch www/css/style.css ENOSPC
    at exports._errnoException (util.js:896:11)
    at FSWatcher.start (fs.js:1423:19)
    at Object.fs.watch (fs.js:1450:11)
    at createFsWatchInstance (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:117:15) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Caught exception:
 Error: watch www/img/ionic.png ENOSPC
    at exports._errnoException (util.js:896:11)
    at FSWatcher.start (fs.js:1423:19)
    at Object.fs.watch (fs.js:1450:11)
    at createFsWatchInstance (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:117:15) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Caught exception:
 Error: watch www/js/app.js ENOSPC
    at exports._errnoException (util.js:896:11)
    at FSWatcher.start (fs.js:1423:19)
    at Object.fs.watch (fs.js:1450:11)
    at createFsWatchInstance (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/msalinas/.nvm/versions/node/v6.0.0/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:117:15) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

//
cordova -> 6.4.0
ionic -> 2.1.17
Node v6.0.0
npm 3.8.6

**Comment by sagoyanfisic** [comment]
The solution is to install the version of node 5.x
