### ISSUE TITLE
Error after updating ionic to latest version

### ISSUE THREAD

**Issue by RezaRahmati** [driftyco/ionic-cli#1821]
I have had ionic rc3 on my machine, and this is the result of `ionic info`

 ordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed

Then I update ionic by running `npm install -g ionic`
now I get this error

Caught exception:
 Error: Cannot find module 'lodash/assign'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Reza\AppData\Roaming\npm\node_modules\ionic\node_modules\xmlbuilder\lib\index.js:5:12)
    at Object.<anonymous> (C:\Users\Reza\AppData\Roaming\npm\node_modules\ionic\node_modules\xmlbuilder\lib\index.js:14:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by RezaRahmati** [comment]
cause was npm version 3.10.5 .
Updating npm to latest 4.x fixed it
