### ISSUE TITLE
Unexpected token } in JSON at position 782

### ISSUE THREAD

**Issue by ncubo** [driftyco/ionic-cli#1856]
Hello, I upgrade ionic to version 2. Now, when I try to run "ionic serve --lab" in my V1 ionic project, I have the next issue:

```
Caught exception:
 SyntaxError: Unexpected token } in JSON at position 782
    at Object.parse (native)
    at /usr/local/lib/node_modules/ionic/lib/utils/npmScripts.js:125:30
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12) 
```

**Comment by ncubo** [comment]
Sorry, I solved my problem. It just was that I had a "}" bad closed in my package.json
