### ISSUE TITLE
Getting started example fails on Windows 7

### ISSUE THREAD

**Issue by nighto** [driftyco/ionic-cli#1877]
#### Short description of the problem:
`ionic start --v2 myApp tabs` fails to install

**Steps to reproduce:**
1. On Windows 7 machine with node and npm installed, run `npm install -g cordova ionic`
2. Run `ionic start --v2 myApp tabs`

Here's my `npm install -g cordova ionic` log:
```
C:\Users\ajunior>npm install -g cordova ionic
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
C:\Users\ajunior\AppData\Roaming\npm\cordova -> C:\Users\ajunior\AppData\Roaming
\npm\node_modules\cordova\bin\cordova
C:\Users\ajunior\AppData\Roaming\npm\ionic -> C:\Users\ajunior\AppData\Roaming\n
pm\node_modules\ionic\bin\ionic
cordova@6.5.0 C:\Users\ajunior\AppData\Roaming\npm\node_modules\cordova
├── underscore@1.7.0
├── q@1.0.1
├── nopt@3.0.1 (abbrev@1.0.9)
├── update-notifier@0.5.0 (is-npm@1.0.0, semver-diff@2.1.0, string-length@1.0.1,
 chalk@1.1.3, repeating@1.1.3, configstore@1.4.0, latest-version@1.0.1)
├── insight@0.8.4 (object-assign@4.1.1, async@1.5.2, uuid@3.0.1, lodash.debounce
@3.1.1, chalk@1.1.3, tough-cookie@2.3.2, os-name@1.0.3, configstore@1.4.0, reque
st@2.79.0, inquirer@0.10.1)
├── cordova-common@2.0.0 (underscore@1.8.3, q@1.4.1, unorm@1.4.1, cordova-regist
ry-mapper@1.1.15, semver@5.3.0, ansi@0.3.1, osenv@0.1.4, glob@5.0.15, minimatch@
3.0.3, bplist-parser@0.1.1, shelljs@0.5.3, elementtree@0.1.7, plist@1.2.0)
└── cordova-lib@6.5.0 (cordova-registry-mapper@1.1.15, unorm@1.3.3, valid-identi
fier@0.0.1, opener@1.4.1, properties-parser@0.2.3, semver@4.3.6, nopt@3.0.6, dep
-graph@1.1.0, shelljs@0.3.0, glob@5.0.15, elementtree@0.1.6, request@2.47.0, xco
de@0.9.1, cordova-serve@1.0.1, tar@1.0.2, aliasify@1.9.0, cordova-fetch@1.0.2, i
nit-package-json@1.9.4, plist@1.2.0, cordova-create@1.0.2, cordova-js@4.2.1, npm
@2.15.11)

ionic@2.2.1 C:\Users\ajunior\AppData\Roaming\npm\node_modules\ionic
└── @ionic/app-generators@0.0.3
```

Apparently it installed correctly. Then I tried to `start` an app. Here's the log:

```
C:\Users\ajunior\src>ionic start --v2 mapaCicloviario tabs
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************
Creating Ionic app in folder C:\Users\ajunior\src\mapaCicloviario based on tabs
project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
npm WARN peerDependencies The peer dependency @angular/tsc-wrapped@* included fr
om @ionic/app-scripts will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD
ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it
explicitly.
npm WARN peerDependencies The peer dependency rxjs@* included from @ionic/app-sc
ripts will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD
ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it
explicitly.
npm WARN optional dep failed, continuing fsevents@1.0.17
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.
assign.
\
> node-sass@3.10.1 install C:\Users\ajunior\src\mapaCicloviario\node_modules\@io
nic\app-scripts\node_modules\node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/
v3.10.1/win32-x64-46_binding.node
Binary downloaded and installed at C:\Users\ajunior\src\mapaCicloviario\node_mod
ules\@ionic\app-scripts\node_modules\node-sass\vendor\win32-x64-46\binding.node

> node-sass@3.10.1 postinstall C:\Users\ajunior\src\mapaCicloviario\node_modules
\@ionic\app-scripts\node_modules\node-sass
> node scripts/build.js

"C:\Users\ajunior\src\mapaCicloviario\node_modules\@ionic\app-scripts\node_modul
es\node-sass\vendor\win32-x64-46\binding.node" exists.
 testing binary.
Binary is fine; exiting.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package rxjs@5.0.0-beta.12 does not satisfy its sibling
s' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/core@2.2.1 wants rxjs@5.0.0-beta.12

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ajunior\src\mapaCicloviario\npm-debug.log
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
```

So there was an error when `start`ing the app. I tried to `serve` it, but of course it failed:

```
C:\Users\ajunior\src\mapaCicloviario>ionic serve
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

> ionic-app-base@ ionic:serve C:\Users\ajunior\src\mapaCicloviario
> ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livere
load-port" "35729"

module.js:327
    throw err;
    ^

Error: Cannot find module 'reflect-metadata'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\ajunior\src\mapaCicloviario\node_modules\@io
nic\app-scripts\dist\aot\aot-compiler.js:4:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--" "--v2" "--address"
"0.0.0.0" "--port" "8100" "--livereload-port" "35729"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! ionic-app-base@ ionic:serve: `ionic-app-scripts serve "--v2" "--address
" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-app-base@ ionic:serve script 'ionic-app-scripts ser
ve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"'.
npm ERR! This is most likely a problem with the ionic-app-base package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100
" "--livereload-port" "35729"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-app-base
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls ionic-app-base
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ajunior\src\mapaCicloviario\npm-debug.log
There was an error serving your Ionic application: There was an error with the s
pawned command: serve
```

**Post the output of `ionic info` below please**

```
C:\Users\ajunior\src\mapaCicloviario>ionic info
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

Your system information:

 You have been opted out of telemetry. To change this, run: cordova telemetry on
.
6.5.0

Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v4.4.4
Xcode version: Not installed


******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by tja4472** [comment]
Hi

Try with node v6.9.4

http://ionicframework.com/docs/v2/setup/installation/
> To create Ionic 2 projects, you’ll need to install the latest version of the CLI and Cordova. Before you do that, you’ll need a recent version of Node.js. Download the installer for Node.js 6 or greater and then proceed to install the Ionic CLI and Cordova for native app development:

**Comment by nighto** [comment]
That fixed the issue. To help anyone who happens to have this problem in the future, after updating node, it is not enough to try to install/serve everything again: you will have to uninstall cordova (`npm uninstall -g cordova`), install it again, then `start` the ionic app again.

**Comment by nighto** [comment]
And last but not least: thank you @tja4472! :)
