### ISSUE TITLE
ionic start abctest blank

### ISSUE THREAD

**Issue by tvek** [driftyco/ionic-cli#1905]
COMMAND EXECUTED : ionic start abctest blank

PREQUENTENCIES : previous command(ionic build android) was interupted using Ctrl + C

OUTPUT:
Unable to parse Ionic Config file. Please make sure it is valid JSON (.ionic/ion
ic.config)
Caught exception:
 SyntaxError: Unexpected token   in JSON at position 0
    at Object.parse (native)
    at Object.load (C:\Users\tvek\AppData\Roaming\npm\node_modules\ionic\node_mo
dules\ionic-app-lib\lib\config.js:14:26)
    at Object.<anonymous> (C:\Users\tvek\AppData\Roaming\npm\node_modules\ionic\
lib\utils\stats.js:31:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by tvek** [comment]
Steps to Follow for solving IONIC Configuration Error 
1) Go to your Global ionic node_modules directory where all your global packages are installed.
->Goto the below directory in windows machine
%USERPROFILE%\Application Data\npm\node_modules

2) move to the inside library directory 
\ionic\node_modules\ionic-app-lib\lib

3) Open the "config.json" file in the above directory

4) Change the CONFIG_FILE path by adding a '/' after the '.'
Before : CONFIG_FILE: '.ionic/ionic.config',
After  : CONFIG_FILE: './ionic/ionic.config',
