### ISSUE TITLE
Error: Cannot find module 'internal/fs'

### ISSUE THREAD

**Issue by scott-alvis** [driftyco/ionic-cli#1921]
ionic help produces this error message:

```
$ ionic help

Caught exception:
 Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (/Users/scott.alvis/.npm-packages/lib/node_modules/ionic/node_modules/unzip/node_modules/fstream/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

```

Also after running ionic start --v2 myApp tabs and running ionic serve it starts the server but the browsers reports this:

```
Error: ENOENT: no such file or directory, open '/Users/.../Work/Ionic/tabs/www/index.html'
```

**Post the output of `ionic info` below please**

```
$ ionic info

Your system information:

Cordova CLI: 6.5.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: Mac OS X El Capitan
Node Version: v7.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002

```

Note the versions above are required for my current project outside of the sample ionic applications.

Thank you,

Scott Alvis

**Comment by scott-alvis** [comment]
It appears that running `npm run-script build` directly after `ionic start --v2 myApp tabs` resolves the issue and after building `ionic serve` works as expected.

**Comment by rafaelbuiu** [comment]
`npm rebuild` worked for me
