### ISSUE TITLE
Error: Cannot find module 'colors/safe'

### ISSUE THREAD

**Issue by ninomirabile** [driftyco/ionic-cli#1936]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`
2.2.1

#### Short description of the problem:
Error: Cannot find module 'colors/safe'

#### What behavior are you expecting?
start project

**Steps to reproduce:**

insert any relevant code between the above and below backticks
```
Caught exception:
 Error: Cannot find module 'colors/safe'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Antonino\AppData\Roaming\npm\node_modules\ionic\node_modules\winston\lib\winston\config.js:9:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
**Post the output of `ionic info` below please**

**Comment by ninomirabile** [comment]
I resolve :), uninstall, install.
