### ISSUE TITLE
problem running ionic blank app

### ISSUE THREAD

**Issue by pblag** [driftyco/ionic-cli#1941]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`
3.10.8

#### Short description of the problem:
tried to download npm install -g cordova ionic getting errors with that then when I try to start an app I get the error below

#### What behavior are you expecting?

wanted to open an blank app

**Steps to reproduce:**
1. ionic start myApp blank --v2
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**
Caught exception:
 Error: Cannot find module 'sax'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/paul/.nvm/versions/node/v6.9.1/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:9:9)
    at Object.<anonymous> (/Users/paul/.nvm/versions/node/v6.9.1/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:538:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12) 

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.
