### ISSUE TITLE
Unable to parse Ionic Config file. Please make sure it is valid JSON (.ionic/ionic.config)

### ISSUE THREAD

**Issue by tshesko1** [driftyco/ionic-cli#1951]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`

node -v && nodejs -v && npm -v && cordova -v && git --version && uname -a
v6.9.4
v4.7.2
4.3.0
6.5.0
git version 2.11.0
Linux LOCALHOST 4.9.0-kali2-amd64 #1 SMP Debian 4.9.13-1kali1 (2017-03-01) x86_64 GNU/Linux

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**
Unable to parse Ionic Config file. Please make sure it is valid JSON (.ionic/ionic.config)
Caught exception:
 SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Object.load (/home/maximus/.local/node/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/config.js:14:26)
    at Object.<anonymous> (/home/maximus/.local/node/lib/node_modules/ionic/lib/utils/stats.js:31:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by tshesko1** [comment]
Te following Link solves thus Issue:
http://stackoverflow.com/questions/40776922/unable-to-parse-ionic-config-file-please-make-sure-it-is-valid-json
