### ISSUE TITLE
Error with Ionic

### ISSUE THREAD

**Issue by seothuang** [driftyco/ionic-cli#1969]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`
2.2.1

#### Short description of the problem:
I am not able to run my ionic app. It gave me errors.
I tried to re-install ionic and got the error messages listed here.

#### What behavior are you expecting?
I have installed Ionic last year and had developed a simple app using it.
But now when I tried to run the app using 'ionic emulate android' I received error messages.
I removed Cordova and re-stalled Cordova and Ionic, but only manged to re-installed Cordova.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\IBM\\SDP\\cordova_cli\\\\node.exe',
1 verbose cli   'C:\\Program Files\\IBM\\SDP\\cordova_cli\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'ionc',
1 verbose cli   '-g' ]
2 info using npm@3.10.8
3 info using node@v0.10.26
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData ionc
8 silly fetchNamedPackageData ionc
9 silly mapToRegistry name ionc
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data { raw: 'ionc',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'ionc',
12 silly mapToRegistry   name: 'ionc',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/ionc
14 verbose request uri https://registry.npmjs.org/ionc
15 verbose request no auth needed
16 info attempt registry request try #1 at 15:43:10
17 verbose request id a87c79178ce982db
18 http request GET https://registry.npmjs.org/ionc
19 http 404 https://registry.npmjs.org/ionc
20 verbose headers { 'content-type': 'application/json',
20 verbose headers   'cache-control': 'max-age=0',
20 verbose headers   'content-length': '2',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Fri, 10 Mar 2017 07:43:13 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-cdg8729-CDG',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1489131793.138512,VS0,VE790',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 404,
21 silly get   { 'content-type': 'application/json',
21 silly get     'cache-control': 'max-age=0',
21 silly get     'content-length': '2',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Fri, 10 Mar 2017 07:43:13 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-cdg8729-CDG',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1489131793.138512,VS0,VE790',
21 silly get     vary: 'Accept-Encoding' } ]
22 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/ionc
22 silly fetchPackageMetaData     at makeError (C:\Program Files\IBM\SDP\cordova_cli\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\IBM\SDP\cordova_cli\node_modules\npm\node_modules\npm-registry-client\lib\request.js:280:14)
22 silly fetchPackageMetaData     at Request._callback (C:\Program Files\IBM\SDP\cordova_cli\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
22 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\IBM\SDP\cordova_cli\node_modules\npm\node_modules\request\request.js:187:22)
22 silly fetchPackageMetaData     at Request.EventEmitter.emit (events.js:98:17)
22 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\IBM\SDP\cordova_cli\node_modules\npm\node_modules\request\request.js:1044:10)
22 silly fetchPackageMetaData     at Request.EventEmitter.emit (events.js:95:17)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\IBM\SDP\cordova_cli\node_modules\npm\node_modules\request\request.js:965:12)
22 silly fetchPackageMetaData     at IncomingMessage.EventEmitter.emit (events.js:117:20)
22 silly fetchPackageMetaData     at _stream_readable.js:920:16
22 silly fetchPackageMetaData  error for ionc { [Error: Registry returned 404 for GET on https://registry.npmjs.org/ionc] pkgid: 'ionc', statusCode: 404, code: 'E404' }
23 silly rollbackFailedOptional Starting
24 silly rollbackFailedOptional Finishing
25 silly runTopLevelLifecycles Finishing
26 silly install printInstalled
27 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/ionc
27 verbose stack     at makeError (C:\Program Files\IBM\SDP\cordova_cli\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
27 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\IBM\SDP\cordova_cli\node_modules\npm\node_modules\npm-registry-client\lib\request.js:280:14)
27 verbose stack     at Request._callback (C:\Program Files\IBM\SDP\cordova_cli\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
27 verbose stack     at Request.self.callback (C:\Program Files\IBM\SDP\cordova_cli\node_modules\npm\node_modules\request\request.js:187:22)
27 verbose stack     at Request.EventEmitter.emit (events.js:98:17)
27 verbose stack     at Request.<anonymous> (C:\Program Files\IBM\SDP\cordova_cli\node_modules\npm\node_modules\request\request.js:1044:10)
27 verbose stack     at Request.EventEmitter.emit (events.js:95:17)
27 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\IBM\SDP\cordova_cli\node_modules\npm\node_modules\request\request.js:965:12)
27 verbose stack     at IncomingMessage.EventEmitter.emit (events.js:117:20)
27 verbose stack     at _stream_readable.js:920:16
28 verbose statusCode 404
29 verbose pkgid ionc
30 verbose cwd D:\
31 error Windows_NT 6.2.9200
32 error argv "C:\\Program Files\\IBM\\SDP\\cordova_cli\\\\node.exe" "C:\\Program Files\\IBM\\SDP\\cordova_cli\\node_modules\\npm\\bin\\npm-cli.js" "install" "ionc" "-g"
33 error node v0.10.26
34 error npm  v3.10.8
35 error code E404
36 error 404 Registry returned 404 for GET on https://registry.npmjs.org/ionc
37 error 404
38 error 404 'ionc' is not in the npm registry.
39 error 404 You should bug the author to publish it (or use the name yourself!)
40 error 404 Note that you can also install from a
41 error 404 tarball, folder, http url, or git url.
42 verbose exit [ 1, true ]
```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jthoms1** [comment]
Looks like you misspelled it. Line 5 of your output says `ionc`. 

Try running `npm install -g ionic`. Should fix the issue.

**Comment by seothuang** [comment]
Thanks for the reply.
I solved the problem, I found I have another copy of ionic in another folder.
It works after I deleted that copy.
