### ISSUE TITLE
 [ERROR]: Cannot find module  .../node_modules/@ionic/cli-plugin-cloud 

### ISSUE THREAD

**Issue by rflorat07** [driftyco/ionic-cli#1971]
Followed this guide  http://docs.ionic.io/services/deploy/

Your system information:
    Cordova CLI: 6.4.0
    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: 1.9.1
    ios-sim version: 5.0.13
    OS: macOS Sierra
    Node Version: v6.10.0
    Xcode version: Xcode 8.2.1 Build version 8C1002

1- Run  npm install @ionic/cloud-angular --save
2- Run  ionic io init [ERROR] Unknown plugin: @ionic/cli-plugin-.
3- Run Ionic cloud:setup

{ Error: Cannot find module '.../node_modules/@ionic/cli-plugin-cloud'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.load (.../.nvm/versions/node/v6.10.0/lib/node_modules/ionic/dist/ionic.js:8547:25)
    at .../.nvm/versions/node/v6.10.0/lib/node_modules/ionic/dist/ionic.js:2179:35
    at next (native)
    at .../.nvm/versions/node/v6.10.0/lib/node_modules/ionic/dist/ionic.js:2155:71
    at __awaiter (.../.nvm/versions/node/v6.10.0/lib/node_modules/ionic/dist/ionic.js:2151:12)
    at loadPlugin (.../.nvm/versions/node/v6.10.0/lib/node_modules/ionic/dist/ionic.js:2175:12)
    at Object.<anonymous> (.../.nvm/versions/node/v6.10.0/lib/node_modules/ionic/dist/ionic.js:2259:23)
    at next (native) code: 'MODULE_NOT_FOUND' }
Dependency missing for @ionic/cli-plugin-cloud:

  [ERROR]: Cannot find module '/Users/rflorat/Courses/Ionic/MyTabs/node_modules/@ionic/cli-plugin-cloud'

**Comment by jthoms1** [comment]
Unfortunately we do not yet have a cloud functionality built for v3 beta.  This is being worked on, but not yet available.

**Comment by jthoms1** [comment]
Sorry actually you should be able to accomplish this now with `ionic link`.  There is an option available that a allows you to create a new app. This should accomplish the same thing.

**Comment by jthoms1** [comment]
I have updated the internal documentation of the CLI to account for this going forward.

**Comment by yanglongji** [comment]
same problem .....

**Comment by TheBrockEllis** [comment]
I just installed v3 of the CLI and am getting the same error. I've seen the error when trying to do `ionic serve` and `ionic cordova:platform --help`.

```
{ Error: Cannot find module '/Users/brockellis/Code/footsquare/node_modules/@ionic/cli-build-ionic-angular'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.load (/usr/local/lib/node_modules/ionic/dist/ionic.js:8547:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/dist/ionic.js:2179:35)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/ionic/dist/ionic.js:2155:71
    at __awaiter (/usr/local/lib/node_modules/ionic/dist/ionic.js:2151:12)
    at Object.loadPlugin (/usr/local/lib/node_modules/ionic/dist/ionic.js:2175:12)
    at Promise.all.buildPlugins.map.pkgName (/usr/local/lib/node_modules/ionic/dist/ionic.js:54089:30)
    at Array.map (native) code: 'MODULE_NOT_FOUND' }
Dependency missing for @ionic/cli-build-ionic-angular:
```

**Comment by roofcat** [comment]
neva:primerEjemplo kalel$ ionic serve
{ Error: Cannot find module '/Users/kalel/workspace/jsprojects/primerEjemplo/node_modules/@ionic/cli-build-ionic-angular'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.load (/usr/local/lib/node_modules/ionic/dist/ionic.js:8547:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/dist/ionic.js:2179:35)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/ionic/dist/ionic.js:2155:71
    at __awaiter (/usr/local/lib/node_modules/ionic/dist/ionic.js:2151:12)
    at Object.loadPlugin (/usr/local/lib/node_modules/ionic/dist/ionic.js:2175:12)
    at Promise.all.buildPlugins.map.pkgName (/usr/local/lib/node_modules/ionic/dist/ionic.js:54089:30)
    at Array.map (native) code: 'MODULE_NOT_FOUND' }
Dependency missing for @ionic/cli-build-ionic-angular:

  [ERROR]: Cannot find module '/Users/kalel/workspace/jsprojects/primerEjemplo/node_modules/@ionic/cli-build-ionic-angular'
neva:primerEjemplo kalel$ npm install
npm WARN Invalid name: "Mi Primera Aplicacion"
npm WARN primerEjemplo No description
npm WARN primerEjemplo No repository field.
npm WARN primerEjemplo No README data
npm WARN primerEjemplo No license field.
neva:primerEjemplo kalel$

**Comment by jthoms1** [comment]
Cloud is now no longer a module please update to beta.5
