### ISSUE TITLE
Updating CLI fails with unexpected token =

### ISSUE THREAD

**Issue by daveshirman** [driftyco/ionic-cli#1979]
Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`
```
Davids-MacBook-Air:AddVideo2 daveshirman$ ionic --version
/usr/local/lib/node_modules/ionic/dist/ionic.js:2174
function loadPlugin(projectDir, pluginName, askToInstall = true) {
                                                         ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/bin/ionic:8:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

#### Short description of the problem:
```
/Users/daveshirman/Documents/Ionic Projects/AddVideo2/node_modules/@ionic/cli-utils/dist/index.js:218
    constructor(message, exitCode = 1) {
                                  ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/daveshirman/Documents/Ionic Projects/AddVideo2/node_modules/@ionic/cli-plugin-cordova/bin/postinstall:6:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

#### What behavior are you expecting?
For the CLI to install without breaking!

**Post the output of `ionic info` below please**
same as above

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jthoms1** [comment]
Are you using the latest node 6 LTS install.  CLI v3 requires Node 6.  You can install it here: https://nodejs.org/en/download/

**Comment by daveshirman** [comment]
@jthoms1 Thanks, that appears to have resolved things.  Perhaps it's worth updating the blog post on CLI 3 with this information and the link?
