### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by ibewugb** [driftyco/ionic-cli#1983]
#### What version of the CLI are you using? Output of `ionic --version`
No know due to the error

#### Short description of the problem:
I have installed node v5.4.1 since I need axactly this version. Then I installed Ionic and for every command I get the following error:
```
C:\Users\...\AppData\Roaming\npm\node_modules\ionic\dist\ionic.js:2174
function loadPlugin(projectDir, pluginName, askToInstall = true) {
                                                         ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\...\AppData\Roaming\npm\node_modules\ionic\bin\ionic:8:11)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
```

**Steps to reproduce:**
1. Install Node v5.4.1
2. Try any node command

**Comment by rapropos** [comment]
[The docs](http://ionicframework.com/docs/v2/intro/installation/) say quite specifically than Node 6+ is required.

**Comment by jthoms1** [comment]
@rapropos is correct.  You will need to install Node 6 in order to use the new CLI.
