### ISSUE TITLE
[ERROR]: ionic upload | RangeError: Invalid array length 

### ISSUE THREAD

**Issue by patwaswapnil** [driftyco/ionic-cli#1984]
ionic info
 
    Cordova CLI: 6.5.0
    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.9.4
    Xcode version: Not installed

Error- 
```
✔ Requesting snapshot - done!
\ Uploading snapshot

C:\Users\Swapnil\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:23463
  complete = Array(completeLength + 1).join(this.chars.complete);
             ^

RangeError: Invalid array length
    at ProgressBar.render (C:\Users\Swapnil\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:23463:14)
    at ProgressBar.tick (C:\Users\Swapnil\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:23418:8)
    at Task.progress (C:\Users\Swapnil\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:21613:30)
    at uploadSnapshot (C:\Users\Swapnil\AppData\Roaming\npm\node_modules\ionic\dist\ionic.js:8089:28)
    at Request.superagent.post.field.field.on (C:\Users\Swapnil\AppData\Roaming\npm\node_modules\ionic\dist\ionic.js:8065:21)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Transform.progress._transform (C:\Users\Swapnil\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.js:860:16)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
```

**Comment by sansan88** [comment]
Same issue here:


  Your system information:

    Cordova CLI: 6.5.0
    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.9.1
    Xcode version: Not installed

C:\Users\Sandro\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:23463
  complete = Array(completeLength + 1).join(this.chars.complete);
             ^

RangeError: Invalid array length
    at ProgressBar.render (C:\Users\Sandro\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:23463:14)
    at ProgressBar.tick (C:\Users\Sandro\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:23418:8)
    at Task.progress (C:\Users\Sandro\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:21613:30)
    at uploadSnapshot (C:\Users\Sandro\AppData\Roaming\npm\node_modules\ionic\dist\ionic.js:8089:28)
    at Request.superagent.post.field.field.on (C:\Users\Sandro\AppData\Roaming\npm\node_modules\ionic\dist\ionic.js:8065:21)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Transform.progress._transform (C:\Users\Sandro\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.js:860:16)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)

**Comment by obermoserkitz** [comment]
Same here.

```Cordova CLI: 6.5.0
Ionic CLI Version: 3.0.0-beta.
ios-deploy version: Not instal
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.7.3
Xcode version: Not installed
```

```
C:\Users\Obermoser\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:23463
  complete = Array(completeLength + 1).join(this.chars.complete);
             ^

RangeError: Invalid array length
    at ProgressBar.render (C:\Users\Obermoser\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\
index.js:23463:14)
    at ProgressBar.tick (C:\Users\Obermoser\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\in
dex.js:23418:8)
    at Task.progress (C:\Users\Obermoser\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index
.js:21613:30)
    at uploadSnapshot (C:\Users\Obermoser\AppData\Roaming\npm\node_modules\ionic\dist\ionic.js:8089:28)
    at Request.superagent.post.field.field.on (C:\Users\Obermoser\AppData\Roaming\npm\node_modules\ionic\dist\ionic.js:8
065:21)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Transform.progress._transform (C:\Users\Obermoser\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\
lib\node\index.js:860:16)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)

**Comment by YounessElLamzi** [comment]
Same for me


    Ionic Framework Version: 2.3.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.9.1
    Xcode version: Not installed

✔ Requesting snapshot - done!
/ Uploading snapshot

C:\Users\yellamzi\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:23463
  complete = Array(completeLength + 1).join(this.chars.complete);
             ^

RangeError: Invalid array length
    at ProgressBar.render (C:\Users\yellamzi\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:23463:14)
    at ProgressBar.tick (C:\Users\yellamzi\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:23418:8)
    at Task.progress (C:\Users\yellamzi\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:21613:30)
    at uploadSnapshot (C:\Users\yellamzi\AppData\Roaming\npm\node_modules\ionic\dist\ionic.js:8089:28)
    at Request.superagent.post.field.field.on (C:\Users\yellamzi\AppData\Roaming\npm\node_modules\ionic\dist\ionic.js:8065:21)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Transform.progress._transform (C:\Users\yellamzi\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.js:860:16)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)

**Comment by naokichau** [comment]
me too !!!

**Comment by pontusr** [comment]
I had this issue as well.
It seems the npm package was updated yesterday and upgrading to the latest npm package solved it for me.
```
npm uninstall -g ionic cordova
npm i -g ionic cordova
```

**Comment by obermoserkitz** [comment]
@pontusr 
but isn't this just installing the regular and stable ionic cli? Or is it still installing the @beta stuff?

**Comment by dwieeb** [comment]
Looks like a Windows 10 issue. I will debug this before the next release. Thank you!

**Comment by dwieeb** [comment]
This has been fixed and will be in the latest release. Thank you!

**Comment by patwaswapnil** [comment]
Thanks @dwieeb .

How can i update to this release?

`npm install -g ionic`
or  
`npm install -g ionic@beta`?

**Comment by dwieeb** [comment]
@patwaswapnil The latest beta isn't out yet, but you can use `ionic@canary` (don't forget to update your plugins).
