### ISSUE TITLE
ionic upload fails on bitbucket pipelines

### ISSUE THREAD

**Issue by wodka** [driftyco/ionic-cli#2012]
#### What version of the CLI are you using? Output of `ionic --version`

latest version, new container with "npm install -g ionic cordova"

#### Short description of the problem:

I cannot upload the app from a non interactive shell (perhaps this is relevant), in this case bitbucket pipelines

#### What behavior are you expecting?

upload failing every time

**Steps to reproduce:**
1. setup pipelines in an empty repository
2. push changes
3. error happening

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

```
+ ionic upload --note $VERSION --deploy "dev" --email $IONIC_USER --password $IONIC_PASSWORD
No previous login existed. Attempting to log in now.
Logged in! :)
Uploading app...
Caught exception:
 TypeError: First argument must be a string or Buffer
    at ClientRequest.write (_http_outgoing.js:502:11)
    at FormData.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:96:13)
    at FormData.emit (events.js:191:7)
    at FormData.CombinedStream.write (/usr/local/lib/node_modules/ionic/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:118:8)
    at FormData.CombinedStream._pipeNext (/usr/local/lib/node_modules/ionic/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:106:8)
    at FormData.CombinedStream._getNext (/usr/local/lib/node_modules/ionic/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:79:10)
    at FormData.CombinedStream._pipeNext (/usr/local/lib/node_modules/ionic/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:107:8)
    at FormData.CombinedStream._getNext (/usr/local/lib/node_modules/ionic/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:79:10)
    at FormData.CombinedStream._pipeNext (/usr/local/lib/node_modules/ionic/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:107:8) 
Mind letting us know? https://github.com/driftyco/ionic-cli/issues
Caught exception:
 Error: read ECONNRESET
    at exports._errnoException (util.js:1033:11)
    at TLSWrap.onread (net.js:584:26) 
Mind letting us know? https://github.com/driftyco/ionic-cli/issues
Caught exception:
 Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at TLSSocket.socketCloseListener (_http_client.js:334:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:191:7)
    at _handle.close (net.js:513:12)
    at TCP.done [as _onclose] (_tls_wrap.js:328:7) 
Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

**Comment by bashisha** [comment]
Do any body know the resolution to this issue? I am trying to upload from corporate network.

**Comment by dwieeb** [comment]
@bashisha The proxy configuration docs are here: https://ionicframework.com/docs/cli/configuring.html#using-a-proxy
