### ISSUE TITLE
CLI 3.0.0-beta.4 ionic upload not work, error after auth successfully!!

### ISSUE THREAD

**Issue by javico2609** [driftyco/ionic-cli#2036]
Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`
```
npm view ionic@latest version
2.2.1
```
#### What version of the CLI are you using? Output of `ionic --version`
```
ionic --version
3.0.0-beta.4
```
#### Short description of the problem:

Ionic upload not work return this error
```
 ionic upload
✔ Requesting snapshot - done!
- Uploading snapshot

C:\Users\Javico\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:23463
  complete = Array(completeLength + 1).join(this.chars.complete);
             ^

RangeError: Invalid array length
    at ProgressBar.render (C:\Users\Javico\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:23463:14)
    at ProgressBar.tick (C:\Users\Javico\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:23418:8)
    at Task.progress (C:\Users\Javico\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\index.js:21613:30)
    at uploadSnapshot (C:\Users\Javico\AppData\Roaming\npm\node_modules\ionic\dist\ionic.js:8089:28)
    at Request.superagent.post.field.field.on (C:\Users\Javico\AppData\Roaming\npm\node_modules\ionic\dist\ionic.js:8065:21)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Transform.progress._transform (C:\Users\Javico\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.js:860:16)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
```
#### What behavior are you expecting?
upload my project to cloud

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**
```
 Cordova CLI: 6.5.0
    Ionic Framework Version: 2.3.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v7.7.3
    Xcode version: Not installed 
```
**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by javico2609** [comment]
same error with 3.0.0-beta.5

**Comment by obermoserkitz** [comment]
for me, it is working now

**Comment by naokichau** [comment]
@obermoserkitz how can you make it work? or it just work?

**Comment by javico2609** [comment]
i use the ionic-lab tool for windows it's deprecated but upload work fine because if i use ionic-cli 3 return always the same error

**Comment by naokichau** [comment]
i think only ver 3 > has this issue

**Comment by dwieeb** [comment]
@naokichau @javico2609 The next release of CLI 3 beta is coming soon. I'm not getting the error on my end and I'm not sure what conditions actually make it happen. It's definitely some issue with the progress bar library we're using, but if you don't mind I'd like to get that released before attempting to debug this.

**Comment by naokichau** [comment]
Are you using v3 beta5 @dwieeb ?

**Comment by dwieeb** [comment]
@javico2609 @naokichau @obermoserkitz This is no longer an issue with the latest release. 

Thanks!
