### ISSUE TITLE
ionic not creating app

### ISSUE THREAD

**Issue by cwebcbharat** [driftyco/ionic-cli#2077]
Utils.fail [SyntaxError: /opt/node/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start_wizard.js:99
      ps.stdout.on('data', (data) => {
                                  ^^
Unexpected token =>] undefined
Utils.fail stack /opt/node/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start_wizard.js:99
      ps.stdout.on('data', (data) => {
                                  ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.start_wizard (/opt/node/lib/node_modules/ionic/node_modules/ionic-app-lib/index.js:25:12)
    at Object.<anonymous> (/opt/node/lib/node_modules/ionic/lib/ionic/start.js:13:30)
    at Module._compile (module.js:460:26)
Utils.errorHandler is set, calling that now
Cli.appLibUtils.errorHandler msg [SyntaxError: /opt/node/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start_wizard.js:99
      ps.stdout.on('data', (data) => {
                                  ^^
Unexpected token =>] object

/opt/node/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start_wizard.js:99
      ps.stdout.on('data', (data) => {
                                  ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.start_wizard (/opt/node/lib/node_modules/ionic/node_modules/ionic-app-lib/index.js:25:12)
    at Object.<anonymous> (/opt/node/lib/node_modules/ionic/lib/ionic/start.js:13:30)
    at Module._compile (module.js:460:26)

/opt/node/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start_wizard.js:99
      ps.stdout.on('data', (data) => {
                                  ^^
Unexpected token => (CLI v2.2.2)

Your system information:

Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.13
Node Version: v0.12.9
Xcode version: Not installed

**Comment by jthoms1** [comment]
Please install and use node 4 or above.  https://nodejs.org/en/download/
