### ISSUE TITLE
ionic build initial fail

### ISSUE THREAD

**Issue by ratt** [driftyco/ionic-cli#2090]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta7

#### Short description of the problem:
ionic build ios fails, subsequent builds fail thereafter as well. Both outputs attached 

#### What behavior are you expecting?
build to succeed 

**Steps to reproduce:**
1. npm -g install ionic@beta
2. ionic start
3. ionic serve
4. ionic build ios

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

  Your system information:

    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: 1.9.1
    ios-sim version: 5.0.13
    OS: macOS Sierra
    Node Version: v6.6.0
    Xcode version: Xcode 8.2.1 Build version 8C1002

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Intial Failure
$ ionic cordova build ios
✔ Installing the platform: cordova platform add ios - done!
⠴ Installing the project plugins: cordova plugin add --save <plugin> { Error
    at FatalException.Exception (/Users/jarratt/Development/ionic-egg/node_modules/@ionic/cli-utils/dist/lib/errors.js:8:23)
    at FatalException (/Users/jarratt/Development/ionic-egg/node_modules/@ionic/cli-utils/dist/lib/errors.js:17:9)
    at Shell.<anonymous> (/Users/jarratt/Development/ionic-egg/node_modules/@ionic/cli-utils/dist/lib/shell.js:46:31)
    at throw (native)
    at rejected (/Users/jarratt/Development/ionic-egg/node_modules/@ionic/cli-utils/dist/lib/shell.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:103:7) name: 'Exception', exitCode: 1 }

Secondary build fail
ionic cordova build ios
  Running app-scripts build: --iscordovaserve --externalIpRequired --nobrowser
[08:00:21]  build dev started ...
[08:00:21]  clean started ...
[08:00:21]  clean finished in 2 ms
[08:00:21]  copy started ...
[08:00:21]  transpile started ...
[08:00:23]  transpile finished in 1.93 s
[08:00:23]  preprocess started ...
[08:00:23]  deeplinks started ...
[08:00:23]  deeplinks finished in 22 ms
[08:00:23]  preprocess finished in 22 ms
[08:00:23]  webpack started ...
[08:00:23]  copy finished in 2.06 s
[08:00:30]  webpack finished in 7.47 s
[08:00:30]  sass started ...
[08:00:31]  sass finished in 904 ms
[08:00:31]  postprocess started ...
[08:00:31]  postprocess finished in 47 ms
[08:00:31]  lint started ...
[08:00:31]  build dev finished in 10.40 s
✔ Running build - done!
⠏ Executing cordova command: cordova build ios [08:00:33]  lint finished in 1.54 s
⠙ Executing cordova command: cordova build ios [ERROR] An error occurred while running the above command (exit code 1):

        ** BUILD FAILED **

        The following build commands failed:
        	CompileC /Users/jarratt/Library/Developer/Xcode/DerivedData/MyApp-bfmkixvulxtdwygczqvddidmdxfi/Build/Intermediates/MyApp.build/Debug-iphonesimulator/MyApp.build/Objects-normal/x86_64/AppDelegate.o MyApp/Classes/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
        	CompileC /Users/jarratt/Library/Developer/Xcode/DerivedData/MyApp-bfmkixvulxtdwygczqvddidmdxfi/Build/Intermediates/MyApp.build/Debug-iphonesimulator/MyApp.build/Objects-normal/x86_64/MainViewController.o MyApp/Classes/MainViewController.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
        	CompileC /Users/jarratt/Library/Developer/Xcode/DerivedData/MyApp-bfmkixvulxtdwygczqvddidmdxfi/Build/Intermediates/MyApp.build/Debug-iphonesimulator/MyApp.build/Objects-normal/x86_64/CDVDevice.o MyApp/Plugins/cordova-plugin-device/CDVDevice.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
        	CompileC /Users/jarratt/Library/Developer/Xcode/DerivedData/MyApp-bfmkixvulxtdwygczqvddidmdxfi/Build/Intermediates/MyApp.build/Debug-iphonesimulator/MyApp.build/Objects-normal/x86_64/CDVViewController+SplashScreen.o MyApp/Plugins/cordova-plugin-splashscreen/CDVViewController+SplashScreen.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
        (4 failures)
        Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/jarratt/Development/ionic-egg/platforms/ios/cordova/build-debug.xcconfig,-workspace,MyApp.xcworkspace,-scheme,MyApp,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 5s,build,CONFIGURATION_BUILD_DIR=/Users/jarratt/Development/ionic-egg/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/jarratt/Development/ionic-egg/platforms/ios/build/sharedpch

**Comment by ratt** [comment]
Not sure if this should be moved to the ionic-app-scripts repo?

**Comment by vkniazeu** [comment]
For me, I'm building for the browser, it's only the first build failing in a new project at the `Installing the project plugins: cordova plugin add --save <plugin>` step.
Subsequent browser builds are successful.
```
ionic cordova build browser --prod
✔ Installing the platform: cordova platform add browser - done!
/ Installing the project plugins: cordova plugin add --save <plugin> { Error
    at FatalException.Exception (C:\projects\ionic-test\node_modules\@ionic\cli-utils\dist\lib\errors.js:8:23)
    at FatalException (C:\projects\ionic-test\node_modules\@ionic\cli-utils\dist\lib\errors.js:17:9)
    at Shell.<anonymous> (C:\projects\ionic-test\node_modules\@ionic\cli-utils\dist\lib\shell.js:46:31)
    at Generator.throw (<anonymous>)
    at rejected (C:\projects\ionic-test\node_modules\@ionic\cli-utils\dist\lib\shell.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:109:7) name: 'Exception', exitCode: 1 }

**Comment by dwieeb** [comment]
Is this still an issue? I think the latest CLI will print a much better error message than what I'm seeing.
