### ISSUE TITLE
v3-beta7: `TypeError: Cannot read property 'private' of undefined` on `ionic cordova run --help`

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2092]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta7

#### Short description of the problem:

Calling `ionic cordova run --help` gives this output:

```
> ionic cordova run --help

  Run an Ionic project on a connected device

    Usage
      $ ionic cordova run [platform]

    Inputs
      platform ................. The platform to run: ios, android

    Options
      --livereload, -l ......... Live reload app dev files from the device
      --address ................ Use specific address (livereload req.) (default: 0.0.0.0)
      --consolelogs, -c ........ Print app console logs to Ionic CLI
      --serverlogs, -s ......... Print dev server logs to Ionic CLI
      --port, -p ............... Dev server HTTP port (default: 8100)
      --livereload-port, -r .... Live Reload port (default: 35729)
      --prod ................... Create a prod build with app-scripts
      --list ................... List all available Cordova run targets
      --debug .................. Create a Cordova debug build
      --release ................ Create a Cordova release build
      --device ................. Deploy Cordova build to a device
      --emulator ............... Deploy Cordova build to an emulator
      --target ................. Deploy Cordova build to a device (use --list to see all)

    Examples
      $ ionic cordova run ios --livereload -c -s

TypeError: Cannot read property 'private' of undefined
    at inputs.filter (C:\nvm\v7.9.0\node_modules\ionic\node_modules\@ionic\cli-utils\dist\lib\command\command.js:91:31)
    at Array.filter (native)
    at HelpCommand.getCleanInputsForTelemetry (C:\nvm\v7.9.0\node_modules\ionic\node_modules\@ionic\cli-utils\dist\lib\c
ommand\command.js:90:18)
    at HelpCommand.<anonymous> (C:\nvm\v7.9.0\node_modules\ionic\node_modules\@ionic\cli-utils\dist\lib\command\command.
js:63:48)
    at Generator.next (<anonymous>)
    at fulfilled (C:\nvm\v7.9.0\node_modules\ionic\node_modules\@ionic\cli-utils\dist\lib\command\command.js:4:58)
```

#### What behavior are you expecting?

Probably only the first part of the output, not the error message.

**Steps to reproduce:**
1. Install the v3-beta7 CLI
2. Start project, go into directory
3. Execute `ionic cordova run --help`

**Post the output of `ionic info` below please**

```
  Your system information:
    Cordova CLI: Not installed
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v7.9.0
    Xcode version: Not installed
```

**Comment by piotrowski** [comment]
Same error output for `ionic cordova platform --help`.

**Comment by feliperfmarques** [comment]
Same error output for ionic cordova run --help

**Comment by dwieeb** [comment]
@feliperfmarques Are you also on Windows 10?

**Comment by feliperfmarques** [comment]
@dwieeb I get same error using OSX. Sorry, forgot of paste my output to ```ionic info```. 

Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.0
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: 1.9.1
    ios-sim version: 5.0.13
    OS: OS X El Capitan
    Node Version: v6.9.1
    Xcode version: Xcode 8.1 Build version 8B62

**Comment by jayh92** [comment]
Is this the Easter Egg they were talking about here http://blog.ionic.io/? Just the fact that the CLI beta doesn't actually work? 

If you run 'npm install @ionic/cli-plugin-cordova' in your project directory you can get a little further but you still run into the Cannot read property 'private' of undefined.

**Comment by dwieeb** [comment]
Thanks @piotrowski and @feliperfmarques ! I have fixed the issue for the upcoming release.
