### ISSUE TITLE
Ionic Upload  complete = Array(completeLength + 1).join(this.chars.complete);              ^  RangeError: Invalid array length

### ISSUE THREAD

**Issue by dilipwk** [driftyco/ionic-cli#2106]
**v3 beta7 testing**

Please ensure that you have updated your dependent packages.  We have changed a few of the package names. https://github.com/driftyco/ionic-cli/tree/v3#existing-ionic2-project

**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`
   Cordova CLI: 6.4.0
    Ionic CLI Version: 3.0.0-beta7
    OS: Windows 10
    Node Version: v6.9.1

#### Short description of the problem:
`Ionic upload ` gives error 

#### What behavior are you expecting?
Uploading app to ionic apps dashboard 

**Steps to reproduce:**
1. Create new project 
2. Navigate to the project 
3. `ionic upload` command 

```
>IONIC upload
✔ Requesting snapshot upload - done!
- Uploading snapshot
C:\Users\dilipwk\AppData\Roaming\npm\node_modules\ionic\node_modules\progress\lib\node-progress.js:131
  complete = Array(completeLength + 1).join(this.chars.complete);
             ^

RangeError: Invalid array length
    at ProgressBar.render (C:\Users\dilipwk\AppData\Roaming\npm\node_modules\ionic\node_modules\progress\lib\node-progress.js:131:14)
    at ProgressBar.tick (C:\Users\dilipwk\AppData\Roaming\npm\node_modules\ionic\node_modules\progress\lib\node-progress.js:86:8)
    at Task.progress (C:\Users\dilipwk\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\lib\utils\task.js:52:34)
    at deploy.uploadSnapshot (C:\Users\dilipwk\AppData\Roaming\npm\node_modules\ionic\dist\lib\upload.js:32:24)
    at Request.http_1.createRequest.field.field.on (C:\Users\dilipwk\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\lib\utils\aws.js:19:21)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Transform.progress._transform (C:\Users\dilipwk\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.js:948:16)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
```

**Post the output of `ionic info` below please**
 Your system information:

    Cordova CLI: 6.4.0
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.9.1
    Xcode version: Not installed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by dwieeb** [comment]
Thank you for the report. We are aware of this issue on Windows and we'll track it here -> https://github.com/driftyco/ionic-cli/issues/1984
