### ISSUE TITLE
v3-beta7: CLI gives an error running on MacOS

### ISSUE THREAD

**Issue by ErikSchierboom** [driftyco/ionic-cli#2107]
#### What version of the CLI are you using? Output of `ionic --version`

I am trying to install the latest beta of the CLI.

#### Short description of the problem:

I can install the ionic beta CLI on my Mac, but every `ionic` command I run shows the same error: 

```
/usr/local/lib/node_modules/ionic/dist/ionic.js:51
            const [configData, cliInfo] = yield Promise.all([
                  ^

SyntaxError: Unexpected token [
```

#### What behavior are you expecting?

The CLI should just work.

**Steps to reproduce:**
1. `npm install -g ionic@beta` (which installs ionic@3.0.0-beta7)
2. `ionic start`

**Post the output of `ionic info` below please**

```
/usr/local/lib/node_modules/ionic/dist/ionic.js:51
            const [configData, cliInfo] = yield Promise.all([
                  ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/bin/ionic:8:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by dwieeb** [comment]
What version of node do you have? We require at least Node 6.

**Comment by Amunds** [comment]
I had the same error with Node v5.4. Updating to Node 7 solved the issue.

**Comment by ErikSchierboom** [comment]
Can confirm that upgrading to Node 7 fixes this. Sorry about that.

**Comment by dwieeb** [comment]
@ErikSchierboom No worries! Cheers 🍻
