### ISSUE TITLE
3.0.0-beta7 CLI errors

### ISSUE THREAD

**Issue by mubasshir** [driftyco/ionic-cli#2113]
Not able to create resources 

> **ionic cordova resources -s**

```
 ✔ Collecting resource configuration and source images - done!
 ✔ Uploading source images to prepare for transformations - done!
 ⠴ Generating platform resources Error: encountered bad status code (400) for http://res.ionic.io/api/v1/transform
     at Request.cli_utils_1.createRequest.timeout.type.send.on (/Applications/XAMPP/xamppfiles/htdocs/Excalibur-mobile/node_modules/@ionic/cli-plugin-cordova/dist/lib/resources.js:159:24)
     at emitOne (events.js:96:13)
     at Request.emit (events.js:188:7)
     at Request._emitResponse (/Applications/XAMPP/xamppfiles/htdocs/Excalibur-mobile/node_modules/superagent/lib/node/index.js:745:10)
     at ClientRequest.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/Excalibur-mobile/node_modules/superagent/lib/node/index.js:360:10)
     at ClientRequest.g (events.js:292:16)
     at emitOne (events.js:101:20)
     at ClientRequest.emit (events.js:188:7)
     at HTTPParser.parserOnIncomingClient (_http_client.js:473:21)
     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)

```

Also when I seeked for help I got following error

> ionic cordova resources --help

  Automatically create icon and splash screen resources
  
    Usage
      $ ionic cordova resources 
  
    Options
      --icon, -i ............... Generate icon resources
      --splash, -s ............. Generate splash screen resources
  
    Examples
      $ ionic cordova resources  
  

```
 TypeError: Cannot read property 'private' of undefined
     at inputs.filter (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/dist/lib/command/command.js:91:31)
     at Array.filter (native)
     at HelpCommand.getCleanInputsForTelemetry (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/dist/lib/command/command.js:90:18)
     at HelpCommand.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/dist/lib/command/command.js:63:48)
     at Generator.next (<anonymous>)
     at fulfilled (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/dist/lib/command/command.js:4:58)
```

My Ionic Info
```
    Cordova CLI: 6.5.0 
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: 1.9.1 
    ios-sim version: 5.0.4 
    OS: macOS Sierra
    Node Version: v7.3.0
    Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by 8BallBomBom** [comment]
Run these 2 commands again.

npm install -g ionic@beta
npm install --save-dev @ionic/cli-plugin-ionic-angular@beta @ionic/cli-plugin-cordova@beta

Seems to have fixed it for me.

**Comment by zoinkydoink** [comment]
if u try ionic cordova resources -i it should work, but the ionic cordova resources -s does not work for me either

**Comment by dwieeb** [comment]
This has been fixed and beta8 will be out soon! Thank you!

**Comment by mubasshir** [comment]
@dwieeb any idea when? Still facing same issue

**Comment by dwieeb** [comment]
@mubasshir This fix has been out a long time now.
