### ISSUE TITLE
v3-beta8: `ionic docs` outputs "TypeError: undefined" when not in project directory

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2139]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta8

#### Short description of the problem:

`ionic docs` doesn't open the docs but outputs an error when you execute it outside a project directory:

```
PS C:\Users\Jan\Documents> ionic docs
TypeError: undefined
    at urlFormat (url.js:553:11)
    at new Request (C:\nvm\v6.10.2\node_modules\ionic\node_modules\superagent\lib\node\index.js:136:37)
    at module.exports (C:\nvm\v6.10.2\node_modules\ionic\node_modules\superagent\lib\node\index.js:41:10)
    at Object.createRequest (C:\nvm\v6.10.2\node_modules\ionic\node_modules\@ionic\cli-utils\dist\lib\http.js:33:15)
    at DocsCommand.<anonymous> (C:\nvm\v6.10.2\node_modules\ionic\dist\commands\docs.js:27:35)
    at next (native)
    at fulfilled (C:\nvm\v6.10.2\node_modules\ionic\dist\commands\docs.js:10:58)
```

#### What behavior are you expecting?

Docs are opened in default browser.

**Steps to reproduce:**
1. Install v3.0.0-beta8 CLI
2. Run `ionic info` (outside of project directory)

**Post the output of `ionic info` below please**

```
npm (global):

    @ionic/cli-utils : 0.0.12
    ionic            : 3.0.0-beta8

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by piotrowski** [comment]
(Sidenote: `ionic signup` does successfully open a browser window with the correct URL)

**Comment by piotrowski** [comment]
Found out that it works inside a project directory (makes sense...) so update the issue

**Comment by dwieeb** [comment]
Thanks @piotrowski! This fix will go out soon.
