### ISSUE TITLE
v3-beta8: `ionic cordova build ios` outputs error FatalException.Exception on Windows

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2144]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta8

#### Short description of the problem:

Running `ionic cordova build ios` on Windows outputs error FatalException.Exception:

```
PS C:\Users\Jan\Documents\beta8test> ionic cordova build
? What platform would you like to build: ios, android: ios
{ Error
    at FatalException.Exception (C:\Users\Jan\Documents\beta8test\node_modules\@ionic\cli-utils\dist\lib\errors.js:8:23)
    at FatalException (C:\Users\Jan\Documents\beta8test\node_modules\@ionic\cli-utils\dist\lib\errors.js:17:9)
    at BuildCommand.exit (C:\Users\Jan\Documents\beta8test\node_modules\@ionic\cli-utils\dist\lib\command\command.js:82:16)
    at BuildCommand.checkForMac (C:\Users\Jan\Documents\beta8test\node_modules\@ionic\cli-plugin-cordova\dist\commands\base.js:18:24)
    at BuildCommand.<anonymous> (C:\Users\Jan\Documents\beta8test\node_modules\@ionic\cli-plugin-cordova\dist\commands\base.js:47:22)
    at next (native)
    at C:\Users\Jan\Documents\beta8test\node_modules\@ionic\cli-plugin-cordova\dist\commands\base.js:7:71
    at __awaiter (C:\Users\Jan\Documents\beta8test\node_modules\@ionic\cli-plugin-cordova\dist\commands\base.js:3:12)
    at BuildCommand.preRun (C:\Users\Jan\Documents\beta8test\node_modules\@ionic\cli-plugin-cordova\dist\commands\base.js:44:16)
    at BuildCommand.<anonymous> (C:\Users\Jan\Documents\beta8test\node_modules\@ionic\cli-utils\dist\lib\command\command.js:46:32) name: 'Exception', exitCode: 1 }
```

or

```
PS C:\Users\Jan\Documents\beta8test> ionic cordova build ios
{ Error
    at FatalException.Exception (C:\Users\Jan\Documents\beta8test\node_modules\@ionic\cli-utils\dist\lib\errors.js:8:23)
    at FatalException (C:\Users\Jan\Documents\beta8test\node_modules\@ionic\cli-utils\dist\lib\errors.js:17:9)
    at BuildCommand.exit (C:\Users\Jan\Documents\beta8test\node_modules\@ionic\cli-utils\dist\lib\command\command.js:82:16)
    at BuildCommand.checkForMac (C:\Users\Jan\Documents\beta8test\node_modules\@ionic\cli-plugin-cordova\dist\commands\base.js:18:24)
    at BuildCommand.<anonymous> (C:\Users\Jan\Documents\beta8test\node_modules\@ionic\cli-plugin-cordova\dist\commands\base.js:47:22)
    at next (native)
    at C:\Users\Jan\Documents\beta8test\node_modules\@ionic\cli-plugin-cordova\dist\commands\base.js:7:71
    at __awaiter (C:\Users\Jan\Documents\beta8test\node_modules\@ionic\cli-plugin-cordova\dist\commands\base.js:3:12)
    at BuildCommand.preRun (C:\Users\Jan\Documents\beta8test\node_modules\@ionic\cli-plugin-cordova\dist\commands\base.js:44:16)
    at BuildCommand.<anonymous> (C:\Users\Jan\Documents\beta8test\node_modules\@ionic\cli-utils\dist\lib\command\command.js:46:32) name: 'Exception', exitCode: 1 }
```

#### What behavior are you expecting?

Probably an error message that I can't build iOS project on Windows.

**Steps to reproduce:**
1. Install v3.0.0-beta8 CLI
2. Go to project directory
3. Run `ionic cordova build ios`

**Post the output of `ionic info` below please**

```
npm (global):

    @ionic/cli-utils : 0.0.12
    ionic            : 3.0.0-beta8

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by piotrowski** [comment]
Problem **persists** after running `npm i @ionic/cli-utils@beta` as we talked about on Slack. Probably more a logic error.

**Comment by dwieeb** [comment]
Did you update your plugins, as well?

**Comment by piotrowski** [comment]
Those were up to date at the time of writing:
```
    "@ionic/cli-plugin-cordova": "0.0.13",
    "@ionic/cli-plugin-ionic-angular": "0.0.7",
```

**Comment by dwieeb** [comment]
Ugh, I figured this one out. A much better error message will now be displayed for you
