### ISSUE TITLE
v3-beta8: `ionic cordova` commands don't all fail with nice error message when Cordova is not installed

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2145]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta8

#### Short description of the problem:

`ionic cordova` commands don't all fail with nice error message when Cordova is not installed. These command output a not-nice error message:

```
PS C:\Users\Jan\Documents\beta8test2> ionic cordova platform

> cordova platform list

{ Error
    at FatalException.Exception (C:\Users\Jan\Documents\beta8test2\node_modules\@ionic\cli-utils\dist\lib\errors.js:8:23)
    at FatalException (C:\Users\Jan\Documents\beta8test2\node_modules\@ionic\cli-utils\dist\lib\errors.js:17:9)
    at PlatformCommand.exit (C:\Users\Jan\Documents\beta8test2\node_modules\@ionic\cli-utils\dist\lib\command\command.js:82:16)
    at PlatformCommand.<anonymous> (C:\Users\Jan\Documents\beta8test2\node_modules\@ionic\cli-plugin-cordova\dist\commands\base.js:31:32)
    at throw (native)
    at rejected (C:\Users\Jan\Documents\beta8test2\node_modules\@ionic\cli-plugin-cordova\dist\commands\base.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:109:7) name: 'Exception', exitCode: 1 }
```

```
PS C:\Users\Jan\Documents\beta8test2> ionic cordova plugin

> cordova plugin list

{ Error
    at FatalException.Exception (C:\Users\Jan\Documents\beta8test2\node_modules\@ionic\cli-utils\dist\lib\errors.js:8:23)
    at FatalException (C:\Users\Jan\Documents\beta8test2\node_modules\@ionic\cli-utils\dist\lib\errors.js:17:9)
    at PluginCommand.exit (C:\Users\Jan\Documents\beta8test2\node_modules\@ionic\cli-utils\dist\lib\command\command.js:82:16)
    at PluginCommand.<anonymous> (C:\Users\Jan\Documents\beta8test2\node_modules\@ionic\cli-plugin-cordova\dist\commands\base.js:31:32)
    at throw (native)
    at rejected (C:\Users\Jan\Documents\beta8test2\node_modules\@ionic\cli-plugin-cordova\dist\commands\base.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:109:7) name: 'Exception', exitCode: 1 }
```

#### What behavior are you expecting?

Something more like this:

```
PS C:\Users\Jan\Documents\beta8test2> ionic cordova emulate android

> cordova platform add --save android

[ERROR] Command not found: cordova
```

Or even an error message that describes how to install Cordova.

**Steps to reproduce:**
1. Install v3.0.0-beta8 CLI
2. Go to project directory
3. Run command

**Post the output of `ionic info` below please**

```
npm (global):

    @ionic/cli-utils : 0.0.12
    ionic            : 3.0.0-beta8

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by dwieeb** [comment]
Can you update your plugins and confirm if this is still an issue:

`npm i --save-dev @ionic/cli-plugin-cordova@latest @ionic/cli-plugin-ionic-angular@latest`

**Comment by piotrowski** [comment]
Fixed after running `npm i @ionic/cli-utils@beta` as we talked about on Slack.
