### ISSUE TITLE
[cli 3.0 beta 9] upload impossible

### ISSUE THREAD

**Issue by ThomasKientz** [driftyco/ionic-cli#2163]
Impossible to upload a new snapshot with : `ionic upload`

> `TypeError: Cannot read property 'includes' of undefined`

**Comment by jorgjanke** [comment]
Same here:
```
TypeError: Cannot read property 'includes' of undefined
    at getReleaseChannelName (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/dist/lib/plugins.js:187:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/dist/lib/plugins.js:159:33)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/dist/lib/plugins.js:4:58)
```

**Comment by dwieeb** [comment]
@ThomasKientz @jorgjanke Please update your plugins.

For Ionic Angular:

```bash
npm i --save-dev @ionic/cli-plugin-cordova@beta @ionic/cli-plugin-ionic-angular@beta
```

For Ionic 1:

```bash
npm i --save-dev @ionic/cli-plugin-cordova@beta @ionic/cli-plugin-ionic1@beta
```

**Comment by jorgjanke** [comment]
Thanks! - works! - might be sensible to add it to the changelog / upgrade doc.

**Comment by piotrowski** [comment]
Couldn't this even be automated? If plugin is missing, tell the user and ask him if he wants to install it. Would improve the upgrade experience by miles!

**Comment by dwieeb** [comment]
@jorgjanke 🍻 

The notification will be automatic going forward. See https://twitter.com/mhartington/status/857039470943764482
