### ISSUE TITLE
3.0.0-beta9 ionic serve - TypeError: args.env.prompt is not a function

### ISSUE THREAD

**Issue by jorgjanke** [driftyco/ionic-cli#2166]
#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta9

#### Short description of the problem:

```
$ ionic serve
TypeError: args.env.prompt is not a function
    at Object.<anonymous> (/Users/jorg/Documents/ADev/track4d/node_modules/@ionic/cli-plugin-ionic-angular/dist/serve.js:28:54)
    at Generator.next (<anonymous>)
    at /Users/jorg/Documents/ADev/track4d/node_modules/@ionic/cli-plugin-ionic-angular/dist/serve.js:7:71
    at __awaiter (/Users/jorg/Documents/ADev/track4d/node_modules/@ionic/cli-plugin-ionic-angular/dist/serve.js:3:12)
    at Object.serve (/Users/jorg/Documents/ADev/track4d/node_modules/@ionic/cli-plugin-ionic-angular/dist/serve.js:16:12)
    at Object.<anonymous> (/Users/jorg/Documents/ADev/track4d/node_modules/@ionic/cli-plugin-ionic-angular/dist/index.js:67:24)
    at Generator.next (<anonymous>)
    at /Users/jorg/Documents/ADev/track4d/node_modules/@ionic/cli-plugin-ionic-angular/dist/index.js:7:71
    at __awaiter (/Users/jorg/Documents/ADev/track4d/node_modules/@ionic/cli-plugin-ionic-angular/dist/index.js:3:12)
    at Hook.hooks.register [as callable] (/Users/jorg/Documents/ADev/track4d/node_modules/@ionic/cli-plugin-ionic-angular/dist/index.js:66:61)
```

#### What behavior are you expecting?

normal start

**Steps to reproduce:**
1. install beta9
2. run ionic server - received
```
ionic serve
[WARN] Locally installed CLI Plugin @ionic/cli-plugin-cordova has an update available! Please upgrade: 
           npm install --save-dev @ionic/cli-plugin-cordova@beta
        
[WARN] Locally installed CLI Plugin @ionic/cli-plugin-ionic-angular has an update available! Please upgrade: 
           npm install --save-dev @ionic/cli-plugin-ionic-angular@beta
```
3. did the updates above (installed the beta1)
4. tried to run ionic serve again       

**Post the output of `ionic info` below please**

npm (global):

    @ionic/cli-utils : 1.0.0-beta0
    cordova          : 6.5.0 
    ionic            : 3.0.0-beta9

npm (local):

    @ionic/app-scripts              : 1.3.5
    @ionic/cli-plugin-cordova       : 1.0.0-beta1
    @ionic/cli-plugin-ionic-angular : 1.0.0-beta1
    Ionic Framework                 : ionic-angular 3.1.0

System:

    Node       : v7.4.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.1 Build version 8E1000a 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13

**Comment by jorgjanke** [comment]
ran
  npm i -g @ionic/cli-utils@beta 
with the result
  @ionic/cli-utils@1.0.0-beta1 
and
  UNMET PEER DEPENDENCY strip-ansi@^3.0.1

... but with the same result (ionic serve -> TypeError: args.env.prompt)

**Comment by dwieeb** [comment]
You'll also need to update the cli globally with `npm i -g ionic@beta`

I'm not sure why it didn't also notify you of that update. I will investigate tomorrow.

**Comment by dwieeb** [comment]
![image](https://cloud.githubusercontent.com/assets/236501/25545018/a45ce76c-2c22-11e7-9048-7a4852ae8297.png)

This is the root of the problem. We should've used dots for the beta versions, apparently. Won't be a problem going forward.

Let me know if you still are having issues.
