### ISSUE TITLE
upload error with existing app

### ISSUE THREAD

**Issue by ThomasKientz** [driftyco/ionic-cli#2197]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-rc0

#### Short description of the problem:

Impossible to upload a new archive to an existing app.
```
MacBook-Pro-de-Thomas:WonderParents thomas$ ionic upload
✔ Requesting snapshot upload - done!
⠋ Uploading snapshot [==============================] 100%TypeError: Cannot read property 'substring' of undefined
    at Object.formatSuperAgentError (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/dist/lib/http.js:134:29)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/dist/index.js:119:43)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/ionic/dist/index.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

#### What behavior are you expecting?

The upload to complete without errors.

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

```
global packages:

    @ionic/cli-utils : 1.0.0-rc.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.0.0-rc.0

local packages:

    @ionic/app-scripts              : 1.3.4
    @ionic/cli-plugin-cordova       : 1.0.0-rc.0
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v7.5.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.2.1 Build version 8C1002 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.11 
```

**Comment by dwieeb** [comment]
There's a deeper server error being obscured here. I just pushed a fix that will show the error.

@ThomasKientz Could you possibly update your cli to our canary build and test this? `npm i -g ionic@canary`

**Comment by ThomasKientz** [comment]
The error was coming from my network... I succeed upload a new build with on another network. 

the error was : 

```
HTTP Error 400: POST https://ionic-apps.s3.amazonaws.com/
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message><RequestId>F62FAF7A0A328F20</RequestId><HostId>tda7HH2VojffwYmI9C0rvE62+zW0CqwyY0Ad/LYDSiSAbrEbopcW5JrquU5/WBYBIlVIZSKqk04=</HostId></Error>
``` 

Thank you !
