### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by kostebudinoski** [driftyco/ionic-cli#2242]
After latest ionic update I am getting following issue, on every command execution:

```
ionic serve --verbose
[ERROR] Error occurred while loading plugins. CLI functionality may be limited.
        Checking for CLI updates now...
[DEBUG] Plugin error: Dependency missing for @ionic/cli-plugin-ionic-angular:
          [ERROR]: Cannot find module '\node_modules\@ionic\cli-plugin-ionic-angular'
[DEBUG] Checking for latest plugin version of ionic@latest.
"3.0.0"

[DEBUG] Latest version of ionic@latest is .
[DEBUG] !!! ERROR ENCOUNTERED !!!
SyntaxError: Unexpected end of JSON input
[DEBUG] SyntaxError: Unexpected end of JSON input
            at Object.parse (native)
            at npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\lib\plugins.js:212:36
            at next (native)
            at fulfilled (\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\lib\plugins.js:4:58)
            at process._tickCallback (internal/process/next_tick.js:103:7)
```

Ionic info:

```
[ERROR] Error occurred while loading plugins. CLI functionality may be limited.
        Checking for CLI updates now...
[ERROR] No updates found after plugin error--please report this issue.

global packages:

    @ionic/cli-utils : 1.0.0
    Ionic CLI        : 3.0.0

System:

    Node       : v6.10.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```
ionic --version:
3.0.0

I tried uninstalling and installing ionic@latest package, but it didn't help.

**Comment by piotrowski** [comment]
Tell us a bit about the project that you wanted to `ionic serve`.

**Comment by kostebudinoski** [comment]
Hi Piotrowski, thanks for your reply. Here is my package.json configuration:

```
 "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "4.0.2",
    "@angular/compiler": "4.0.2",
    "@angular/compiler-cli": "4.0.2",
    "@angular/core": "4.0.2",
    "@angular/forms": "4.0.2",
    "@angular/http": "4.0.2",
    "@angular/platform-browser": "4.0.2",
    "@angular/platform-browser-dynamic": "4.0.2",
    "@ionic-native/camera": "^3.5.0",
    "@ionic-native/core": "3.4.2",
    "@ionic-native/splash-screen": "3.4.2",
    "@ionic-native/status-bar": "3.4.2",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.1.1",
    "ionicons": "3.0.0",
    "moment": "^2.15.1",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "^0.8.5"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.4",
    "typescript": "~2.2.1"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-network-information",
    "cordova-sqlite-storage",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "ionic-plugin-keyboard",
    "cordova-plugin-splashscreen"
  ],
  "cordovaPlatforms": [],
```

However, after I updated the packages as follows:

```
"scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "4.1.0",
    "@angular/compiler": "4.1.0",
    "@angular/compiler-cli": "4.1.0",
    "@angular/core": "4.1.0",
    "@angular/forms": "4.1.0",
    "@angular/http": "4.1.0",
    "@angular/platform-browser": "4.1.0",
    "@angular/platform-browser-dynamic": "4.1.0",
    "@ionic-native/camera": "^3.5.0",
    "@ionic-native/core": "3.6.1",
    "@ionic-native/splash-screen": "3.6.1",
    "@ionic-native/status-bar": "3.6.1",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.1.1",
    "ionicons": "3.0.0",
    "moment": "^2.15.1",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "^0.8.10"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.7",
    "@ionic/cli-plugin-ionic-angular": "1.0.0-rc.1",
    "typescript": "~2.2.1"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-network-information",
    "cordova-sqlite-storage",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "ionic-plugin-keyboard",
    "cordova-plugin-splashscreen"
  ],
  "cordovaPlatforms": [],
```

issue is gone.

**Comment by piotrowski** [comment]
Ok, so you update the Angular and Ionic Native packages, updated app-scripts and added @ionic/cli-plugin-ionic-angular (which should be 1.0.0 by the way, not rc1 any more). Correct?

**Comment by kostebudinoski** [comment]
Yes, correct!

Angular 4.0.2 -> 4.1.0
Ionic-native 3.4.2 -> 3.6.1
ZoneJs 0.8.5 -> 0.8.10
Ionic-app-scripts -> 1.3.4 -> 1.3.7
Added ionic/cli-plugin-ionic-angular 1.00.-rc.1

you can reproduce the issue:
1. creating new ionic app
2. paste previous project.json I had
3. run npm install and 
4. run ionic info or ionic serve

**Comment by dwieeb** [comment]
@kostebudinoski Sounds like you got it working with the latest versions of the plugins 👍

**Comment by piotrowski** [comment]
Shouldn't the CLI have caught that? He didn't have any version of the plugin in there before.

From his first message it seems more like if the version check (?) didn't work and that's why it crashed instead of outputting a helpful message.

**Comment by kostebudinoski** [comment]
I agree with @piotrowski, CLI should catch this and display helpful message
