### ISSUE TITLE
CLI V3 - Camera plugin throws an error

### ISSUE THREAD

**Issue by gigocabrera** [driftyco/ionic-cli#2261]
#### Short description of the problem:
When I try to install the camera plugin I get an error

#### What behavior are you expecting?
I expect the plugin install to work

**Steps to reproduce:**
1. ionic cordova plugin add
2. What plugin would you like to add: cordova-plugin-camera

```

[ERROR] An error occurred while running cordova plugin add cordova-plugin-camera --save=cordova-plugin-camera --save (exit code 1):

        Installing "cordova-plugin-camera" for ios
        Installing "cordova-plugin-compat" for ios
        Failed to install 'cordova-plugin-compat':Error
            at Object.parseProjectFile [as parse] (C:\ionic\CajaFuerte-app\platforms\ios\cordova\lib\projectFile.js:51:15)
            at Api.addPlugin (C:\ionic\CajaFuerte-app\platforms\ios\cordova\Api.js:224:33)
            at handleInstall (C:\Users\gigoc\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:611:6)
            at C:\Users\gigoc\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:407:28
            at _fulfilled (C:\Users\gigoc\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
            at self.promiseDispatch.done (C:\Users\gigoc\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
            at Promise.promise.promiseDispatch (C:\Users\gigoc\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
            at C:\Users\gigoc\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49
            at flush (C:\Users\gigoc\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:108:17)
            at _combinedTickCallback (internal/process/next_tick.js:73:7)
        Failed to install 'cordova-plugin-camera':Error
            at Object.parseProjectFile [as parse] (C:\ionic\CajaFuerte-app\platforms\ios\cordova\lib\projectFile.js:51:15)
            at Api.addPlugin (C:\ionic\CajaFuerte-app\platforms\ios\cordova\Api.js:224:33)
            at handleInstall (C:\Users\gigoc\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:611:6)
            at C:\Users\gigoc\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:407:28
            at _fulfilled (C:\Users\gigoc\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
            at self.promiseDispatch.done (C:\Users\gigoc\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
            at Promise.promise.promiseDispatch (C:\Users\gigoc\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
            at C:\Users\gigoc\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49
            at flush (C:\Users\gigoc\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:108:17)
            at _combinedTickCallback (internal/process/next_tick.js:73:7)
        Error: Could not find *-Info.plist file, or config.xml file.
```

**Ionic Info:** 
```
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v7.9.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by dwieeb** [comment]
You're on Windows and you have the iOS Cordova platform installed. Plugin hooks for iOS that run during install will fail on Windows.

**Comment by piotrowski** [comment]
I tried reproducing the problem and on first try I am not able to:

```
PS C:\Users\Jan\Documents\superAfter> ionic cordova plugin add cordova-plugin-camera
> cordova plugin add cordova-plugin-camera --save
✔ Running command - done!
Installing "cordova-plugin-camera" for android
Installing "cordova-plugin-compat" for android
Subproject Path: CordovaLib
Installing "cordova-plugin-camera" for ios
Plugin dependency "cordova-plugin-compat@1.1.0" already fetched, using that version.
Installing "cordova-plugin-compat" for ios
Saved plugin info for "cordova-plugin-camera" to config.xml
Adding cordova-plugin-camera to package.json
PS C:\Users\Jan\Documents\superAfter> ionic info

global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

PS C:\Users\Jan\Documents\superAfter>
```

I will change my Cordova and Node version now so it matches 100%.

**Comment by piotrowski** [comment]
Ok, I also can't reproduce this with Node 7.9.0 and Cordova 6.5.0.

```
PS C:\Users\Jan\Documents\superAfter> ionic cordova plugin add cordova-plugin-camera
> cordova plugin add cordova-plugin-camera --save
✔ Running command - done!
Fetching plugin "cordova-plugin-camera" via npm
Installing "cordova-plugin-camera" for android
Fetching plugin "cordova-plugin-compat" via npm
Installing "cordova-plugin-compat" for android
Subproject Path: CordovaLib
Installing "cordova-plugin-camera" for ios
Installing "cordova-plugin-compat" for ios
Saved plugin info for "cordova-plugin-camera" to config.xml
PS C:\Users\Jan\Documents\superAfter> ionic info

global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v7.9.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

PS C:\Users\Jan\Documents\superAfter>
```

What does `cordova platform list` give you @gigocabrera?

**Comment by gigocabrera** [comment]
@piotrowski thank you for looking into this. I will send you the `cordova platform list` tonight when I get home.

**Comment by piotrowski** [comment]
What I tested with today:

```
PS C:\Users\Jan\Documents\superAfter> ionic cordova platform list
> cordova platform list
✔ Running command - done!
{}
Installed platforms:
  android 6.1.2
  ios 4.3.1
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  browser ~4.1.0
  webos ~3.7.0
  windows ~5.0.0
```

**Comment by gigocabrera** [comment]
Here's what I get when I do `cordova platform list`
```
PS C:\ionic\CajaFuerte-app> cordova platform list
Installed platforms:
  ios 4.3.1
Available platforms:
  amazon-fireos ~3.6.3 (deprecated)
  android ~6.1.1
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  webos ~3.7.0
  windows ~4.4.0
  wp8 ~3.8.2 (deprecated)
```

**Comment by piotrowski** [comment]
Shame. All identical, but can't reproduce :/

**Comment by dwieeb** [comment]
@piotrowski @gigocabrera Concentrate on where this error is coming from: `Error: Could not find *-Info.plist file, or config.xml file.`

**Comment by gigocabrera** [comment]
@dwieeb I tried the same on a mac and I don't get any errors. Something specific to my PC environment. I'll take a closer look at the error mentioned above and I'll report my findings

**Comment by piotrowski** [comment]
Sledge-hammer method: Remove and re-add the iOS platform before adding the plugin. Stuff tends to break in there sometimes.

**Comment by gigocabrera** [comment]
@piotrowski you're the man. That did it. Thank you for your help!
