### ISSUE TITLE
"[DEBUG] Plugin error: FILE_INVALID_JSON"

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2275]
2 people on the forum report the same error:

https://forum.ionicframework.com/t/ionic-serve-fail-after-upgrade-to-ionic-cli-v3/89940

```
[ERROR] Error occurred while loading plugins. CLI functionality may be limited.
Checking for CLI updates now...
[DEBUG] Plugin error: FILE_INVALID_JSON
[DEBUG] Checking for latest plugin version of ionic@latest.
"3.0.0"

[DEBUG] Latest version of ionic@latest is .
[DEBUG] !!! ERROR ENCOUNTERED !!!
SyntaxError: Unexpected end of JSON input
[DEBUG] SyntaxError: Unexpected end of JSON input
at Object.parse (native)
at /Users/boutell/npm/lib/node_modules/ionic/node_modules/@ionic/cli-utils/dist/lib/plugins.js:212:36
at next (native)
at fulfilled (/Users/boutell/npm/lib/node_modules/ionic/node_modules/@ionic/cli-utils/dist/lib/plugins.js:4:58)
```

**ionic info**

```
ERROR] Error occurred while loading plugins. CLI functionality may be limited.
Checking for CLI updates now...
[ERROR] No updates found after plugin error--please report this issue.

global packages:

@ionic/cli-utils : 1.0.0
Ionic CLI        : 3.0.0
System:

Node       : v6.10.1
OS         : macOS Sierra
Xcode      : Xcode 8.3 Build version 8E162
ios-deploy : 1.8.1
ios-sim    : 5.0.6
```

**Comment by dwieeb** [comment]
I would check the `ionic.config.json` file for json errors.

**Comment by dwieeb** [comment]
A commit is in master that will be more descriptive about which file has the error.
