### ISSUE TITLE
After the WannaCry virus and Dell required a update

### ISSUE THREAD

**Issue by stephennurwono** [driftyco/ionic-cli#2309]
$ ionic info
Caught exception:
 Error: EPERM: operation not permitted, mkdir 'C:\WINDOWS\system32\config\systemprofile\.ionic'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:923:18)
    at new IonicStore (C:\Users\Kenobi-Dell\AppData\Roaming\npm\node_modules\ionic\lib\utils\store.js:19:8)
    at Object.<anonymous> (C:\Users\Kenobi-Dell\AppData\Roaming\npm\node_modules\ionic\lib\cli.js:5:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by stephennurwono** [comment]
After reinstall:
rm -rf node_modules
npm install
it works.
