### ISSUE TITLE
Check for package.json file

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#249]
Ran `ionic platform android` and received this error:

```
Running command: /tmp/HelloSwipe/hooks/after_platform_add/010_install_plugins.js 

module.js:340
    throw err;
          ^
Error: Cannot find module '../../package.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/adam/git/ionic/tmp/HelloSwipe/hooks/after_platform_add/010_install_plugins.js:11:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
Error: Hook failed with error code 8: /Users/adam/git/ionic/tmp/HelloSwipe/hooks/after_platform_add/010_install_plugins.js
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:194:23
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:415:13)
```

Looks like a file is missing, but the code should check for this and have a pretty error message.

**Comment by jbavari** [comment]
This is fixed, and closed by 743d0994f1378866a970d43b8559419033afedc5
