### ISSUE TITLE
Can’t build android project

### ISSUE THREAD

**Issue by piernik** [driftyco/ionic-cli#344]
I've got my ionic project and now I want to build android app.
I manage to add `ionic platform android`
But when `ionic build android` I got error:
```
Adding in default Ionic hooks
Running command: "C:\Program Files\nodejs\node.exe" C:\strony\www\polskieszlaki_app\hooks\after_prepare\010_add_platf
orm_class.js C:\strony\www\polskieszlaki_app
add to body class: platform-android
Running command: "C:\Program Files\nodejs\node.exe" C:\strony\www\polskieszlaki_app\hooks\after_prepare\020_remove_sa
ss_from_platforms.js C:\strony\www\polskieszlaki_app
Running command: C:\strony\www\polskieszlaki_app\platforms\android\cordova\build.bat
ERROR building one of the platforms: Error: C:\strony\www\polskieszlaki_app\platforms\android\cordova\build.bat: Comm
and failed with exit code 2
You may not have the required environment or OS to build this project
Error: C:\strony\www\polskieszlaki_app\platforms\android\cordova\build.bat: Command failed with exit code 2
    at ChildProcess.whenDone (C:\Users\Lukasz\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\c
ordova\superspawn.js:131:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

```

I have apache-ant downloaded - `ant` command returns 
```
Buildfile: build.xml does not exist!
Build failed
```

I have java installed - cmd: `java -version` returns
```
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
```
I have android sdk installed - cmd `android` opens SDK

Here is my `PATH` - `echo %PATH%`
```
C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\Windo
wsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Fi
les (x86)\Git\cmd;C:\Users\Lukasz\AppData\Roaming\npm;c:\strony\www\apache_ant\apache-ant-1.9.4\bin;c:\Users\Lukasz\A
ppData\Local\Android\android-sdk\tools;c:\Users\Lukasz\AppData\Local\Android\android-sdk\platform-tools;c:\Program Fi
les\Java\jdk1.8.0_25\bin
```

I'm running on windows 8.1 64 bits - what's wrong??

**Comment by piernik** [comment]
SOLVED: I had to add to PATH `C:\Program Files\nodejs\bin`
