### ISSUE TITLE
Error during platform add without default hooks

### ISSUE THREAD

**Issue by ackerdev** [driftyco/ionic-cli#366]
When starting a new project via `ionic start myapp blank`, the hooks directory only contains the hook after_prepare/010_add_platform_class.js.

When attempting to run `ionic platform add ios`, the following is output:

```
$ ionic platform add ios
Downloading Default Ionic Resources

Downloading: https://github.com/driftyco/ionic-default-resources/archive/master.zip
[=============================]  100%  0.0s
Done adding default Ionic resources
Adding icons for platform: ios
running cordova platform add ios
Adding ios project...
iOS project created with cordova-ios@3.8.0
Running command: /Users/.../Projects/testproj/hooks/after_prepare/010_add_platform_class.js /Users/.../Projects/testproj
Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1155:11)
    at Object.exports.spawn (child_process.js:988:9)
    at Object.exports.spawn (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:100:31)
    at runScriptViaChildProcessSpawn (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:188:23)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:131:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:114:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
```

Running `ionic hooks add` before `ionic platform add ios` seems to allow the operation to succeed without error; it seems to be trying to interact with hooks that don't exist since they're no longer added by default.

ionic-cli 1.3.19
cordova 4.3.0
node v0.12.1

**Comment by jbavari** [comment]
@ackerdev this will be fixed in the next release.

In the meantime, please run this in your Ionic app's directory:

`chmod -R 755 hooks/`

**Comment by jbavari** [comment]
In the meantime, please use the ionic 1.4.0 beta 7 - `npm install -g ionic@extlib`.
