### ISSUE TITLE
Error creating a new app

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-cli#406]
CLI version is 1.4.0-beta7

I made a new project and used -w (no Cordova). I got:

Adding in iOS application by default
Error Initializing app:  CordovaError: Current working directory is not a Cordova-based project.
    at Object.cdProjectRoot (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/src/cordova/util.js:119:15)
    at Object.platform (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/src/cordova/platform.js:441:36)
    at Object.addPlatform (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/cordova.js:204:18)
    at Object.addDefaultPlatforms (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:102:20)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:76:18
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)

It looks like the 'auto add ios' feature doesn't take into account the no-cordova flag.

**Comment by jbavari** [comment]
Roger, i'll hop on it later. Thanks for reporting!

**Comment by jbavari** [comment]
I've got this committed in ionic-app-lib. I'm aiming to release 1.4.0 next week.
