### ISSUE TITLE
ionic browser remove corsswalk fails

### ISSUE THREAD

**Issue by adamduren** [driftyco/ionic-cli#430]
**System Information:**
```
Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.8.11
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.4
Ionic App Lib Version: 0.0.20
ios-deploy version: Not installed
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.12.2
Xcode version: Xcode 6.3.1 Build version 6D1002
```

**Traceback:**
```
➜ ionic browser remove crosswalk
ReferenceError: argv is not defined
    at Object.removeBrowser (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/browser.js:605:7)
    at Object.run (/usr/local/lib/node_modules/ionic/lib/ionic/browser.js:75:17)
    at Object.run (/usr/local/lib/node_modules/ionic/lib/cli.js:71:32)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/bin/ionic:13:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
Exception: [ReferenceError: argv is not defined]
```

**Comment by jbavari** [comment]
Thanks for reporting. Patching now.

**Comment by adamduren** [comment]
Awesome, thanks!

**Comment by jbavari** [comment]
Would you mind verifying it works for you in the latest CLI beta?

`npm install -g ionic@beta`

**Comment by adamduren** [comment]
```
➜ ionic browser remove crosswalk
Removing crosswalk browser
➜
```
That did the trick. I'm not sure if it's intentional or not but it left this in my `ionic.project` file.

```
  "browsers": [
    {
      "platform": "android",
      "browser": "crosswalk",
      "version": "12.41.296.5"
    }
  ]
```

**Comment by jbavari** [comment]
Ah, patching. Thanks again.

**Comment by jbavari** [comment]
New beta is out - please try one more! Thanks again.

**Comment by adamduren** [comment]
That worked, no traces left behind from adding crosswalk and then removing! Thanks again.

**Comment by jbavari** [comment]
No problem. 1.4.5 is good to go.
