### ISSUE TITLE
Repeated "Ionic not Defined" Error

### ISSUE THREAD

**Issue by hejalsoni** [driftyco/ionic-cli#451]
I tried to...
-clear the cache
-restart the computer
-uninstall and reinstall ionic
...but it did not work and this error persists.

Entire error statement below:
server start error: ReferenceError: ionic is not defined
    at Object.gulpStartupTasks (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/serve.js:253:14)
    at Object.start (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/serve.js:487:36)
    at /usr/local/lib/node_modules/ionic/lib/ionic/serve.js:60:20
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by jbavari** [comment]
I see the error. Can you use a previous version other than what you are using until we patch that?

`npm install ionic@1.4.3` for example.

**Comment by hejalsoni** [comment]
Okay! Is there a specific reason why I am getting the error?

**Comment by markomarkovic** [comment]
I'm getting the same error, tried with `ionic@1.4.4`, `ionic@1.4.5` and `ionic@1.5.0`.

```
% ionic info
Your system information:

Cordova CLI: 5.0.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.0
Ionic App Lib Version: 0.1.0
ios-deploy version: Not installed
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.4
Xcode version: Xcode 6.3.2 Build version 6D2105 
```

```
% ionic serve -b
server start error: ReferenceError: ionic is not defined
    at Object.gulpStartupTasks (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/serve.js:256:14)
    at Object.start (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/serve.js:490:36)
    at /usr/local/lib/node_modules/ionic/lib/ionic/serve.js:69:20
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by jbavari** [comment]
@markomarkovic do you have gulp tasks defined in your `ionic.project` file?

**Comment by markomarkovic** [comment]
@jbavari Yes, I have `["sass", "watch"]` as `gulpStartupTasks` and the error was there. The installed `node_modules` were not the correct ones (I think they just got copied from linux, and did not get  installed for OSX). After removing and reinstalling them, everything works. Thank you for the hint.

**Comment by developerant** [comment]
perhaps missing something... try 

sudo npm install -g ionic
ionic plugin add ionic-plugin-deploy

**Comment by SunilRumbaLama** [comment]
Any solutions yet??? i have facing the same problem. Latest ionic CLI, still no worth.

**Comment by richard457** [comment]
Did the bug got a fix I am still having please help me I am in hackton

**Comment by BrianDAC** [comment]
@richard457 did u fix it? im having the same issue too

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
