### ISSUE TITLE
An uncaught exception occured and has been reported to Ionic

### ISSUE THREAD

**Issue by TongChia** [driftyco/ionic-cli#459]
```
Initializing cordova project
Adding in iOS application by default
npm http GET https://registry.npmjs.org/cordova-ios/3.8.0
An uncaught exception occured and has been reported to Ionic

Request path contains unescaped characters. (CLI v1.5.0)

Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.0
Ionic App Lib Version: 0.1.0
ios-deploy version: 1.7.0
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.4
Xcode version: Xcode 6.3.1 Build version 6D1002
```

**Comment by TongChia** [comment]
cordova platform add ios
npm http GET https://registry.npmjs.org/cordova-ios/3.8.0
TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:73:11)
    at TunnelingAgent.exports.request (http.js:49:10)
    at TunnelingAgent.createSocket (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:117:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:184:41)
    at TunnelingAgent.addRequest (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/node_modules/tunnel-agent/index.js:80:8)
    at new ClientRequest (_http_client.js:154:16)
    at Object.exports.request (http.js:49:10)
    at Object.exports.request (https.js:136:15)
    at Request.start (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:594:30)
    at Request.end (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:1186:28)
