### ISSUE TITLE
Ionic share fails.  ReferenceError: argv is not defined

### ISSUE THREAD

**Issue by scottgeye** [driftyco/ionic-cli#485]
I get the following error output whenever I try to share the app I just uploaded via the CLI:

ReferenceError: argv is not defined
    at Object.IonicTask.get (/usr/local/lib/node_modules/ionic/lib/ionic/login.js:105:16)
    at Object.IonicTask.run (/usr/local/lib/node_modules/ionic/lib/ionic/share.js:57:9)
    at Object.run (/usr/local/lib/node_modules/ionic/lib/cli.js:89:32)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/bin/ionic:9:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

argv is not defined (CLI v1.5.2)

Your system information:

Cordova CLI: 4.2.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.2
Ionic App Lib Version: 0.2.0
ios-deploy version: Not installed
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.10.26
Xcode version: Xcode 6.3.2 Build version 6D2105

**Comment by jbavari** [comment]
Fixed in 1.5.3
