### ISSUE TITLE
ReferenceError: argv is not defined on "ionic share"

### ISSUE THREAD

**Issue by tonycurwen** [driftyco/ionic-cli#487]
Running ionic share and getting argv not defined error. Just upgraded the command line to 1.5.2, was working yesterday before the upgrade.

Also run npm -g update, but same issue.

ReferenceError: argv is not defined
    at Object.IonicTask.get (/usr/local/lib/node_modules/ionic/lib/ionic/login.js:105:16)
    at Object.IonicTask.run (/usr/local/lib/node_modules/ionic/lib/ionic/share.js:57:9)
    at Object.run (/usr/local/lib/node_modules/ionic/lib/cli.js:89:32)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/bin/ionic:9:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

argv is not defined (CLI v1.5.2)

Your system information:

Cordova CLI: 5.1.1
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.2
Ionic App Lib Version: 0.2.0
ios-deploy version: Not installed
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.2
Xcode version: Xcode 6.3.2 Build version 6D2105

**Comment by jbavari** [comment]
Fixed in 1.5.3.

**Comment by mpatel99** [comment]
running ionic app build command and getting same error as above
----------------------------------------------------------------------------------------
ionic app build android

ReferenceError: argv is not defined
    at Object.IonicTask.get (/usr/local/lib/node_modules/ionic/lib/ionic/login.js:105:16)
    at Object.IonicTask.run (/usr/local/lib/node_modules/ionic/lib/ionic/app.js:31:9)
    at Object.run (/usr/local/lib/node_modules/ionic/lib/cli.js:95:32)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/bin/ionic:9:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)

argv is not defined (CLI v1.7.12)

Your system information:

Cordova CLI: 5.4.1
Ionic Version: 1.2.1
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.2 Build version 7C68
