### ISSUE TITLE
Uh oh! Problem adding Crosswalk

### ISSUE THREAD

**Issue by zarko-tg** [driftyco/ionic-cli#489]
```
...
Added ./engine/cordova-android-c0.6.1/ platform

Added Cordova Android 4.0
4.0.0-dev
Error: [TypeError: Uh oh!
Invalid Version: ]
TypeError: Uh oh!
Invalid Version: 
    at new SemVer (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/node_modules/semver/semver.js:271:11)
    at compare (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/node_modules/semver/semver.js:424:10)
    at Function.lt (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/node_modules/semver/semver.js:458:10)
    at Object.module.exports.framework.install (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/plugman/platforms/android.js:150:62)
    at installWrapper (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/platforms/platforms.js:77:32)
    at Object.ActionStack.process (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/plugman/util/action-stack.js:68:25)
    at handleInstall (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/plugman/install.js:554:20)
    at /Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/plugman/install.js:346:28
    at _fulfilled (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/q/q.js:509:49
    at flush (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
 ✗ 
An error with adding Crosswalk browser occured TypeError: Uh oh!
Invalid Version: 

TypeError: Uh oh!
Invalid Version: 
    at new SemVer (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/node_modules/semver/semver.js:271:11)
    at compare (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/node_modules/semver/semver.js:424:10)
    at Function.lt (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/node_modules/semver/semver.js:458:10)
    at Object.module.exports.framework.install (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/plugman/platforms/android.js:150:62)
    at installWrapper (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/platforms/platforms.js:77:32)
    at Object.ActionStack.process (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/plugman/util/action-stack.js:68:25)
    at handleInstall (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/plugman/install.js:554:20)
    at /Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/plugman/install.js:346:28
    at _fulfilled (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/q/q.js:509:49
    at flush (/Users/zarko/.nvm/v0.12.4/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)

Uh oh!
Invalid Version:  (CLI v1.5.3)
```

Your system information:

Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.3
Ionic App Lib Version: 0.2.0
ios-deploy version: 1.7.0 
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.4
Xcode version: Xcode 6.3.2 Build version 6D2105

**Comment by jbavari** [comment]
Fixed in 1.5.4.
