### ISSUE TITLE
Error on ionic browser remove crosswalk

### ISSUE THREAD

**Issue by do-web** [driftyco/ionic-cli#500]
ionic browser remove crosswalk
Removing crosswalk browser
 ✗ Trace
    at Object.save (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/project.js:67:13)
    at Object.removeBrowserInstallation (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/browser.js:544:16)
    at Object.removeBrowser (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/browser.js:647:11)
    at Object.run (/usr/local/lib/node_modules/ionic/lib/ionic/browser.js:75:17)
    at Object.run (/usr/local/lib/node_modules/ionic/lib/cli.js:89:32)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/bin/ionic:9:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
 ✗ This should never happen!
 ✗ Unable to save settings file: TypeError: Arguments to path.join must be strings

ionic -v
1.5.5

If i want to add crosswalk i get:

An error with adding Crosswalk browser occured Error: There was an error adding the Cordova Android library
There was an error adding the platform:TypeError: Invalid Version:

Error: There was an error adding the Cordova Android library
There was an error adding the platform:TypeError: Invalid Version:
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/browser.js:332:11
    at _rejected (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)

There was an error adding the Cordova Android library
There was an error adding the platform:TypeError: Invalid Version:  (CLI v1.5.5)

**Comment by cahara** [comment]
i had this same issue. Try downgrading Ionic to 1.5.0 as a work around.

**Comment by jbavari** [comment]
I got this fixed and will be released shortly - commit here: https://github.com/driftyco/ionic-app-lib/commit/3cd5c5624fa95641ab34bca77d846f4152adfcf1

**Comment by jbavari** [comment]
Fixed in 1.6.0.
