### ISSUE TITLE
Error: ionic platform add android - Request path contains unescaped characters

### ISSUE THREAD

**Issue by murugavelit10** [driftyco/ionic-cli#563]
Hi,
I have installed the following:
**JDK** _v1.7.0_55_
**Node** _v0.12.7_
**Npm** _v2.11.3_
**Ionic** _v1.0.1_
**Ionic CLI** _v1.6.4_
**Ionic App Lib** _v0.3.8_
**Cordova** _v5.1.1_ and
**Ant** _v1.9.6_
**Platform** _Windows 7 Professional SP1_
**Proxy** _Yes, Corporate proxy_

I have created **myApp** using the following command:
`ionic start myApp tabs`

When I try to add platform I'm getting the following error
```
D:\ionic\myApp>ionic platform add android
Updated the hooks directory to have execute permissions
npm http GET https://registry.npmjs.org/cordova-android
TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:73:11)
    at TunnelingAgent.exports.request (http.js:49:10)
    at TunnelingAgent.createSocket (C:\Users\gbs03602\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:117:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (C:\Users\gbs03602\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:184:41)
    at TunnelingAgent.addRequest (C:\Users\gbs03602\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:80:8)
    at new ClientRequest (_http_client.js:154:16)
    at Object.exports.request (http.js:49:10)
    at Object.exports.request (https.js:136:15)
    at Request.start (C:\Users\gbs03602\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:594:30)
    at Request.end (C:\Users\gbs03602\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:1186:28)
```

I have googled and found lot of solutions to fix this issue like replace tunnel-agent from this [link](https://github.com/mikeal/tunnel-agent), configure **PROXY** and so on.

Nothing works for me. Hope this will be fixed soon.

Thanks

**Comment by doggy8088** [comment]
I have the same issue.  Is there any workaround?

**Comment by ThorstenHans** [comment]
did you configure the proxy for `npm` ? -> http://jjasonclark.com/how-to-setup-node-behind-web-proxy/

**Comment by doggy8088** [comment]
@ThorstenHans I'm using **ionic start appName templateName** command.  This command don't use npm's proxy settings.

**Comment by ThorstenHans** [comment]
@doggy8088 the ionic cli is using npm to pull resources as you can see in your output

**Comment by ThorstenHans** [comment]
@doggy8088 got it, log was missguiding... the npm call before was completed successfully... sorry

**Comment by doggy8088** [comment]
@ThorstenHans  Here is the screenshot below.  When I set PROXY environment variable before run ```ionic start``` command, it'll always output that error.

![image](https://cloud.githubusercontent.com/assets/88981/9655990/b5db19c8-5267-11e5-988c-540adbe2bd88.png)

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
