### ISSUE TITLE
Failed to add ios platform

### ISSUE THREAD

**Issue by luozhihua** [driftyco/ionic-cli#572]
I want add ios platform, but failed.

OS: os x Yosemite 10.10.5
Node: v0.12.5
ionic: v1.6.4
cordova: v5.2.0

Commands Terminal log:
```
ionic platform add ios
Updated the hooks directory to have execute permissions
Adding ios project...
iOS project created with cordova-ios@3.9.1
mv: dest file already exists: /Users/colin/zxinsight/mw-jssdk-example/platforms/ios/CordovaExample

Running command: /Users/colin/zxinsight/mw-jssdk-example/hooks/after_prepare/010_add_platform_class.js /Users/colin/zxinsight/mw-jssdk-example
add to body class: platform-ios
Installing "com.ionic.keyboard" for ios
Failed to install 'com.ionic.keyboard':Error: does not appear to be an xcode project (no xcode project file)
    at Object.module.exports.parseProjectFile (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/ios.js:179:19)
    at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:56:45)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:576:20)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:363:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
Error: does not appear to be an xcode project (no xcode project file)
    at Object.module.exports.parseProjectFile (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/ios.js:179:19)
    at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:56:45)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:576:20)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:363:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
```

**Comment by smarques** [comment]
:+1:

**Comment by LTroya** [comment]
Same issue here. I installed ionic tabs' template

**Comment by jbavari** [comment]
@luozhihua Could you try deleting the platforms folder and re-adding ios again?

**Comment by luozhihua** [comment]
@jbavari I deleted the project and restart a new ionic project,  It's looks like ok now!

**Comment by luozhihua** [comment]
At first, I deleted platforms folder and re-adding ios, But it throws same error still!

**Comment by ceoaliongroo** [comment]
How solve it in a work in progress project?

**Comment by tlancina** [comment]
@ceoaliongroo does removing `com.ionic.keyboard` and installing `ionic-plugin-keyboard` work? More info here: https://github.com/driftyco/ionic-plugin-keyboard/issues/102#issuecomment-192910209.

Going to close this as `com.ionic.keyboard` is no longer used, but feel free to open a new issue if you're having problems, thanks!
