### ISSUE TITLE
Having trouble uploading ionic app

### ISSUE THREAD

**Issue by Bhupadhy** [driftyco/ionic-cli#575]
This is the error I am getting:

BhavikUhyayaMBP:aven Bhavik$ ionic upload
Uploading app....
An uncaught exception occurred and has been reported to Ionic

value is out of bounds (CLI v1.6.4)

Your system information:

Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: Not installed
ios-sim version: 4.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 6.4 Build version 6E35b 

errorHandler had an error [Error: process exited before Archiver could finish emitting data]
Error: process exited before Archiver could finish emitting data
    at null.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/archiver/lib/modules/core/index.js:42:13)
    at process.g (events.js:199:16)
    at process.emit (events.js:129:20)
    at process.exit (node.js:600:17)
    at Object.errorHandler (/usr/local/lib/node_modules/ionic/lib/cli.js:535:15)
    at handleUncaughtExceptions (/usr/local/lib/node_modules/ionic/lib/cli.js:513:9)
    at /usr/local/lib/node_modules/ionic/node_modules/opbeat-ionic/index.js:153:18
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/opbeat-ionic/lib/request.js:51:21)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:426:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at TLSSocket.socketOnData (_http_client.js:317:20)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at TLSSocket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

**Comment by weber-stephen** [comment]
Have the same issue. Was there a resolution?

**Comment by Bhupadhy** [comment]
It had to do with the plugins I had installed, try removing unneeded plugins and the links to them. It might be parsePush plugin or the cordova whitelist plugin. After I figured out it was one of my plugins I found a different fork/version and used that and the upload went through.

**Comment by weber-stephen** [comment]
Ah! Found it. It was angular material design icons bower plugin here (https://github.com/klarsys/angular-material-icons). Thanks for your help!

**Comment by klh** [comment]
this is not fixed,
its not a plugin issue - but a dependency issue - the ZIP library you're using doesn't support large files or many files well... you should change that dependency.


**Full error is:**
```
buffer.js:716
    throw new TypeError('value is out of bounds');
    ^
TypeError: value is out of bounds
    at checkInt (buffer.js:716:11)
    at Buffer.writeUInt16LE (buffer.js:770:5)
    at /Users/kk/.nvm/versions/node/v0.12.6/lib/node_modules/ionic/node_modules/zip-stream/lib/headers.js:41:32
    at Array.forEach (native)
    at ZipHeaderCentralFooter.ZipHeader.toBuffer (/Users/kk/.nvm/versions/node/v0.12.6/lib/node_modules/ionic/node_modules/zip-stream/lib/headers.js:28:15)
    at Object.exports.encode (/Users/kk/.nvm/versions/node/v0.12.6/lib/node_modules/ionic/node_modules/zip-stream/lib/headers.js:198:24)
    at ZipStream._writeCentralDirectory (/Users/kk/.nvm/versions/node/v0.12.6/lib/node_modules/ionic/node_modules/zip-stream/lib/zip-stream.js:220:22)
    at ZipStream.finalize (/Users/kk/.nvm/versions/node/v0.12.6/lib/node_modules/ionic/node_modules/zip-stream/lib/zip-stream.js:270:8)
    at Zip.finalize (/Users/kk/.nvm/versions/node/v0.12.6/lib/node_modules/ionic/node_modules/archiver/lib/modules/zip/index.js:39:15)
    at Archiver._onQueueEnd (/Users/kk/.nvm/versions/node/v0.12.6/lib/node_modules/ionic/node_modules/archiver/lib/modules/core/index.js:91:26)
```

**related issues:**

- https://github.com/archiverjs/node-archiver/issues/61
- https://github.com/archiverjs/node-zip-stream/issues/5
- https://github.com/archiverjs/node-archiver/issues/64

@archiverjs
