### ISSUE TITLE
Error:Spawn Eaccess

### ISSUE THREAD

**Issue by Gardezi1** [driftyco/ionic-cli#576]
Hey guys I am getting this error. Can somebody help me out 

Running command: /home/kwanso/todo/hooks/after_prepare/010_add_platform_class.js /home/kwanso/todo
add to body class: platform-android
Running command: /home/kwanso/todo/hooks/after_prepare/020_remove_sass_from_platforms.js /home/kwanso/todo
Running command: /home/kwanso/todo/platforms/android/cordova/build 
ANDROID_HOME=/home/kwanso/Desktop/android-sdk-linux
JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
Running: /home/kwanso/todo/platforms/android/gradlew cdvBuildDebug -b /home/kwanso/todo/platforms/android/build.gradle -Dorg.gradle.daemon=true
error caught: Error: spawn EACCES
/home/kwanso/todo/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at Object.exports.spawn (child_process.js:995:9)
    at module.exports (/home/kwanso/todo/platforms/android/cordova/lib/spawn.js:37:35)
    at /home/kwanso/todo/platforms/android/cordova/lib/build.js:343:24
    at _fulfilled (/home/kwanso/todo/platforms/android/cordova/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/home/kwanso/todo/platforms/android/cordova/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/home/kwanso/todo/platforms/android/cordova/node_modules/q/q.js:760:13)
    at /home/kwanso/todo/platforms/android/cordova/node_modules/q/q.js:821:14
    at flush (/home/kwanso/todo/platforms/android/cordova/node_modules/q/q.js:108:17)
ERROR building one of the platforms: Error: /home/kwanso/todo/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /home/kwanso/todo/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/home/kwanso/.npm-packages/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

**Comment by jbavari** [comment]
Could you please run `ionic info` and post that information here?

**Comment by Gardezi1** [comment]
@jbavari 
Cordova CLI: 5.1.1
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
OS: Distributor ID: Ubuntu Description: Ubuntu 14.04 LTS
Node Version: v0.12.7

I kind of reinstalled everything Now I am not getting any error

**Comment by jbavari** [comment]
Good to know. Closing.
