### ISSUE TITLE
TypeError: argument entity must be string, Buffer, or fs.Stats

### ISSUE THREAD

**Issue by LydiaMontagnese** [driftyco/ionic-cli#598]
I am getting this error when I try to run ionic: 

/usr/local/lib/node_modules/ionic/node_modules/serve-static/node_modules/send/node_modules/etag/index.js:55
    throw new TypeError('argument entity must be string, Buffer, or fs.Stats')
          ^
TypeError: argument entity must be string, Buffer, or fs.Stats
    at etag (/usr/local/lib/node_modules/ionic/node_modules/serve-static/node_modules/send/node_modules/etag/index.js:55:11)
    at SendStream.setHeader (/usr/local/lib/node_modules/ionic/node_modules/serve-static/node_modules/send/index.js:724:15)
    at SendStream.send (/usr/local/lib/node_modules/ionic/node_modules/serve-static/node_modules/send/index.js:500:8)
    at onstat (/usr/local/lib/node_modules/ionic/node_modules/serve-static/node_modules/send/index.js:585:10)
    at FSReqWrap.oncomplete (fs.js:95:15)

My node version is v4.1.1

Anyone come across this recently and know a fix?

**Comment by AbdelBa** [comment]
Same error, haven't found anything on the web so I updated manually the `etag` package:

    cd /usr/local/lib/node_modules/ionic/node_modules/serve-static/node_modules/send/
    npm install etag@1.7.0

**Comment by HoraceShmorace** [comment]
Nice, @AbdelBa! I've searching for like 2 hours for how to fix this.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.

**Comment by mohanchalla** [comment]
Still Issue exist. I am getting the following error
 
    throw new TypeError('argument entity must be string, Buffer, or fs.Stats')
    ^

TypeError: argument entity must be string, Buffer, or fs.Stats
    at etag (C:\Users\ABC\AppData\Roaming\npm\node_modules\ionic\node_modules\etag\index.js:55:11)
    at SendStream.setHeader (C:\Users\ABC\AppData\Roaming\npm\node_modules\ionic\node_modules\send\index.js:724:15)
    at SendStream.send (C:\Users\ABC\AppData\Roaming\npm\node_modules\ionic\node_modules\send\index.js:500:8)
    at onstat (C:\Users\ABC\AppData\Roaming\npm\node_modules\ionic\node_modules\send\index.js:585:10)
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by chris087** [comment]
This worked for me:

**cd /usr/local/lib/node_modules/ionic/node_modules/send**

neptune:send chris$ **sudo npm install etag@1.7.0**

- crc@3.0.0 node_modules/crc
send@0.9.1 /usr/local/lib/node_modules/ionic/node_modules/send
└── etag@1.7.0  invalid

it says invalid, but ionic serve will now work.

**Comment by KeithDriscoll** [comment]
The solution @chris087 provided worked for me.

In Windows environment just change the location to:

**C:\Users\{your user folder}\AppData\Roaming\nvm\v6.10.3{might need to change this as well}\node_modules\ionic\node_modules\send**

Then run **npm install etag@1.7.0**
