### ISSUE TITLE
Error: Spawn EACESS ionic 

### ISSUE THREAD

**Issue by flexzero** [driftyco/ionic-cli#602]
cannot build or run it using ionic build android or ionic run android it gives me EACESS error each time

error caught: Error: spawn EACCES
/home/flexzero/Desktop/delta/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                    ^

Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:339:9)
    at module.exports (/home/flexzero/Desktop/delta/platforms/android/cordova/lib/spawn.js:37:35)
    at /home/flexzero/Desktop/delta/platforms/android/cordova/lib/build.js:370:24
    at _fulfilled (/home/flexzero/Desktop/delta/platforms/android/cordova/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/home/flexzero/Desktop/delta/platforms/android/cordova/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/home/flexzero/Desktop/delta/platforms/android/cordova/node_modules/q/q.js:760:13)
    at /home/flexzero/Desktop/delta/platforms/android/cordova/node_modules/q/q.js:821:14
    at flush (/home/flexzero/Desktop/delta/platforms/android/cordova/node_modules/q/q.js:108:17)
ERROR running one or more of the platforms: Error: /home/flexzero/Desktop/delta/platforms/android/cordova/run: Command failed with exit code 1
You may not have the required environment or OS to run this project

my system infromation: 

Your system information:

Cordova CLI: 5.3.3
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.5
Ionic App Lib Version: 0.3.9
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.3 LTS 
Node Version: v4.0.0

**Comment by jorgebermudez** [comment]
Tengo el mismo problema 
+1

**Comment by flexzero** [comment]
@jorgebermudez contento de saber. todavía no se encuentra la manera de arreglar

**Comment by flexzero** [comment]
Okk so i figured out the solution the problem was with the android SDK permissions. Make sure when you move or copy the SDK to the new location change it's permissions with "chmod -R a+rX /<android-sdk-dir>/*" and we are done. :)

**Comment by flexzero** [comment]
Change the permission of android SDK directory under Linux
