### ISSUE TITLE
ionic browser add crosswalk fails with Uh Oh message on linux

### ISSUE THREAD

**Issue by ivanixgames** [driftyco/ionic-cli#651]
Uh oh!
Invalid Version:  (CLI v1.5.5)

My system information:

Cordova CLI: 4.3.0
Ionic Version: 1.1.1
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
OS: Distributor ID:	LinuxMint Description:	Linux Mint 17 Qiana 
Node Version: v0.12.3

Stderr messages:

$ ionic browser add crosswalk
Adding crosswalk browser
You are running Cordova CLI 4.3.0 - installing Cordova Android and Crosswalk manually

Downloaded cordova-crosswalk-engine

Downloaded Cordova Android for Crosswalk

Copying over Crosswalk Webview (arm) to the Crosswalk Engine

Finished copying Crosswalk Webview (arm) to the Crosswalk Engine

Copying over Crosswalk Webview (x86) to the Crosswalk Engine

Finished copying Crosswalk Webview (x86) to the Crosswalk Engine

Downloaded Crosswalk webviews

Removed old Cordova Android platform
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.ivanixmobile.barflygames
	Name: BarFly Games FonApp
	Activity: MainActivity
	Android target: android-21
Copying template files...
Android project created with cordova-android@4.0.0-dev
add to body class: platform-android
all done with platform add stuffs
Added ./engine/cordova-android-c0.6.1/ platform

Added Cordova Android 4.0
4.0.0-dev
Error: [TypeError: Uh oh!
Invalid Version: ]
TypeError: Uh oh!
Invalid Version: 
    at new SemVer (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/node_modules/semver/semver.js:271:11)
    at compare (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/node_modules/semver/semver.js:424:10)
    at Function.lt (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/node_modules/semver/semver.js:458:10)
    at Object.module.exports.framework.install (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/plugman/platforms/android.js:150:62)
    at installWrapper (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/platforms/platforms.js:77:32)
    at Object.ActionStack.process (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/plugman/util/action-stack.js:68:25)
    at handleInstall (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/plugman/install.js:554:20)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/plugman/install.js:346:28
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
 ✗ 
An error with adding Crosswalk browser occured TypeError: Uh oh!
Invalid Version: 

TypeError: Uh oh!
Invalid Version: 
    at new SemVer (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/node_modules/semver/semver.js:271:11)
    at compare (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/node_modules/semver/semver.js:424:10)
    at Function.lt (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/node_modules/semver/semver.js:458:10)
    at Object.module.exports.framework.install (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/plugman/platforms/android.js:150:62)
    at installWrapper (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/platforms/platforms.js:77:32)
    at Object.ActionStack.process (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/plugman/util/action-stack.js:68:25)
    at handleInstall (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/plugman/install.js:554:20)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/src/plugman/install.js:346:28
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)

Uh oh!
Invalid Version:  (CLI v1.5.5)

Your system information:

Cordova CLI: 4.3.0
Ionic Version: 1.1.1
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
OS: Distributor ID:	LinuxMint Description:	Linux Mint 17 Qiana 
Node Version: v0.12.3

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
