### ISSUE TITLE
`ionic generate directive | component | pipe` throws error

### ISSUE THREAD

**Issue by joshuamorony** [driftyco/ionic-cli#671]
Running any of the following commands:

`ionic generate directive test`
`ionic generate component test`
`ionic generate pipe test`

Throws the following error:

Error with generation: [TypeError: Path must be a string. Received undefined]
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at Object.run (/Users/joshuamorony/Documents/apps/ionic2/directive-test/node_modules/ionic-framework/tooling/generators/directive/index.js:13:23)
    at Object.generate (/Users/joshuamorony/Documents/apps/ionic2/directive-test/node_modules/ionic-framework/tooling/generate.js:58:53)
    at Object.IonicTask.run (/usr/local/lib/node_modules/ionic/lib/ionic/generate.js:62:28)
    at Promise.apply (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:1078:26)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:1304:14
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:419:9)

all other generate commands work fine.

Your system information:

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.8.11
Gulp local:
Ionic Version: 2.0.0-alpha.35
Ionic CLI Version: 2.0.0-alpha.25
Ionic App Lib Version: 2.0.0-alpha.24
ios-deploy version: 1.7.0
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v4.2.2
Xcode version: Xcode 7.1 Build version 7B91b

**Comment by mrpatiwi** [comment]
+1

**Comment by obetomuniz** [comment]
+1

**Comment by thaDude** [comment]
+1

... Also, wouldn't it be useful to have this command accept the  `--typescript` option to generate a `.ts` boilerplate file instead of `.js`?

**Comment by tlancina** [comment]
I believe this is fixed in the latest framework version, please let me know if this isn't the case.

**Comment by fisherds** [comment]
It is fixed now which is cool.  For example:
`ionic g component myComponent
`
but it's not in the documentation yet.

http://ionicframework.com/docs/cli/generate/
