### ISSUE TITLE
ReferenceError: argv is not defined on "ionic build"

### ISSUE THREAD

**Issue by mpatel99** [driftyco/ionic-cli#700]
I am trying to build ionic app for ios and android and getting reference error : argv is not defined

ionic app build android

ReferenceError: argv is not defined
    at Object.IonicTask.get (/usr/local/lib/node_modules/ionic/lib/ionic/login.js:105:16)
    at Object.IonicTask.run (/usr/local/lib/node_modules/ionic/lib/ionic/app.js:31:9)
    at Object.run (/usr/local/lib/node_modules/ionic/lib/cli.js:95:32)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/bin/ionic:9:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)

argv is not defined (CLI v1.7.12)

Your system information:

Cordova CLI: 5.4.1
Ionic Version: 1.2.1
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.2 Build version 7C68

**Comment by jgw96** [comment]
Hello! Are you still having this issue with the latest v1 version of the ionic cli, 1.7.14? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
