### ISSUE TITLE
syntaxError when i execute :ionic run ios

### ISSUE THREAD

**Issue by lixiaodong** [driftyco/ionic-cli#723]
✗ Caught exception:
 SyntaxError: Unexpected end of input
    at Object.parse (native)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/node_modules/ionic-xcode/lib/pbxProject.js:39:24)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12) 

---------------------------------------------------------------------------------------------------------------

i installed ionic-2.0.0-beta.15 on mac os.

first,I run ionic create myapp,then i just rewrite some html file,when i run ios again.
this error shows.

Is there anyone who can help me ?please give me some ideas,maybe i use the wrong way?
maybe the version i use was wrong?

**Comment by flexzero** [comment]
check any JSON parsing code in your app.

**Comment by jgw96** [comment]
Hello @lixiaodong ! Are you still having this issue with the latest version of the ionic cli (beta.25)?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
