### ISSUE TITLE
error at ionic serve with ionic beta

### ISSUE THREAD

**Issue by emps** [driftyco/ionic-cli#737]
✗ Caught exception:
 TypeError: glob pattern string required
    at new Minimatch (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\g
ulp-watch\node_modules\glob\node_modules\minimatch\minimatch.js:108:11)
    at setopts (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\gulp-wa
tch\node_modules\glob\common.js:112:20)
    at new Glob (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\gulp-w
atch\node_modules\glob\glob.js:117:3)
    at FSWatcher.processEvent (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_
modules\gulp-watch\index.js:92:35)
    at emitTwo (events.js:87:13)
    at FSWatcher.emit (events.js:172:7)
    at FSWatcher.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_m
odules\gulp-watch\node_modules\chokidar\index.js:172:38)
    at FSWatcher._emit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules
\gulp-watch\node_modules\chokidar\index.js:212:5)
    at FSWatcher._remove (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modul
es\gulp-watch\node_modules\chokidar\index.js:525:50)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\gulp-watch\node_
modules\chokidar\index.js:451:20
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by tlancina** [comment]
Whoop, going to track this in: https://github.com/driftyco/ionic-cli/issues/739 since they're the same.  Would you mind posting when you get this error? Is it editing or deleting a specific file, or on serve?
