### ISSUE TITLE
ionic cli stopped working: undefined:0 error

### ISSUE THREAD

**Issue by eltoky** [driftyco/ionic-cli#738]
I tried to upload source code with ionic cli command and after that ionic cli command is no longer working. I have removed npm ionic package, deleted the .ionic folder in my user folder... almost tried everything but same issue...

Here is the error message:
undefined:0

^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at C:\Users\Frank\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\io-config.js:179:28
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by eltoky** [comment]
Looks like the issue is because of my local project... i created a new project, then copy my source files and it looks fine...

Wondering which local files got corrupted and why?
