### ISSUE TITLE
npm install-g ionic dosent work

### ISSUE THREAD

**Issue by amanuel2** [driftyco/ionic-cli#777]
This is the error. Its driving me nuts!
```

C:\wamp\www>npm install -g ionic
C:\Users\Amanuel\AppData\Roaming\npm\ionic -> C:\Users\Amanuel\AppData\Roaming\npm\node_modules\ionic\bin\ionic

> node-sass@3.4.2 install C:\Users\Amanuel\AppData\Roaming\npm\node_modules\ionic\node_modules\node-sass
> node scripts/install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\wamp\www\scripts\install.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\wamp\www\npm-debug.log

```

**Comment by tlancina** [comment]
Not sure why that script is running from your current directory and not within node-sass.

You might want to try opening an issue over at https://github.com/sass/node-sass/issues.

**Comment by amanuel2** [comment]
I had to update my node js to latest version... turns out i had a old version lol..

**Comment by tlancina** [comment]
Glad it's working! I'm going to close this, feel free to comment if you're still having issues.
