### ISSUE TITLE
bug: cordova add platform error!!!

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#844]
_From @arist1213 on September 21, 2015 15:38_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>I was testing with xcode7 on iOS9 sdk. After I update ionic version to 1.6.4. This error appears.

This is mine currently version:
ionic -v
1.6.4
cordova -v
5.0.0

This is mine error:
ionic start testing blank
cordova platform add ios
Adding ios project...
iOS project created with cordova-ios@3.8.0
Running command: /Users/yanming/Desktop/ionicDemo/testing/hooks/after_prepare/010_add_platform_class.js /Users/yanming/Desktop/ionicDemo/testing
Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at Object.exports.spawn (child_process.js:995:9)
    at Object.exports.spawn (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:100:31)
    at runScriptViaChildProcessSpawn (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:189:23)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:132:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:115:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#4401_

**Comment by jgw96** [comment]
_From @richardsun29 on December 19, 2015 23:55_

Is `010_add_platform_class.js` executable? Try running: 
```
chmod +x /Users/yanming/Desktop/ionicDemo/testing/hooks/after_prepare/010_add_platform_class.js
```

**Comment by jgw96** [comment]
Thanks for opening this issue with us! As this issue is more related to the ionic-cli i will be moving this issue over to that repo, please feel free to continue the conversation on this issue there!

**Comment by tlancina** [comment]
Hey thanks for the issue. This sounds more like a permissions error than a bug with the CLI.  I would recommend updating the CLI to the latest version (1.7.14) and if you are still having problems you could try the forums: https://forum.ionicframework.com/ to see if anyone else has encountered a similar issue.
