### ISSUE TITLE
Error while creating a new ionic v2 project with 'ionic start' cli.

### ISSUE THREAD

**Issue by ssreekanth** [driftyco/ionic-cli#855]
I tried to create a new ionic v2 project using the following command, but it throws error about config.xml (show below).

```
$ ionic start --v2 --ts --sass --no-cordova --skip-npm myApp blank

One awesome Ionic app coming right up...

Creating Ionic app in folder /Users/testuser/Downloads/sandbox/myApp based on blank project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/typescript.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-blank/archive/typescript.zip
Saving your Ionic app state of platforms and plugins
Saved platform
There was an error saving your current Ionic setup
 Error: ENOENT: no such file or directory, open '/Users/testuser/Downloads/sandbox/myApp/config.xml'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.getXmlData (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:287:22)
    at Object.saveExistingPlugins (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:159:29)
    at Object.saveState (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:72:11)
    at Object.Start.finalize (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:1108:9)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:143:18
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)

♬ ♫ ♬ ♫  Your Ionic app is ready to go! ♬ ♫ ♬ ♫

Make sure to cd into your new app directory:
  cd myApp

To run your app in the browser (great for initial development):
  ionic serve

To run on iOS:
  ionic run ios

To run on Android:
  ionic run android

To test your app on a device easily, try Ionic View:
  http://view.ionic.io

Create an Ionic Platform account to add these features to your app?
(Y/n): n

New to Ionic? Get started here: http://ionicframework.com/docs/v2/getting-started

$
```

**Comment by tlancina** [comment]
This should be fixed in the latest beta, but please let me know if you're still having issues, thanks!
