### ISSUE TITLE
ionic.project file not being generated with 2.0beta.22 CLI

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-cli#860]
With a v1 project, it's not creating a v1 ionic.project file at project creation time

**Comment by laidig** [comment]
I have the same problem with the current ionic@beta
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13

```
tony@tPal2:~/temp$ ionic start a blank

One awesome Ionic app coming right up...
...
Error updating config.xml file: TypeError: undefined is not a function
 ✗ TypeError: undefined is not a function
    at Object.module.exports.create (/usr/local/lib/node_modules/ionic/node_modules/xml2js/node_modules/xmlbuilder/lib/index.js:16:22)
    at Builder.exports.Builder.Builder.buildObject (/usr/local/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:165:29)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:860:33
    at Parser.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:384:20)
    at Parser.emit (events.js:107:17)
    at Object.onclosetag (/usr/local/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:348:26)
    at emit (/usr/local/lib/node_modules/ionic/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/usr/local/lib/node_modules/ionic/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
    at closeTag (/usr/local/lib/node_modules/ionic/node_modules/xml2js/node_modules/sax/lib/sax.js:861:5)
    at Object.write (/usr/local/lib/node_modules/ionic/node_modules/xml2js/node_modules/sax/lib/sax.js:1294:29)
```

**Comment by tlancina** [comment]
This should be fixed in the latest beta, let me know if this isn't the case, thanks!
