### ISSUE TITLE
cannot find module babelify

### ISSUE THREAD

**Issue by koinoniki** [driftyco/ionic-cli#864]
ionic -v
2.0.0-beta.22

ionic serve
WARN: ionic.config.js has been deprecated, you can remove it. 

Running 'serve:before' gulp task before serve 
[23:56:01] Starting 'sass'...
[23:56:01] Starting 'html'...
[23:56:01] Starting 'fonts'...
[23:56:01] Starting 'scripts'...
[23:56:01] Finished 'scripts' after 56 ms
[23:56:01] Finished 'html' after 163 ms
[23:56:02] Finished 'fonts' after 440 ms
[23:56:03] Finished 'sass' after 1.71 s
[23:56:03] Starting 'watch'...
 ✗ Caught exception:
 Error: Cannot find module 'babelify' from '/Users/nick/Projects/ionic-projects/MyIonic2Project'
    at /Users/nick/Projects/ionic-projects/MyIonic2Project/node_modules/ionic-gulp-browserify-es2015/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/Users/nick/Projects/ionic-projects/MyIonic2Project/node_modules/ionic-gulp-browserify-es2015/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/nick/Projects/ionic-projects/MyIonic2Project/node_modules/ionic-gulp-browserify-es2015/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/nick/Projects/ionic-projects/MyIonic2Project/node_modules/ionic-gulp-browserify-es2015/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/nick/Projects/ionic-projects/MyIonic2Project/node_modules/ionic-gulp-browserify-es2015/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/nick/Projects/ionic-projects/MyIonic2Project/node_modules/ionic-gulp-browserify-es2015/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by tlancina** [comment]
What is the output of `npm -v`?

**Comment by diosney** [comment]
Mine:

`npm -v` : 2.14.9
`node -v`: v0.12.10

**Comment by tlancina** [comment]
Thanks! Just wanted to make sure. 

So your options are: upgrade to npm3 and reinstall, or install these 3 packages:
 `npm install babelify babel-plugin-transform-decorators-legacy babel-preset-es2015`.

Let me know if that doesn't work :)

**Comment by diosney** [comment]
Installing the additional modules for the older npm worked for me, thanks!

I didn't tested the other wayaround, though (updating node/npm).

**Comment by tlancina** [comment]
Just a heads up, it's recommended to update to npm3 otherwise your build times are going to be very slow: 
    https://phabricator.babeljs.io/T2706
    https://phabricator.babeljs.io/T6756

**Comment by koinoniki** [comment]
excellent, i have upgraded to npm3, and now it works, thanks!

**Comment by diosney** [comment]
Upgraded to node v5 and npm v3 and worked like a charm.
