### ISSUE TITLE
Starting a new project throws undefined is not a function error

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-cli#882]
To reproduce:

1. Run `ionic start a blank --v2`

Error thrown:

```
add to body class: platform-ios
Error updating config.xml file: TypeError: undefined is not a function
✗ TypeError: undefined is not a function
    at Object.module.exports.create (/usr/local/lib/node_modules/ionic/node_modules/xml2js/node_modules/xmlbuilder/lib/index.js:16:22)
    at Builder.exports.Builder.Builder.buildObject (/usr/local/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:165:29)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:860:33
    at Parser.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:384:20)
    at Parser.emit (events.js:107:17)
    at Object.onclosetag (/usr/local/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:348:26)
    at emit (/usr/local/lib/node_modules/ionic/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/usr/local/lib/node_modules/ionic/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
    at closeTag (/usr/local/lib/node_modules/ionic/node_modules/xml2js/node_modules/sax/lib/sax.js:861:5)
    at Object.write (/usr/local/lib/node_modules/ionic/node_modules/xml2js/node_modules/sax/lib/sax.js:1294:29)
```

```
$ ionic -v
2.0.0-beta.23
```

```
$ node -v
v0.12.4
```

```
$ npm -v
3.7.5
```

@tlancina and I went through this and determined it was caused by the xml2js dependency. Should be fixed with the next CLI release but wanted to make an issue for people that run into this.

**Comment by tlancina** [comment]
Also to note that it only occurs on node versions < 4 and updating node will make it go away.

**Comment by tlancina** [comment]
Should be fixed in the latest beta.
