### ISSUE TITLE
Error in starting project

### ISSUE THREAD

**Issue by tomasantunes** [driftyco/ionic-cli#884]
Getting the following error, seems to be related to Hawk.
Any help?

const Hoek = require('hoek');
^^^^^

SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/hawk/lib/index.js:5:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

Use of const in strict mode. (CLI v1.7.14)

Your system information:

Cordova CLI: 6.1.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.4 LTS 
Node Version: v0.10.25

**Comment by tlancina** [comment]
What command are you running to get this error?

**Comment by tomasantunes** [comment]
I was running the command "ionic start myapp". This was later solved by updating node to version 4.

**Comment by tlancina** [comment]
Ah yes that node version is quite old. Going to close this, but please let us know if you're still having issues, thanks!
