### ISSUE TITLE
Using ID Argument Throws An Error

### ISSUE THREAD

**Issue by merktassel** [driftyco/ionic-cli#897]
I was looking into the CLI arguments for creating a new project, and decided to give --id a try:

`ionic start --appname 'My App'  --id 'com.example.my-app' --sass my-app blank`

However, it keeps throwing the following error:

`
Error updating config.xml file: TypeError: packageName.replace is not a function
 ✗ TypeError: packageName.replace is not a function
    at /Users/markcastle/.nvm/versions/node/v4.2.1/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start.js:847:44
    at Parser.<anonymous> (/Users/markcastle/.nvm/versions/node/v4.2.1/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:384:20)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.onclosetag (/Users/markcastle/.nvm/versions/node/v4.2.1/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:348:26)
    at emit (/Users/markcastle/.nvm/versions/node/v4.2.1/lib/node_modules/ionic/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/Users/markcastle/.nvm/versions/node/v4.2.1/lib/node_modules/ionic/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
    at closeTag (/Users/markcastle/.nvm/versions/node/v4.2.1/lib/node_modules/ionic/node_modules/xml2js/node_modules/sax/lib/sax.js:861:5)
    at Object.write (/Users/markcastle/.nvm/versions/node/v4.2.1/lib/node_modules/ionic/node_modules/xml2js/node_modules/sax/lib/sax.js:1294:29)
    at Parser.exports.Parser.Parser.parseString (/Users/markcastle/.nvm/versions/node/v4.2.1/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:403:31)
`

I'm using version 2.0.0-beta.22 of the CLI. Let me know if you need any more information.

**Comment by tlancina** [comment]
Thanks for the issue, is this still an issue with beta.24?

**Comment by merktassel** [comment]
Yes, I just gave it a try and received the same error.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
