### ISSUE TITLE
ionic start issue

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-cli#912]
_From @abhilashenair on March 21, 2016 7:1_

ionic start todo2 example
module.js:341
    throw err;
    ^

Error: Cannot find module 'archiver'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/utils.js:3:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

_Copied from original issue: driftyco/ionic-site#515_

**Comment by perrygovier** [comment]
@abhilashenair could you share more info about your environment? CLI Version, OS, Node version...

**Comment by jgw96** [comment]
Hello all! As it has been a while since there was any activity on this issue i will be closing it for now, but feel free to comment if you are still having the issue.
