### ISSUE TITLE
Ionic browser crosswalk - build fail after adding the crosswalk browser

### ISSUE THREAD

**Issue by jacovc86** [driftyco/ionic-cli#916]
Execution failed for task ':dexArmv7Debug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        C:\Users\Kobico\AppData\Local\Android\sdk\build-tools\23.0.2\dx.bat --dex --no-optimize --output C:\Work\shopiz-mobile-ionic\platforms\android\build\intermediates\dex\armv7\debug --input-list=C:\Work\shopiz-mobile-ionic\platforms\android\build\intermediates\tmp\dex\armv7\debug\inputList.txt
Error Code:
        2
Output:

        UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
                at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
                at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
                at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
                at com.android.dx.command.dexer.Main.run(Main.java:277)
                at com.android.dx.command.dexer.Main.main(Main.java:245)
                at com.android.dx.command.Main.main(Main.java:106)

--- ionic info

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 1.1.0-nightly-1505
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS:
Node Version: v5.10.0

**Comment by tlancina** [comment]
Does running `cordova build` fail as well, or just `ionic build`?

**Comment by jgw96** [comment]
Hello all! As it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if your still having the issue though!
