### ISSUE TITLE
Something wrong with Ionic 2, take a look please (Ionic serve failed)

### ISSUE THREAD

**Issue by speciose** [driftyco/ionic-cli#955]
```
$ ionic serve
WARN: ionic.config.js has been deprecated, you can remove it.

Running 'serve:before' gulp task before serve
[14:07:51] Starting 'clean'...
[14:07:51] Finished 'clean' after 31 ms
[14:07:51] Starting 'watch'...
[14:07:51] Starting 'sass'...
[14:07:51] Starting 'html'...
[14:07:51] Starting 'fonts'...
[14:07:51] Starting 'scripts'...
[14:07:51] Finished 'scripts' after 41 ms
[14:07:51] Finished 'html' after 56 ms
[14:07:51] Finished 'fonts' after 66 ms
[14:07:52] Finished 'sass' after 816 ms
Caught exception:
 Error: watch /home/e/Desktop/MyIonic2Project/app ENOSPC
    at exports._errnoException (util.js:890:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:82:15) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Caught exception:
 Error: watch /home/e/Desktop/MyIonic2Project/app ENOSPC
    at exports._errnoException (util.js:890:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:82:15) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Caught exception:
 Error: watch /home/e/Desktop/MyIonic2Project/app/pages ENOSPC
    at exports._errnoException (util.js:890:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:82:15) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Caught exception:
 Error: watch /home/e/Desktop/MyIonic2Project/app/theme ENOSPC
    at exports._errnoException (util.js:890:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/e/Desktop/MyIonic2Project/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:82:15) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```
a lot of errors (it was just a little part) and in the end:
```
7.5 MB bytes written (9.81 seconds)
[14:16:16] Finished 'watch' after 11 s
[14:16:16] Starting 'serve:before'...
[14:16:16] Finished 'serve:before' after 6.11 μs

WARN: ionic.config.js has been deprecated, you can remove it.
Live Reload failed to start, error: Error: watch /home/e/Desktop/MyIonic2Project/www/build ENOSPC
Ionic serve failed - error: Error: watch /home/e/Desktop/MyIonic2Project/www/build ENOSPC
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

```
it happens on all apps (blank, tutorial, default)
ionic 2.0.0-beta.25

A week ago everything worked fine

**Comment by speciose** [comment]
I've restarted my system and now it's working. Don't know what so say... close this issue if you think that it's not interesting. I don't know what is was.
Forgot to say that I'm using Ubuntu 14 (running through VirtualBox on windows machine)
