### ISSUE TITLE
Error on `ionic share`: Cannot find module './project'

### ISSUE THREAD

**Issue by iignatov** [driftyco/ionic-cli#972]
More details about this issue are available in the following forum topic: [Cannot find module ‘./project’](https://forum.ionicframework.com/t/cannot-find-module-project/50658).

---

Running ionic@2.0.0-beta.25 and from the CLI using the command:
```
ionic share user@domain.tld
```

This throws an error in the CLI in `ionc/lib/ionic/share.js`:
```
Error: Cannot find module './project'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Joe\AppData\Roaming\npm\node_modules\ionic\lib\ionic\share.js:7:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

Cannot find module './project' (CLI v2.0.0-beta.25)
```

Tried to then run `npm install project`, but error still occurs. Can't seem to find a module named project inside the ionic package.

My system information:
```
Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Windows 7 SP1
Node Version: v5.7.0
```

**Comment by galuszkak** [comment]
I wanted to try this fix but I went to problem in #1005

**Comment by ccianciulli** [comment]
Same here

Error: Cannot find module './project'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/lib/ionic/share.js:7:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)


Cannot find module './project' (CLI v2.0.0-beta.25)

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v0.12.4
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jthoms1** [comment]
@iignatov Could you try the latest beta 2.0.0-beta.30 and let me know if it is still occurring for you?  Thanks!

**Comment by iignatov** [comment]
@jthoms1 I just tried with `2.0.0-beta.30` and the error is not thrown anymore - closing the issue.
