### ISSUE TITLE
Unable to run ionic serve

### ISSUE THREAD

**Issue by chandanch** [driftyco/ionic-cli#981]
Hello When try ionic serve --address 52.33.46.9 --port 8100 I get the erro as:
Error: listen EADDRNOTAVAIL 52.33.46.9
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickCallback (node.js:359:17) 

What could be issue for this?

My system information:

Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.3 LTS 
Node Version: v4.4.3

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
