### ISSUE TITLE
ionic run android -l TypeError

### ISSUE THREAD

**Issue by jQrgen** [driftyco/ionic-cli#984]
"ionic run android" produces no bugs, but adding the -l tag spawns a TypeError

<b>Stians-iMac:flare Stian$ ionic run android -l</b>

Error happened TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (/Users/Stian/flareprog/flare/node_modules/karma/node_modules/core-js/modules/_defined.js:3:28)
    at createHTML (/Users/Stian/flareprog/flare/node_modules/karma/node_modules/core-js/modules/_string-html.js:7:19)
    at bold (/Users/Stian/flareprog/flare/node_modules/karma/node_modules/core-js/modules/es6.string.bold.js:5:12)
    at cb (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:206:7)
    at done (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:167:19)
    at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:40:16
    at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:193:9
    at Console.log (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/transports/console.js:127:3)
    at emit (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:186:17)
    at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:157:13
    at _each (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:156:9)
    at Logger.log (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:214:9)
    at target.(anonymous function) [as info](/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/common.js:54:18)
    at Object.IonicTask.setupLiveReload (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/lib/ionic/cordova.js:338:7)
TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (/Users/Stian/flareprog/flare/node_modules/karma/node_modules/core-js/modules/_defined.js:3:28)
    at createHTML (/Users/Stian/flareprog/flare/node_modules/karma/node_modules/core-js/modules/_string-html.js:7:19)
    at bold (/Users/Stian/flareprog/flare/node_modules/karma/node_modules/core-js/modules/es6.string.bold.js:5:12)
    at cb (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:206:7)
    at done (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:167:19)
    at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:40:16
    at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:193:9
    at Console.log (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/transports/console.js:127:3)
    at emit (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:186:17)
    at /Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:157:13
    at _each (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:156:9)
    at Logger.log (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:214:9)
    at target.(anonymous function) [as info](/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/common.js:54:18)
    at Object.IonicTask.setupLiveReload (/Users/Stian/.nvm/versions/node/v5.10.1/lib/node_modules/ionic/lib/ionic/cordova.js:338:7)

<b>Stians-iMac:flare Stian$ ionic info</b>

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.2.1-nightly-1867
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.5 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3 Build version 7D175

**Comment by RTeran** [comment]
I have same problem...

**Comment by ivogallego** [comment]
Me too

**Comment by JohnyGemityg** [comment]
common problem 

Setup Live Reload
server start error: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at Object.checkForDocumentRoot (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/serve.js:248:27)
    at Object.start (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/serve.js:487:16)
    at /usr/lib/node_modules/ionic/lib/utils/cordova.js:257:18
    at _fulfilled (/usr/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/lib/node_modules/ionic/node_modules/q/q.js:108:17)
There was an error serving your Ionic application for run server start error: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at Object.checkForDocumentRoot (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/serve.js:248:27)
    at Object.start (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/serve.js:487:16)
    at /usr/lib/node_modules/ionic/lib/utils/cordova.js:257:18
    at _fulfilled (/usr/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/lib/node_modules/ionic/node_modules/q/q.js:108:17)
undefined
Caught exception:
 undefined 

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.29
Ionic App Lib Version: 2.0.0-beta.16
OS: Distributor ID:	Debian Description:	Debian GNU/Linux 7.10 (wheezy) 
Node Version: v5.11.1

**Comment by email4nickp** [comment]
Also having this issue

**Comment by HuaHub** [comment]
+1

**Comment by ddellamico** [comment]
+1

**Comment by ddellamico** [comment]
Really weird but looks like something related to winston log module ..
Inside the /usr/local/lib/node_modules/ionic/lib/utils/cordova.js  on function "**setupLiveReload**" I removed the first line "log.info(('Setup Live Reload').green.bold);" and all seems to work perfectly, livereload too.

**ionic info**

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by abstiagomarek** [comment]
@ddellamico It worked for me too!

**Comment by coderroggie** [comment]
Similar issue as well for me with ionic upload command.  Command appears to have worked, but the resulting log messages don't give a lot of confidence to that.

```
Uploading app....
Saved app_id, writing to ionic.io.bundle.min.js...

Caught exception:
 TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (/builds/jenkins_home/workspace/Argonaut-Ionic.io-DEV/node_modules/karma/node_modules/core-js/modules/_defined.js:3:28)
    at createHTML (/builds/jenkins_home/workspace/Argonaut-Ionic.io-DEV/node_modules/karma/node_modules/core-js/modules/_string-html.js:7:19)
    at bold (/builds/jenkins_home/workspace/Argonaut-Ionic.io-DEV/node_modules/karma/node_modules/core-js/modules/es6.string.bold.js:5:12)
    at cb (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:206:7)
    at done (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:167:19)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:40:16
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:193:9
    at Console.log (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/transports/console.js:127:3)
    at emit (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:186:17)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:157:13
    at _each (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:156:9)
    at Logger.log (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:214:9)
    at target.(anonymous function) [as info] (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/common.js:54:18)
    at Request._callback (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:150:11) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

**Comment by marcoturi** [comment]
+1

**Comment by jascination** [comment]
This is still happening with me:

```
Caught exception:
 TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (/Users/jvg/Sites/ionic-gulp-es6-starter-kit/node_modules/core-js/modules/_defined.js:3:28)
    at createHTML (/Users/jvg/Sites/ionic-gulp-es6-starter-kit/node_modules/core-js/modules/_string-html.js:7:19)
    at bold (/Users/jvg/Sites/ionic-gulp-es6-starter-kit/node_modules/core-js/modules/es6.string.bold.js:5:12)
    at cb (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:206:7)
    at done (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:167:19)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:40:16
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:193:9
    at Console.log (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/transports/console.js:127:3)
    at emit (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:186:17)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:157:13
    at _each (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/node_modules/async/lib/async.js:156:9)
    at Logger.log (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/logger.js:214:9)
    at target.(anonymous function) [as error] (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/winston/lib/winston/common.js:54:18)
    at Socket.<anonymous> (/usr/local/lib/node_modules/ionic/lib/utils/cordova.js:83:11)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

**Comment by coderroggie** [comment]
Upgrading the ionic-cli to version 2.1.6 fixed the issue for me.  I believe the commit that fixed it was https://github.com/driftyco/ionic-cli/pull/1605

**Comment by jQrgen** [comment]
Works with the updated cli + following specs:
![screen shot 2016-11-12 at 17 39 07](https://cloud.githubusercontent.com/assets/3964957/20239912/fdfa24dc-a90b-11e6-862e-b69556260990.png)
