### ISSUE TITLE
cannot find module errors

### ISSUE THREAD

**Issue by shoaibik** [driftyco/ionic-cli#992]
When I tried to create a new app it gives me error cannot find module 'xxxx', i tried to install that module it then gives error cannot find module (another). I tried 5-6 modules by installing them globally but it still gives me a new error.

```
Error: Cannot find module 'pkginfo'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Shoaia\AppData\Roaming\npm\node_modules\ionic\node_modules\prompt\lib\prompt.js:34:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

Cannot find module 'pkginfo' (CLI v1.7.14)

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS:
Node Version: v4.4.4
```

**Comment by shoaibik** [comment]
reinstalling the ionic fixed the issue.
```
npm cache clean
npm uninstall ionic -g
npm install ionic -g
```
